import type { Species } from "../pantanal";

export type RegionalOccurrenceStatus = "confirmed" | "pending-review" | "not-confirmed";

export type RegionalOccurrenceRecord = {
  speciesId: string;
  scientificName: string;
  region: "Pantanal";
  status: RegionalOccurrenceStatus;
  sourceTitle: string;
  sourceUrl: string;
  queryUrl: string;
  checkedAt: string;
  evidence: string;
};

const icmbioDatasetUrl = "https://collectory.sibbr.gov.br/collectory/public/show/dr327";
const icmbioOccurrenceUrl = "https://ala-hub.sibbr.gov.br/ala-hub/occurrence/search?q=data_resource_uid:dr327";
const gbifMatchUrl = "https://api.gbif.org/v1/species/match?name=Pseudoplatystoma%20corruscans";
const embrapaMirandaUrl = "https://www.infoteca.cnptia.embrapa.br/infoteca/handle/doc/789558";
const gbifPacuUrl = "https://api.gbif.org/v1/species/match?name=Piaractus%20mesopotamicus";
const scieloPacuUrl = "https://www.scielo.br/j/bjb/a/dNGnkpjV7M9Fx7GtyGBD7zg/?format=html&lang=en&ilang=pt_BR";
const gbifPiraputangaUrl = "https://api.gbif.org/v1/species/match?name=Brycon%20hilarii";
const springerPiraputangaUrl = "https://link.springer.com/article/10.1134/S0032945217030092";
const gbifCaranguejoUrl = "https://api.gbif.org/v1/species/match?name=Dilocarcinus%20pagei";
const scieloCaranguejoUrl = "https://www.scielo.br/j/paz/a/8d5vM7nQbcDxLyVHgvPnvQb/?lang=pt";
const gbifCamaraoUrl = "https://api.gbif.org/v1/species/match?name=Macrobrachium%20amazonicum";
const pubmedCamaraoUrl = "https://pubmed.ncbi.nlm.nih.gov/23894962/";
const gbifJauUrl = "https://api.gbif.org/v1/species/match?name=Zungaro%20jahu";
const pubmedJauUrl = "https://pubmed.ncbi.nlm.nih.gov/19372007/";
const gbifArmadeiraUrl = "https://api.gbif.org/v1/species/match?name=Phoneutria%20nigriventer";
const scieloArmadeiraUrl = "https://www.scielo.br/j/isz/a/VnwWHnXJMxyw8mbMxbgsVmx/?lang=pt";
const checkedAt = "2026-08-27";

/**
 * Ledger explícito: confirmação exige fonte regional direta. Quando a busca
 * foi concluída sem evidência suficiente, `not-confirmed` encerra a triagem
 * sem converter ausência de prova em confirmação.
 */
export const regionalOccurrenceRecords: readonly RegionalOccurrenceRecord[] = [
  { speciesId: "pintado", scientificName: "Pseudoplatystoma corruscans", region: "Pantanal", status: "confirmed", sourceTitle: "Embrapa-CPAP — estudo da bacia do rio Miranda, Pantanal de Mato Grosso do Sul", sourceUrl: embrapaMirandaUrl, queryUrl: gbifMatchUrl, checkedAt, evidence: "A publicação da Embrapa analisa explicitamente Pseudoplatystoma corruscans na bacia hidrográfica do rio Miranda, Pantanal do Mato Grosso do Sul, e descreve sua migração, desova nos rios Miranda e Aquidauana e dispersão pelas áreas alagadas. O GBIF/Catalogue of Life confirma Pseudoplatystoma corruscans (Spix & Agassiz, 1829) como espécie aceita. Evidências separadas de ocorrência regional e identidade taxonômica; conservação não inferida." },
  { speciesId: "pacu", scientificName: "Piaractus mesopotamicus", region: "Pantanal", status: "confirmed", sourceTitle: "SciELO — estudo de rendimento por recruta do pacu no Pantanal de Mato Grosso do Sul", sourceUrl: scieloPacuUrl, queryUrl: gbifPacuUrl, checkedAt, evidence: "O artigo publicado no Brazilian Journal of Biology informa que Piaractus mesopotamicus é uma das espécies mais capturadas no Pantanal de Mato Grosso do Sul e analisa dados de peixes capturados na região. O GBIF/Catalogue of Life confirma Piaractus mesopotamicus (Holmberg, 1887) como espécie aceita. Evidências separadas de ocorrência regional e identidade taxonômica; conservação não inferida." },
  { speciesId: "piraputanga", scientificName: "Brycon hilarii", region: "Pantanal", status: "confirmed", sourceTitle: "Springer — populações de Brycon hilarii no Pantanal", sourceUrl: springerPiraputangaUrl, queryUrl: gbifPiraputangaUrl, checkedAt, evidence: "O artigo do Journal of Ichthyology descreve Brycon hilarii como espécie endêmica da bacia hidrográfica do Alto Paraguai e analisa seis coleções na região do Pantanal. Estudo SciELO independente registra 80 exemplares coletados em quatro pontos da sub-bacia do rio Miranda e descreve a espécie como amplamente distribuída pela bacia do rio Paraguai. O GBIF/Catalogue of Life confirma Brycon hilarii (Valenciennes, 1850) como espécie aceita. Evidências separadas de ocorrência regional e identidade taxonômica; conservação não inferida." },
  { speciesId: "caranguejo-agua-doce", scientificName: "Dilocarcinus pagei", region: "Pantanal", status: "confirmed", sourceTitle: "SciELO — distribuição de Trichodactylidae em alagados do Pantanal Mato-Grossense", sourceUrl: scieloCaranguejoUrl, queryUrl: gbifCaranguejoUrl, checkedAt, evidence: "O artigo de Papéis Avulsos de Zoologia estudou caranguejos em alagados do Pantanal Mato-Grossense entre os rios Cuiabá e São Lourenço e nomeia Dilocarcinus pagei entre as espécies registradas na bacia do Alto Paraguai, incluindo as três espécies mais abundantes amostradas. O GBIF/Catalogue of Life confirma Dilocarcinus pagei Stimpson, 1861 como espécie aceita. Evidências separadas de ocorrência regional e identidade taxonômica; conservação não inferida." },
  { speciesId: "camarao-agua-doce", scientificName: "Macrobrachium amazonicum", region: "Pantanal", status: "confirmed", sourceTitle: "PubMed — características reprodutivas e morfométricas de Macrobrachium amazonicum no Pantanal", sourceUrl: pubmedCamaraoUrl, queryUrl: gbifCamaraoUrl, checkedAt, evidence: "O artigo da Revista de Biología Tropical estudou 2.270 exemplares de Macrobrachium amazonicum coletados em dois habitats naturais de água doce — rio Miranda e Lagoa Baiazinha — no Pantanal de Mato Grosso do Sul, Brasil. O GBIF/Catalogue of Life confirma Macrobrachium amazonicum (Heller, 1862) como espécie aceita. Evidências separadas de ocorrência regional e identidade taxonômica; conservação não inferida." },
  { speciesId: "zungaro-jahu", scientificName: "Zungaro jahu", region: "Pantanal", status: "confirmed", sourceTitle: "PubMed — Myxobolus cordeiroi em Zungaro jahu no Pantanal brasileiro", sourceUrl: pubmedJauUrl, queryUrl: gbifJauUrl, checkedAt, evidence: "O estudo parasitológico examinou 50 exemplares de jaú no Pantanal brasileiro e identificou explicitamente o hospedeiro como Zungaro jahu; o artigo descreve Myxobolus cordeiroi infectando essa espécie. O GBIF/Catalogue of Life confirma Zungaro jahu (Ihering, 1898) como espécie aceita. A ocorrência regional é confirmada; a categoria de conservação não é inferida deste registro." },
  { speciesId: "phoneutria-nigriventer", scientificName: "Phoneutria nigriventer", region: "Pantanal", status: "confirmed", sourceTitle: "SciELO — Diversidade e composição da araneofauna do Mato Grosso do Sul, Brasil", sourceUrl: scieloArmadeiraUrl, queryUrl: gbifArmadeiraUrl, checkedAt, evidence: "A compilação científica da araneofauna do Mato Grosso do Sul inclui amostragens no Passo do Lontra, município de Corumbá, e na Serra do Amolar, ambas no Pantanal Sul; Phoneutria nigriventer aparece entre as seis espécies com mais de dez registros no estado. O GBIF/Catalogue of Life confirma Phoneutria nigriventer (Keyserling, 1891) como espécie aceita. A fonte sustenta ocorrência regional no recorte do Pantanal Sul, com a ressalva de que o artigo compila registros em escala estadual e não atribui cada registro individual a uma única localidade." },
  { speciesId: "brycon-orbignyanus", scientificName: "Brycon orbignyanus", region: "Pantanal", status: "not-confirmed", sourceTitle: "UEMS — modelagem de distribuição de Brycon orbignyanus na bacia Paraná–Paraguai", sourceUrl: "https://anaisonline.uems.br/enic/article/download/5212/5238", queryUrl: "https://api.gbif.org/v1/species/match?name=Brycon%20orbignyanus", checkedAt, evidence: "O estudo de modelagem da bacia Paraná–Paraguai projeta adequabilidade no baixo Pantanal, mas não apresenta registro primário de coleta pantaneira para este catálogo. O GBIF/Catalogue of Life confirma o táxon como espécie aceita. A triagem foi encerrada como not-confirmed para o recorte Pantanal: modelagem e ocorrência estruturada isolada não foram promovidas a presença confirmada." },
  { speciesId: "serrasalmus-maculatus", scientificName: "Serrasalmus maculatus", region: "Pantanal", status: "confirmed", sourceTitle: "Check List — Fishes from the Parque Nacional do Pantanal Matogrossense", sourceUrl: "https://checklist.pensoft.net/article/18852/download/pdf/286620", queryUrl: "https://api.gbif.org/v1/species/match?name=Serrasalmus%20maculatus", checkedAt, evidence: "O inventário de campo do Parque Nacional do Pantanal Matogrossense, no alto rio Paraguai, lista nominalmente Serrasalmus maculatus Kner, 1858 entre as espécies coletadas. O GBIF/Catalogue of Life confirma o táxon como espécie aceita; ocorrência regional e identidade taxonômica estão documentadas separadamente." },
  { speciesId: "serrasalmus-marginatus", scientificName: "Serrasalmus marginatus", region: "Pantanal", status: "confirmed", sourceTitle: "Check List — Fishes from the Parque Nacional do Pantanal Matogrossense", sourceUrl: "https://checklist.pensoft.net/article/18852/download/pdf/286620", queryUrl: "https://api.gbif.org/v1/species/match?name=Serrasalmus%20marginatus", checkedAt, evidence: "O inventário de campo do Parque Nacional do Pantanal Matogrossense, no alto rio Paraguai, lista nominalmente Serrasalmus marginatus Valenciennes, 1837 entre as espécies coletadas. O GBIF/Catalogue of Life confirma o táxon como espécie aceita; ocorrência regional e identidade taxonômica estão documentadas separadamente." },
  { speciesId: "gymnotus-inaequilabiatus", scientificName: "Gymnotus inaequilabiatus", region: "Pantanal", status: "confirmed", sourceTitle: "Check List — Fishes from the Parque Nacional do Pantanal Matogrossense", sourceUrl: "https://checklist.pensoft.net/article/18852/download/pdf/286620", queryUrl: "https://api.gbif.org/v1/species/match?name=Gymnotus%20inaequilabiatus", checkedAt, evidence: "O inventário de campo do Parque Nacional do Pantanal Matogrossense, no alto rio Paraguai, lista nominalmente Gymnotus inaequilabiatus (Valenciennes, 1839) entre as espécies coletadas. O GBIF/Catalogue of Life confirma o táxon como espécie aceita; ocorrência regional e identidade taxonômica estão documentadas separadamente." },
  { speciesId: "eigenmannia-virescens", scientificName: "Eigenmannia virescens", region: "Pantanal", status: "confirmed", sourceTitle: "Check List — Fishes from the Parque Nacional do Pantanal Matogrossense", sourceUrl: "https://checklist.pensoft.net/article/18852/download/pdf/286620", queryUrl: "https://api.gbif.org/v1/species/match?name=Eigenmannia%20virescens", checkedAt, evidence: "O inventário de campo do Parque Nacional do Pantanal Matogrossense, no alto rio Paraguai, lista nominalmente Eigenmannia virescens (Valenciennes, 1842) entre as espécies coletadas. O GBIF/Catalogue of Life confirma o táxon como espécie aceita; ocorrência regional e identidade taxonômica estão documentadas separadamente." },
  { speciesId: "rhamdia-quelen", scientificName: "Rhamdia quelen", region: "Pantanal", status: "confirmed", sourceTitle: "IMASUL — Guia Ilustrado dos Peixes do Pantanal e Entorno", sourceUrl: "https://www.imasul.ms.gov.br/wp-content/uploads/2022/11/Montagem-livro-Peixes-VERSAO-FINAL-MARCO-2022-ISBN97865-81066-05-5-ONLINE_FINAL-1.pdf", queryUrl: "https://api.gbif.org/v1/species/match?name=Rhamdia%20quelen", checkedAt, evidence: "O Guia Ilustrado dos Peixes do Pantanal e Entorno, elaborado pelo IMASUL a partir de expedições na Bacia do Alto Paraguai, apresenta a entrada de Rhamdia quelen e legenda espécime registrado no rio Formoso, município de Bonito, MS. O GBIF/Catalogue of Life confirma o táxon como espécie aceita; a fonte regional e a identidade taxonômica são rastreáveis separadamente." },
  { speciesId: "synbranchus-marmoratus", scientificName: "Synbranchus marmoratus", region: "Pantanal", status: "confirmed", sourceTitle: "Check List — Fishes from the Parque Nacional do Pantanal Matogrossense", sourceUrl: "https://checklist.pensoft.net/article/18852/download/pdf/286620", queryUrl: "https://api.gbif.org/v1/species/match?name=Synbranchus%20marmoratus", checkedAt, evidence: "O inventário de campo do Parque Nacional do Pantanal Matogrossense, no alto rio Paraguai, lista nominalmente Synbranchus marmoratus Bloch, 1795 entre as espécies coletadas. O GBIF/Catalogue of Life confirma o táxon como espécie aceita; ocorrência regional e identidade taxonômica estão documentadas separadamente." },
  { speciesId: "crenicichla-britskii", scientificName: "Crenicichla britskii", region: "Pantanal", status: "not-confirmed", sourceTitle: "SciELO — Peixes da planície de inundação do alto rio Paraná e áreas adjacentes", sourceUrl: "https://www.scielo.br/j/ni/a/tScwvm8JLhKnbxKjtBQLPBx/?lang=en", queryUrl: "https://api.gbif.org/v1/species/match?name=Crenicichla%20britskii", checkedAt, evidence: "A publicação consultada registra Crenicichla britskii na planície de inundação do alto rio Paraná, fora do recorte Pantanal deste ledger. O GBIF/Catalogue of Life confirma o táxon como espécie aceita. A triagem foi encerrada como not-confirmed para o recorte Pantanal, sem extrapolar entre bacias." },
  { speciesId: "hemisorubim-platyrhynchos", scientificName: "Hemisorubim platyrhynchos", region: "Pantanal", status: "confirmed", sourceTitle: "Check List — Fishes from the Parque Nacional do Pantanal Matogrossense", sourceUrl: "https://checklist.pensoft.net/article/18852/download/pdf/286620", queryUrl: "https://api.gbif.org/v1/species/match?name=Hemisorubim%20platyrhynchos", checkedAt, evidence: "O inventário de campo do Parque Nacional do Pantanal Matogrossense, no alto rio Paraguai, lista nominalmente Hemisorubim platyrhynchos (Valenciennes, 1840) entre as espécies coletadas. O GBIF/Catalogue of Life confirma o táxon como espécie aceita; ocorrência regional e identidade taxonômica estão documentadas separadamente." },
  { speciesId: "loricariichthys-platymetopon", scientificName: "Loricariichthys platymetopon", region: "Pantanal", status: "confirmed", sourceTitle: "Check List — Fishes from the Parque Nacional do Pantanal Matogrossense", sourceUrl: "https://checklist.pensoft.net/article/18852/download/pdf/286620", queryUrl: "https://api.gbif.org/v1/species/match?name=Loricariichthys%20platymetopon", checkedAt, evidence: "O inventário de campo do Parque Nacional do Pantanal Matogrossense, no alto rio Paraguai, lista nominalmente Loricariichthys platymetopon Isbrücker & Nijssen, 1979 entre as espécies coletadas. O GBIF/Catalogue of Life confirma o táxon como espécie aceita; ocorrência regional e identidade taxonômica estão documentadas separadamente." },
  { speciesId: "paleosuchus-palpebrosus", scientificName: "Paleosuchus palpebrosus", region: "Pantanal", status: "confirmed", sourceTitle: "SciELO — Répteis do Mato Grosso do Sul, Brasil", sourceUrl: "https://www.scielo.br/j/isz/a/hXJx474GnYHQtqpLGtxXcWn/?lang=pt", queryUrl: "https://api.gbif.org/v1/species/match?name=Paleosuchus%20palpebrosus", checkedAt, evidence: "A revisão compilatória de répteis do Mato Grosso do Sul apresenta Paleosuchus palpebrosus (Cuvier, 1807) na tabela de composição estadual com ocorrência indicada no domínio Pantanal (PA). O GBIF/Catalogue of Life confirma o táxon como espécie aceita; a fonte regional e a identidade taxonômica são rastreáveis separadamente." },
  { speciesId: "micrablepharus-maximiliani", scientificName: "Micrablepharus maximiliani", region: "Pantanal", status: "confirmed", sourceTitle: "SciELO — Répteis do Mato Grosso do Sul, Brasil", sourceUrl: "https://www.scielo.br/j/isz/a/hXJx474GnYHQtqpLGtxXcWn/?lang=pt", queryUrl: "https://api.gbif.org/v1/species/match?name=Micrablepharus%20maximiliani", checkedAt, evidence: "A revisão compilatória de répteis do Mato Grosso do Sul apresenta Micrablepharus maximiliani (Reinhardt & Luetken, 1862) na tabela de composição estadual com ocorrência indicada no domínio Pantanal (PA). O GBIF/Catalogue of Life confirma o táxon como espécie aceita; a fonte regional e a identidade taxonômica são rastreáveis separadamente." },
  { speciesId: "phrynops-geoffroanus", scientificName: "Phrynops geoffroanus", region: "Pantanal", status: "confirmed", sourceTitle: "SciELO — Répteis do Mato Grosso do Sul, Brasil", sourceUrl: "https://www.scielo.br/j/isz/a/hXJx474GnYHQtqpLGtxXcWn/?lang=pt", queryUrl: "https://api.gbif.org/v1/species/match?name=Phrynops%20geoffroanus", checkedAt, evidence: "A revisão compilatória de répteis do Mato Grosso do Sul apresenta Phrynops geoffroanus (Schweigger, 1812) na tabela de composição estadual com ocorrência indicada no domínio Pantanal (PA). O GBIF/Catalogue of Life confirma o táxon como espécie aceita; a fonte regional e a identidade taxonômica são rastreáveis separadamente." },
  { speciesId: "podocnemis-unifilis", scientificName: "Podocnemis unifilis", region: "Pantanal", status: "not-confirmed", sourceTitle: "SciELO — Répteis do Mato Grosso do Sul, Brasil", sourceUrl: "https://www.scielo.br/j/isz/a/hXJx474GnYHQtqpLGtxXcWn/?lang=pt", queryUrl: "https://api.gbif.org/v1/species/match?name=Podocnemis%20unifilis", checkedAt, evidence: "A revisão estadual registra Podocnemis unifilis como espécie exótica para o Mato Grosso do Sul, associada à Amazônia e ao Cerrado; a consulta GBIF no recorte operacional retornou 0 ocorrências. A espécie é aceita no GBIF/Catalogue of Life, mas a evidência disponível não sustenta ocorrência pantaneira para este catálogo. A triagem foi encerrada como not-confirmed, sem interpretar o zero como prova isolada de ausência." },
  { speciesId: "hydrodynastes-gigas", scientificName: "Hydrodynastes gigas", region: "Pantanal", status: "confirmed", sourceTitle: "SciELO — Répteis do Mato Grosso do Sul, Brasil", sourceUrl: "https://www.scielo.br/j/isz/a/hXJx474GnYHQtqpLGtxXcWn/?lang=pt", queryUrl: "https://api.gbif.org/v1/species/match?name=Hydrodynastes%20gigas", checkedAt, evidence: "A revisão compilatória de répteis do Mato Grosso do Sul apresenta Hydrodynastes gigas (Duméril et al., 1854) na tabela de composição estadual com ocorrência indicada no domínio Pantanal (PA). O texto também descreve populações aquáticas locais favorecidas por áreas alagadas em Porto Murtinho. O GBIF/Catalogue of Life confirma o táxon como espécie aceita; a fonte regional e a identidade taxonômica são rastreáveis separadamente." },
  { speciesId: "puma-concolor", scientificName: "Puma concolor", region: "Pantanal", status: "confirmed", sourceTitle: "SciELO — Terrestrial and aquatic mammals of the Pantanal", sourceUrl: "https://www.scielo.br/j/bjb/a/ntjhhV3T693jyYtC4zGxHBR/?lang=en", queryUrl: "https://api.gbif.org/v1/species/match?name=Puma%20concolor", checkedAt, evidence: "A revisão de mamíferos do Pantanal menciona Puma concolor no contexto da fauna do Pantanal e descreve sua ocorrência simpátrica com Panthera onca na região. O GBIF/Catalogue of Life confirma o táxon como espécie aceita; ocorrência regional e identidade taxonômica são rastreáveis separadamente." },
  { speciesId: "lontra-longicaudis", scientificName: "Lontra longicaudis", region: "Pantanal", status: "confirmed", sourceTitle: "SciELO — Terrestrial and aquatic mammals of the Pantanal", sourceUrl: "https://www.scielo.br/j/bjb/a/ntjhhV3T693jyYtC4zGxHBR/?lang=en", queryUrl: "https://api.gbif.org/v1/species/match?name=Lontra%20longicaudis", checkedAt, evidence: "A revisão de mamíferos do Pantanal identifica Lontra longicaudis como uma das duas espécies de mustelídeos adaptadas à vida aquática no Pantanal e descreve sua dependência das margens dos rios. O GBIF/Catalogue of Life confirma o táxon como espécie aceita." },
  { speciesId: "ariranha", scientificName: "Pteronura brasiliensis", region: "Pantanal", status: "confirmed", sourceTitle: "SciELO — Terrestrial and aquatic mammals of the Pantanal", sourceUrl: "https://www.scielo.br/j/bjb/a/ntjhhV3T693jyYtC4zGxHBR/?lang=en", queryUrl: "https://api.gbif.org/v1/species/match?name=Pteronura%20brasiliensis", checkedAt, evidence: "A revisão de mamíferos do Pantanal identifica Pteronura brasiliensis como espécie de mustelídeo adaptada à vida aquática no Pantanal. O GBIF/Catalogue of Life confirma o táxon como espécie aceita." },
  { speciesId: "quati", scientificName: "Nasua nasua", region: "Pantanal", status: "confirmed", sourceTitle: "SciELO — Terrestrial and aquatic mammals of the Pantanal", sourceUrl: "https://www.scielo.br/j/bjb/a/ntjhhV3T693jyYtC4zGxHBR/?lang=en", queryUrl: "https://api.gbif.org/v1/species/match?name=Nasua%20nasua", checkedAt, evidence: "A revisão de mamíferos do Pantanal inclui Nasua nasua entre as espécies dependentes de habitats arbóreos e florestais do Pantanal. O GBIF/Catalogue of Life confirma o táxon como espécie aceita." },
  { speciesId: "rhea-americana", scientificName: "Rhea americana", region: "Pantanal", status: "not-confirmed", sourceTitle: "SciELO — Checklist of the birds of Mato Grosso do Sul state, Brazil", sourceUrl: "https://www.scielo.br/j/paz/a/CtXKR4YMyrsG4ttMdRP7JYR/?lang", queryUrl: "https://api.gbif.org/v1/species/match?name=Rhea%20americana", checkedAt, evidence: "A checklist estadual registra Rhea americana para Mato Grosso do Sul, mas a tabela consultada não vincula esta entrada a uma localidade pantaneira individual. O GBIF/Catalogue of Life confirma o táxon como espécie aceita; a triagem foi encerrada como not-confirmed para o recorte Pantanal, sem extrapolar do estado inteiro." },
  { speciesId: "anhinga-anhinga", scientificName: "Anhinga anhinga", region: "Pantanal", status: "not-confirmed", sourceTitle: "SciELO — Checklist of the birds of Mato Grosso do Sul state, Brazil", sourceUrl: "https://www.scielo.br/j/paz/a/CtXKR4YMyrsG4ttMdRP7JYR/?lang", queryUrl: "https://api.gbif.org/v1/species/match?name=Anhinga%20anhinga", checkedAt, evidence: "A checklist estadual registra Anhinga anhinga para Mato Grosso do Sul, mas a tabela consultada não vincula esta entrada a uma localidade pantaneira individual. O GBIF/Catalogue of Life confirma o táxon como espécie aceita; a triagem foi encerrada como not-confirmed para o recorte Pantanal, sem extrapolar do estado inteiro." },
  { speciesId: "eudocimus-ruber", scientificName: "Eudocimus ruber", region: "Pantanal", status: "not-confirmed", sourceTitle: "SciELO — Checklist of the birds of Mato Grosso do Sul state, Brazil", sourceUrl: "https://www.scielo.br/j/paz/a/CtXKR4YMyrsG4ttMdRP7JYR/?lang", queryUrl: "https://api.gbif.org/v1/species/match?name=Eudocimus%20ruber", checkedAt, evidence: "A checklist estadual consultada não apresenta correspondência nominal para Eudocimus ruber nos registros revisados de Mato Grosso do Sul. O GBIF/Catalogue of Life confirma a identidade taxonômica; a triagem foi encerrada como not-confirmed para o Pantanal, sem usar ausência da checklist como prova absoluta." },
  { speciesId: "caracara-plancus", scientificName: "Caracara plancus", region: "Pantanal", status: "not-confirmed", sourceTitle: "SciELO — Checklist of the birds of Mato Grosso do Sul state, Brazil", sourceUrl: "https://www.scielo.br/j/paz/a/CtXKR4YMyrsG4ttMdRP7JYR/?lang", queryUrl: "https://api.gbif.org/v1/species/match?name=Caracara%20plancus", checkedAt, evidence: "A checklist estadual registra Caracara plancus para Mato Grosso do Sul, mas a tabela consultada não vincula esta entrada a uma localidade pantaneira individual. O GBIF/Catalogue of Life confirma o táxon como espécie aceita; a triagem foi encerrada como not-confirmed para o recorte Pantanal, sem extrapolar do estado inteiro." },
  { speciesId: "eupsittula-nenday", scientificName: "Eupsittula nenday", region: "Pantanal", status: "not-confirmed", sourceTitle: "SciELO — Checklist of the birds of Mato Grosso do Sul state, Brazil", sourceUrl: "https://www.scielo.br/j/paz/a/CtXKR4YMyrsG4ttMdRP7JYR/?lang", queryUrl: "https://api.gbif.org/v1/species/match?name=Eupsittula%20nenday", checkedAt, evidence: "A checklist estadual consultada não apresenta correspondência nominal para Eupsittula nenday nos registros revisados de Mato Grosso do Sul. O GBIF/Catalogue of Life confirma a identidade taxonômica; a triagem foi encerrada como not-confirmed para o Pantanal, sem usar ausência da checklist como prova absoluta." },
];

export function validateRegionalOccurrenceRecords(records: readonly RegionalOccurrenceRecord[]): string[] {
  const errors: string[] = [];
  for (const record of records) {
    if (!record.speciesId.trim()) errors.push("registro regional sem speciesId");
    if (record.region !== "Pantanal") errors.push(`${record.speciesId}: região regional inválida`);
    if (!/^https:\/\//.test(record.sourceUrl) || !/^https:\/\//.test(record.queryUrl)) errors.push(`${record.speciesId}: fonte regional sem HTTPS`);
    if (!record.evidence.trim()) errors.push(`${record.speciesId}: evidência regional ausente`);
    if (record.status === "confirmed" && record.evidence.includes("não retornou")) errors.push(`${record.speciesId}: confirmação incompatível com evidência pendente`);
  }
  return errors;
}
