import type { CatalogBatch } from "../types";

const image = (uri: string, author: string, license: string, sourceUrl: string) => ({ uri, author, license, sourceUrl, credit: `${author} / Wikimedia Commons` });

export const amphibians02: CatalogBatch = {
  batchId: "catalog-amphibians-02",
  cycle: 10,
  group: "Anfíbios",
  status: "pending-review",
  sources: [
    { title: "GBIF Species Match — Rhinella diptycha (accepted name)", url: "https://api.gbif.org/v1/species/match?name=Rhinella%20diptycha" },
    { title: "GBIF Species Match — Leptodactylus chaquensis", url: "https://api.gbif.org/v1/species/match?name=Leptodactylus%20chaquensis" },
    { title: "GBIF Species Match — Scinax fuscomarginatus", url: "https://api.gbif.org/v1/species/match?name=Scinax%20fuscomarginatus" },
    { title: "GBIF Species Match — Pithecopus azureus (accepted name)", url: "https://api.gbif.org/v1/species/match?name=Pithecopus%20azureus" },
  ],
  pendingNotes: ["Confirmar páginas individuais das imagens e revisão de distribuição local antes de promover o lote.", "Scinax fuscomarginatus e Pithecopus azureus permanecem bloqueadas até existir uma terceira imagem específica, licenciada e verificável para cada espécie; não reutilizar imagens de espécies próximas.", "O GBIF trata Rhinella schneideri como sinônimo de Rhinella diptycha e Phyllomedusa azurea como sinônimo de Pithecopus azureus; aliases históricos não devem ser apresentados como nomes aceitos."],
  species: [
    {
      id: "sapinho-cururu", commonName: "Sapo-cururu", scientificName: "Rhinella diptycha", group: "Anfíbios", environments: ["Campos", "Bordas de mata"], description: "Sapo de grande porte que ocupa áreas abertas e bordas, especialmente próximo a abrigos úmidos.", physicalCharacteristics: "Pele rugosa, glândulas parotoides desenvolvidas e corpo robusto.", habitat: "Campos, jardins, bordas de mata e margens de áreas úmidas.", behavior: "Ativo principalmente à noite e após chuvas, quando busca alimento e parceiros.", diet: "Insetos, aranhas e outros pequenos invertebrados.", curiosities: ["A pele rugosa ajuda na camuflagem e na proteção.", "A reprodução costuma acompanhar o início das chuvas."], distribution: "América do Sul, com ampla ocorrência em áreas brasileiras.", ecologicalImportance: "Controla invertebrados e serve de alimento para predadores especializados.", images: [image("https://upload.wikimedia.org/wikipedia/commons/f/ff/Bufo_schneideri.jpg", "user:Dawson", "CC BY-SA 2.5", "https://commons.wikimedia.org/wiki/File:Bufo_schneideri.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/4/48/Cururu_%28Rhinella_schneideri%29%2C_Uruguay%2C_2015.jpg", "Enrique González", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Cururu_(Rhinella_schneideri),_Uruguay,_2015.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/1/1f/Curur%C3%BA%2C_%28Rhinella_schneideri%29%2C_Uruguay%2C_2019.jpg", "Enrique González", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Cururú,_(Rhinella_schneideri),_Uruguay,_2019.jpg")], sources: [{ title: "GBIF Species Match — Rhinella diptycha (accepted name)", url: "https://api.gbif.org/v1/species/match?name=Rhinella%20diptycha" }],
    },
    {
      id: "rã-pimenta", commonName: "Rã-pimenta", scientificName: "Leptodactylus chaquensis", group: "Anfíbios", environments: ["Áreas alagadas", "Campos"], description: "Rã terrestre de áreas abertas e úmidas, associada a poças temporárias e margens vegetadas.", physicalCharacteristics: "Corpo robusto, coloração castanha e membros posteriores fortes.", habitat: "Campos inundáveis, banhados, poças temporárias e margens de lagoas.", behavior: "Permanece escondida durante períodos secos e vocaliza após chuvas.", diet: "Insetos, larvas, aranhas e pequenos invertebrados.", curiosities: ["Poças temporárias podem ser importantes para a reprodução.", "A atividade aumenta com umidade e temperatura favoráveis."], distribution: "Bacia do Paraguai e outras regiões úmidas do centro da América do Sul.", ecologicalImportance: "Controla invertebrados e indica a disponibilidade de microhabitats úmidos.", images: [image("https://upload.wikimedia.org/wikipedia/commons/1/1c/Leptodactylus_chaquensis.jpg", "Axel Kwet", "CC BY-SA 2.5", "https://commons.wikimedia.org/wiki/File:Leptodactylus_chaquensis.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/e/e7/Leptodactylus_chaquensis06.jpg", "Diogo B. Provete", "CC BY-SA 2.5", "https://commons.wikimedia.org/wiki/File:Leptodactylus_chaquensis06.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/8/85/Leptodactylus_chaquensis_08.jpg", "Rhalah", "CC0", "https://commons.wikimedia.org/wiki/File:Leptodactylus_chaquensis_08.jpg")], sources: [{ title: "GBIF Species Match — Leptodactylus chaquensis", url: "https://api.gbif.org/v1/species/match?name=Leptodactylus%20chaquensis" }],
    },
    {
      id: "perereca-fuscomarginata", commonName: "Perereca-de-margem-escura", scientificName: "Scinax fuscomarginatus", group: "Anfíbios", environments: ["Campos", "Bordas de mata"], description: "Pequena perereca que utiliza vegetação baixa e áreas úmidas próximas a corpos d'água.", physicalCharacteristics: "Corpo pequeno, discos adesivos nos dedos e faixa escura lateral.", habitat: "Capins, arbustos, bordas e vegetação ao redor de poças.", behavior: "Vocaliza sobre folhas e ramos durante a estação chuvosa.", diet: "Pequenos insetos e outros artrópodes.", curiosities: ["Os discos adesivos permitem subir em folhas lisas.", "A vocalização ajuda a localizar indivíduos em meio à vegetação."], distribution: "Brasil central e outras áreas da América do Sul tropical.", ecologicalImportance: "Controla pequenos artrópodes e integra a fauna de poças temporárias.", images: [image("https://upload.wikimedia.org/wikipedia/commons/1/1c/Scinax_fuscomarginatus01.jpg", "Lucas Grandinetti", "CC BY-SA 2.5", "https://commons.wikimedia.org/wiki/File:Scinax_fuscomarginatus01.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/a/a2/Scinax_fuscomarginatus02.jpg", "Lucas Grandinetti", "CC BY-SA 2.5", "https://commons.wikimedia.org/wiki/File:Scinax_fuscomarginatus02.jpg")], sources: [{ title: "GBIF Species Match — Scinax fuscomarginatus", url: "https://api.gbif.org/v1/species/match?name=Scinax%20fuscomarginatus" }],
    },
    {
      id: "perereca-folhagem-azul", commonName: "Perereca-de-folhagem-azul", scientificName: "Pithecopus azureus", group: "Anfíbios", environments: ["Matas", "Bordas de mata"], description: "Perereca arborícola de hábitos noturnos que utiliza folhas e galhos em ambientes de mata.", physicalCharacteristics: "Corpo verde, membros longos, discos adesivos e coloração contrastante nas partes internas.", habitat: "Matas ciliares, arbustos, capões e bordas próximas de água.", behavior: "Move-se lentamente pela vegetação e permanece imóvel durante o dia.", diet: "Insetos e outros pequenos artrópodes.", curiosities: ["A postura imóvel reduz a chance de ser detectada.", "A reprodução depende de folhas e água em ambientes próximos."], distribution: "Centro da América do Sul, incluindo regiões do Chaco e Pantanal.", ecologicalImportance: "Participa do controle de insetos e indica a qualidade da vegetação ripária.", images: [image("https://upload.wikimedia.org/wikipedia/commons/e/e3/Phyllomedusa_azurea.jpg", "Ariovaldo Giaretta", "CC BY-SA 2.5", "https://commons.wikimedia.org/wiki/File:Phyllomedusa_azurea.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/d/d5/Phyllomedusa_azurea01.jpg", "Lucas Grandinetti", "CC BY-SA 2.5", "https://commons.wikimedia.org/wiki/File:Phyllomedusa_azurea01.jpg")], sources: [{ title: "GBIF Species Match — Pithecopus azureus (accepted name)", url: "https://api.gbif.org/v1/species/match?name=Pithecopus%20azureus" }],
    },
  ],
};
