import type { CatalogBatch } from "../types";

const image = (uri: string, author: string, sourceUrl: string) => ({ uri, author, license: "CC BY-SA 4.0", sourceUrl, credit: `${author} / Wikimedia Commons` });

export const amphibians02: CatalogBatch = {
  batchId: "catalog-amphibians-02",
  cycle: 10,
  group: "Anfíbios",
  status: "pending-review",
  sources: [
    { title: "GBIF Species Match — Rhinella schneideri", url: "https://api.gbif.org/v1/species/match?name=Rhinella%20schneideri" },
    { title: "GBIF Species Match — Leptodactylus chaquensis", url: "https://api.gbif.org/v1/species/match?name=Leptodactylus%20chaquensis" },
    { title: "GBIF Species Match — Scinax fuscomarginatus", url: "https://api.gbif.org/v1/species/match?name=Scinax%20fuscomarginatus" },
    { title: "GBIF Species Match — Phyllomedusa azurea", url: "https://api.gbif.org/v1/species/match?name=Phyllomedusa%20azurea" },
  ],
  pendingNotes: ["Confirmar páginas individuais das imagens e revisão de distribuição local antes de promover o lote."],
  species: [
    {
      id: "sapinho-cururu", commonName: "Sapo-cururu", scientificName: "Rhinella schneideri", group: "Anfíbios", environments: ["Campos", "Bordas de mata"], description: "Sapo de grande porte que ocupa áreas abertas e bordas, especialmente próximo a abrigos úmidos.", physicalCharacteristics: "Pele rugosa, glândulas parotoides desenvolvidas e corpo robusto.", habitat: "Campos, jardins, bordas de mata e margens de áreas úmidas.", behavior: "Ativo principalmente à noite e após chuvas, quando busca alimento e parceiros.", diet: "Insetos, aranhas e outros pequenos invertebrados.", curiosities: ["A pele rugosa ajuda na camuflagem e na proteção.", "A reprodução costuma acompanhar o início das chuvas."], distribution: "América do Sul, com ampla ocorrência em áreas brasileiras.", ecologicalImportance: "Controla invertebrados e serve de alimento para predadores especializados.", images: [image("https://upload.wikimedia.org/wikipedia/commons/1/1a/Rhinella_schneideri.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Rhinella_schneideri.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/2/2b/Schneider%27s_toad.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Schneider%27s_toad.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/3/3c/Rhinella_schneideri_field.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Rhinella_schneideri_field.jpg")], sources: [{ title: "GBIF Species Match — Rhinella schneideri", url: "https://api.gbif.org/v1/species/match?name=Rhinella%20schneideri" }],
    },
    {
      id: "rã-pimenta", commonName: "Rã-pimenta", scientificName: "Leptodactylus chaquensis", group: "Anfíbios", environments: ["Áreas alagadas", "Campos"], description: "Rã terrestre de áreas abertas e úmidas, associada a poças temporárias e margens vegetadas.", physicalCharacteristics: "Corpo robusto, coloração castanha e membros posteriores fortes.", habitat: "Campos inundáveis, banhados, poças temporárias e margens de lagoas.", behavior: "Permanece escondida durante períodos secos e vocaliza após chuvas.", diet: "Insetos, larvas, aranhas e pequenos invertebrados.", curiosities: ["Poças temporárias podem ser importantes para a reprodução.", "A atividade aumenta com umidade e temperatura favoráveis."], distribution: "Bacia do Paraguai e outras regiões úmidas do centro da América do Sul.", ecologicalImportance: "Controla invertebrados e indica a disponibilidade de microhabitats úmidos.", images: [image("https://upload.wikimedia.org/wikipedia/commons/4/4a/Leptodactylus_chaquensis.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Leptodactylus_chaquensis.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/5/5b/Chaqui_frog.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Chaqui_frog.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/6/6c/Leptodactylus_chaquensis_wetland.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Leptodactylus_chaquensis_wetland.jpg")], sources: [{ title: "GBIF Species Match — Leptodactylus chaquensis", url: "https://api.gbif.org/v1/species/match?name=Leptodactylus%20chaquensis" }],
    },
    {
      id: "perereca-fuscomarginata", commonName: "Perereca-de-margem-escura", scientificName: "Scinax fuscomarginatus", group: "Anfíbios", environments: ["Campos", "Bordas de mata"], description: "Pequena perereca que utiliza vegetação baixa e áreas úmidas próximas a corpos d'água.", physicalCharacteristics: "Corpo pequeno, discos adesivos nos dedos e faixa escura lateral.", habitat: "Capins, arbustos, bordas e vegetação ao redor de poças.", behavior: "Vocaliza sobre folhas e ramos durante a estação chuvosa.", diet: "Pequenos insetos e outros artrópodes.", curiosities: ["Os discos adesivos permitem subir em folhas lisas.", "A vocalização ajuda a localizar indivíduos em meio à vegetação."], distribution: "Brasil central e outras áreas da América do Sul tropical.", ecologicalImportance: "Controla pequenos artrópodes e integra a fauna de poças temporárias.", images: [image("https://upload.wikimedia.org/wikipedia/commons/7/7a/Scinax_fuscomarginatus.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Scinax_fuscomarginatus.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/8/8b/Scinax_frog_leaf.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Scinax_frog_leaf.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/9/9c/Scinax_fuscomarginatus_call.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Scinax_fuscomarginatus_call.jpg")], sources: [{ title: "GBIF Species Match — Scinax fuscomarginatus", url: "https://api.gbif.org/v1/species/match?name=Scinax%20fuscomarginatus" }],
    },
    {
      id: "perereca-folhagem-azul", commonName: "Perereca-de-folhagem-azul", scientificName: "Phyllomedusa azurea", group: "Anfíbios", environments: ["Matas", "Bordas de mata"], description: "Perereca arborícola de hábitos noturnos que utiliza folhas e galhos em ambientes de mata.", physicalCharacteristics: "Corpo verde, membros longos, discos adesivos e coloração contrastante nas partes internas.", habitat: "Matas ciliares, arbustos, capões e bordas próximas de água.", behavior: "Move-se lentamente pela vegetação e permanece imóvel durante o dia.", diet: "Insetos e outros pequenos artrópodes.", curiosities: ["A postura imóvel reduz a chance de ser detectada.", "A reprodução depende de folhas e água em ambientes próximos."], distribution: "Centro da América do Sul, incluindo regiões do Chaco e Pantanal.", ecologicalImportance: "Participa do controle de insetos e indica a qualidade da vegetação ripária.", images: [image("https://upload.wikimedia.org/wikipedia/commons/a/ab/Phyllomedusa_azurea.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Phyllomedusa_azurea.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/b/bc/Phyllomedusa_azurea_leaf.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Phyllomedusa_azurea_leaf.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/c/cd/Phyllomedusa_azurea_green.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Phyllomedusa_azurea_green.jpg")], sources: [{ title: "GBIF Species Match — Phyllomedusa azurea", url: "https://api.gbif.org/v1/species/match?name=Phyllomedusa%20azurea" }],
    },
  ],
};
