import type { CatalogBatch } from "../types";

const image = (uri: string, author: string, license: string, sourceUrl: string) => ({ uri, author, license, sourceUrl, credit: `${author} / Wikimedia Commons` });

export const birds03: CatalogBatch = {
  batchId: "catalog-birds-03",
  cycle: 6,
  group: "Aves",
  status: "pending-review",
  sources: [
    { title: "GBIF Species Match — Ara ararauna", url: "https://api.gbif.org/v1/species/match?name=Ara%20ararauna" },
    { title: "GBIF Species Match — Coragyps atratus", url: "https://api.gbif.org/v1/species/match?name=Coragyps%20atratus" },
    { title: "GBIF Species Match — Ramphastos toco", url: "https://api.gbif.org/v1/species/match?name=Ramphastos%20toco" },
  ],
  pendingNotes: [
    "Imagens, créditos e licenças foram conferidos individualmente e as URLs retornaram HTTP 200.",
    "Manter pending-review até registrar evidência individual de ocorrência no Pantanal, fonte oficial de conservação quando aplicável, reviewedAt/reviewedBy e checklist editorial completo."
  ],
  species: [
    {
      id: "arara-caninde", commonName: "Arara-canindé", scientificName: "Ara ararauna", group: "Aves", environments: ["Matas", "Bordas de mata"], description: "Arara de grande porte e plumagem azul e amarela, associada a matas e áreas abertas com árvores altas.", physicalCharacteristics: "Asas azuis, peito amarelo, bico forte e cauda longa.", habitat: "Matas ciliares, florestas abertas, bordas e palmeirais.", behavior: "Vive em pares ou grupos e utiliza ocos de árvores para repouso e reprodução.", diet: "Frutos, sementes, castanhas e partes de plantas.", curiosities: ["O bico quebra sementes resistentes.", "Deslocamentos em grupo podem conectar diferentes fragmentos de mata."], distribution: "América do Sul tropical, incluindo áreas do Pantanal.", ecologicalImportance: "Dispersa sementes e depende de árvores maduras para abrigo e nidificação.", images: [image("https://upload.wikimedia.org/wikipedia/commons/e/ec/Ara_ararauna_Luc_Viatour.jpg", "Luc Viatour", "CC BY 2.0", "https://commons.wikimedia.org/wiki/File:Ara_ararauna_Luc_Viatour.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/9/9c/Ara_ararauna_%28Linnaeus_1758%29.jpg", "Michael Gäbler", "CC BY 3.0", "https://commons.wikimedia.org/wiki/File:Ara_ararauna_(Linnaeus_1758).jpg"), image("https://upload.wikimedia.org/wikipedia/commons/6/60/Ara_ararauna_qtl3.jpg", "Quartl", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Ara_ararauna_qtl3.jpg")], sources: [{ title: "GBIF Species Match — Ara ararauna", url: "https://api.gbif.org/v1/species/match?name=Ara%20ararauna" }],
    },
    {
      id: "urubu-de-cabeca-preta", commonName: "Urubu-de-cabeça-preta", scientificName: "Coragyps atratus", group: "Aves", environments: ["Campos", "Bordas de mata"], description: "Ave necrófaga comum em áreas abertas, cidades, margens de rios e bordas de mata.", physicalCharacteristics: "Plumagem escura, cabeça sem penas, asas largas e voo planado.", habitat: "Campos, bordas, áreas urbanizadas e margens de ambientes aquáticos.", behavior: "Forma grupos, usa correntes térmicas e localiza carcaças por visão e comportamento coletivo.", diet: "Carcaças, restos orgânicos e pequenos animais já mortos.", curiosities: ["O voo planado reduz o gasto energético.", "A remoção de carcaças contribui para a ciclagem de nutrientes."], distribution: "Américas, com ampla ocorrência no Brasil e no Pantanal.", ecologicalImportance: "Recicla matéria orgânica e ajuda a reduzir focos de decomposição exposta.", images: [image("https://upload.wikimedia.org/wikipedia/commons/5/5c/Coragyps-atratus-002.jpg", "Mdf", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Coragyps-atratus-002.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/9/9d/Coragyps-atratus-001.jpg", "Mdf", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Coragyps-atratus-001.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/c/cd/Coragyps_atratus_brasiliensis_Black_vulture_Bel%C3%A9m_01.jpg", "Cayambe", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Coragyps_atratus_brasiliensis_Black_vulture_Bel%C3%A9m_01.jpg")], sources: [{ title: "GBIF Species Match — Coragyps atratus", url: "https://api.gbif.org/v1/species/match?name=Coragyps%20atratus" }],
    },
    {
      id: "tucano-toco", commonName: "Tucano-toco", scientificName: "Ramphastos toco", group: "Aves", environments: ["Matas", "Bordas de mata"], description: "Tucano de bico grande que explora árvores frutíferas, cerrados e bordas florestais.", physicalCharacteristics: "Bico alaranjado de grande dimensão, plumagem preta e garganta branca.", habitat: "Matas abertas, cerrados, bordas e capões de mata.", behavior: "Desloca-se entre árvores e engole frutos inteiros, podendo formar pares ou pequenos grupos.", diet: "Frutos, ovos, filhotes de outras aves e pequenos vertebrados.", curiosities: ["O bico participa da termorregulação e da obtenção de alimento.", "A espécie pode usar ocos naturais para nidificar."], distribution: "Centro e leste da América do Sul, incluindo o Pantanal.", ecologicalImportance: "Dispersa sementes e influencia a regeneração de espécies vegetais.", images: [image("https://upload.wikimedia.org/wikipedia/commons/8/8f/Toco_toucan_%28Ramphastos_toco%29_in_flight_composite.jpg", "Charles J. Sharp", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Toco_toucan_(Ramphastos_toco)_in_flight_composite.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/3/36/Toco_toucan_%28Ramphastos_toco%29_drinking_composite.jpg", "Charles J. Sharp", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Toco_toucan_(Ramphastos_toco)_drinking_composite.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/f/f8/Toco_Toucan_%28Ramphastos_toco%29_-_48153967707.jpg", "Bernard DUPONT", "CC BY-SA 2.0", "https://commons.wikimedia.org/wiki/File:Toco_Toucan_(Ramphastos_toco)_-_48153967707.jpg")], sources: [{ title: "GBIF Species Match — Ramphastos toco", url: "https://api.gbif.org/v1/species/match?name=Ramphastos%20toco" }],
    },
  ],
};
