import type { CatalogBatch } from "../types";

const image = (uri: string, author: string, license: string, sourceUrl: string, credit: string) => ({ uri, author, license, sourceUrl, credit });
const gbif = (name: string) => ({ title: `GBIF Species Match — ${name}`, url: `https://api.gbif.org/v1/species/match?name=${encodeURIComponent(name)}` });

export const birds05: CatalogBatch = {
  batchId: "catalog-birds-05", cycle: 6, group: "Aves", status: "pending-review",
  sources: [gbif("Egretta thula"), gbif("Pitangus sulphuratus"), gbif("Sicalis flaveola")],
  pendingNotes: ["Confirmar ocorrência no recorte do Pantanal e eventual conservação em fonte ICMBio/MMA; imagens não substituem ocorrência regional."],
  species: [
    { id: "egretta-thula", commonName: "Garça-branca-pequena", scientificName: "Egretta thula", group: "Aves", environments: ["Áreas alagadas", "Rios e corixos"], description: "Garça pequena de plumagem branca que procura presas em águas rasas e margens abertas.", physicalCharacteristics: "Plumagem branca, bico escuro, pernas escuras e dedos amarelos, especialmente evidentes durante a alimentação.", habitat: "Lagoas, rios, corixos, banhados, estuários e margens com água rasa.", behavior: "Caminha ou permanece imóvel na água rasa e captura presas com golpes rápidos do bico.", diet: "Pequenos peixes, crustáceos, insetos, anfíbios e outros animais aquáticos.", curiosities: ["Os dedos claros contrastam com as pernas escuras.", "Pode acompanhar outras garças em áreas de alimentação compartilhadas."], distribution: "Américas, do Canadá ao sul da América do Sul, incluindo o Brasil.", ecologicalImportance: "Integra as teias alimentares de áreas úmidas e ajuda a regular pequenos animais aquáticos.", images: [image("https://commons.wikimedia.org/wiki/Special:FilePath/Egretta%20thula%20at%20Las%20Gallinas%20Wildlife%20Ponds.jpg", "Frank Schulenburg", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Egretta_thula_at_Las_Gallinas_Wildlife_Ponds.jpg", "Frank Schulenburg / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Snowy%20egret%20(72749).jpg", "Rhododendrites", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Snowy_egret_(72749).jpg", "Rhododendrites / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Snowy%20egret%20in%20JBWR%20(30217).jpg", "Rhododendrites", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Snowy_egret_in_JBWR_(30217).jpg", "Rhododendrites / Wikimedia Commons")], sources: [gbif("Egretta thula")] },
    { id: "pitangus-sulphuratus", commonName: "Bem-te-vi", scientificName: "Pitangus sulphuratus", group: "Aves", environments: ["Campos", "Bordas de mata", "Áreas alagadas"], description: "Ave generalista de áreas abertas, reconhecida pela vocalização forte e pelo uso de diversos ambientes.", physicalCharacteristics: "Cabeça com faixa escura nos olhos, garganta branca, dorso pardo e ventre amarelo.", habitat: "Campos, bordas, parques, áreas agrícolas, margens de rios e ambientes urbanos.", behavior: "Defende território, captura presas em voos curtos e também procura alimento no solo e em poleiros.", diet: "Insetos, frutos, pequenos peixes, anfíbios e outros pequenos animais.", curiosities: ["A vocalização onomatopaica originou o nome popular.", "A flexibilidade alimentar favorece a ocupação de paisagens modificadas."], distribution: "Ampla distribuição desde o sul dos Estados Unidos até a Argentina, incluindo todo o Brasil.", ecologicalImportance: "Controla invertebrados e dispersa sementes, conectando ambientes naturais e áreas abertas.", images: [image("https://commons.wikimedia.org/wiki/Special:FilePath/Great%20kiskadee%20(70240).jpg", "Rhododendrites", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Great_kiskadee_(70240).jpg", "Rhododendrites / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Great%20kiskadee%20(Pitangus%20sulphuratus),%20Costa%20Rica.jpg", "Hobbyfotowiki", "CC0", "https://commons.wikimedia.org/wiki/File:Great_kiskadee_(Pitangus_sulphuratus),_Costa_Rica.jpg", "Hobbyfotowiki / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Great%20kiskadee%20(Pitangus%20sulphuratus%20guatimalensis)%20Panama.jpg", "Charles J. Sharp", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Great_kiskadee_(Pitangus_sulphuratus_guatimalensis)_Panama.jpg", "Charles J. Sharp / Wikimedia Commons")], sources: [gbif("Pitangus sulphuratus")] },
    { id: "sicalis-flaveola", commonName: "Canário-da-terra-verdadeiro", scientificName: "Sicalis flaveola", group: "Aves", environments: ["Campos", "Bordas de mata"], description: "Passeriforme de áreas abertas que se alimenta no solo e utiliza vegetação baixa para abrigo e reprodução.", physicalCharacteristics: "Plumagem predominantemente amarela nos machos, com dorso oliváceo ou pardo e variação entre sexos e idades.", habitat: "Campos, savanas, pastagens, bordas e áreas abertas próximas a ocupações humanas.", behavior: "Forma pares ou pequenos grupos, forrageia no chão e canta a partir de poleiros expostos.", diet: "Sementes, grãos e pequenos invertebrados, sobretudo durante a alimentação dos filhotes.", curiosities: ["O canto territorial é uma característica marcante dos machos.", "A espécie é frequentemente observada em áreas abertas com gramíneas e arbustos."], distribution: "América do Sul, com ampla ocorrência no Brasil e países vizinhos.", ecologicalImportance: "Participa do transporte de sementes e do controle de pequenos invertebrados em campos e bordas.", images: [image("https://commons.wikimedia.org/wiki/Special:FilePath/Saffron%20finch%20(Sicalis%20flaveola)%20male.JPG", "Charles J. Sharp", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Saffron_finch_(Sicalis_flaveola)_male.JPG", "Charles J. Sharp / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Saffron%20finch%20(Sicalis%20flaveola)%20male%20juvenile.JPG", "Charles J. Sharp", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Saffron_finch_(Sicalis_flaveola)_male_juvenile.JPG", "Charles J. Sharp / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Saffron%20finch%20(Sicalis%20flaveola%20flaveola)%20Cundinamarca.jpg", "Charles J. Sharp", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Saffron_finch_(Sicalis_flaveola_flaveola)_Cundinamarca.jpg", "Charles J. Sharp / Wikimedia Commons")], sources: [gbif("Sicalis flaveola")] },
  ],
};
