import type { CatalogBatch } from "../types";

const image = (uri: string, author: string, license: string, sourceUrl: string, credit: string) => ({ uri, author, license, sourceUrl, credit });
const gbif = (name: string) => ({ title: `GBIF Species Match — ${name}`, url: `https://api.gbif.org/v1/species/match?name=${encodeURIComponent(name)}` });

export const birds04: CatalogBatch = {
  batchId: "catalog-birds-04", cycle: 6, group: "Aves", status: "pending-review",
  sources: [gbif("Syrigma sibilatrix"), gbif("Megaceryle torquata"), gbif("Ardea alba")],
  pendingNotes: ["Confirmar ocorrência no recorte do Pantanal e eventual conservação em fonte ICMBio/MMA; imagens não substituem ocorrência regional."],
  species: [
    {
      id: "syrigma-sibilatrix", commonName: "Maria-faceira", scientificName: "Syrigma sibilatrix", group: "Aves", environments: ["Áreas alagadas", "Campos", "Bordas de mata"],
      description: "Garça de porte médio que explora áreas abertas e úmidas, caminhando em busca de pequenos animais entre a vegetação baixa.", physicalCharacteristics: "Plumagem cinza-azulada, face amarelada, bico escuro e pernas relativamente longas.", habitat: "Campos úmidos, bordas de lagoas, banhados, pastagens e margens de cursos d’água.", behavior: "Forrageia principalmente durante o dia, deslocando-se lentamente e realizando voos curtos entre áreas de alimentação e repouso.", diet: "Insetos, pequenos peixes, anfíbios, crustáceos e outros pequenos animais capturados no solo ou em água rasa.", curiosities: ["A vocalização contribui para o nome popular maria-faceira em várias regiões.", "A espécie combina áreas alagadas e campos, tolerando paisagens abertas quando há alimento e abrigo."], distribution: "América do Sul, incluindo grande parte do Brasil e países vizinhos.", ecologicalImportance: "Ajuda a controlar invertebrados e pequenos vertebrados e indica a disponibilidade de presas em áreas úmidas e campestres.",
      images: [image("https://commons.wikimedia.org/wiki/Special:FilePath/Syrigma%20sibilatrix%20-Punta%20del%20Este,%20Uruguay-8.jpg", "Jimmy Baikovicius", "CC BY-SA 2.0", "https://commons.wikimedia.org/wiki/File:Syrigma_sibilatrix_-Punta_del_Este,_Uruguay-8.jpg", "Jimmy Baikovicius / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Syrigma%20sibilatrix%20-%20rodrigo%20lazaro%20-%20343774749.jpeg", "rodrigo_lazaro", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Syrigma_sibilatrix_-_rodrigo_lazaro_-_343774749.jpeg", "rodrigo_lazaro / iNaturalist / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Whistling%20heron%20(Syrigma%20sibilatrix).JPG", "Charles J. Sharp", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Whistling_heron_(Syrigma_sibilatrix).JPG", "Charles J. Sharp / Wikimedia Commons")], sources: [gbif("Syrigma sibilatrix")],
    },
    {
      id: "megaceryle-torquata", commonName: "Martim-pescador-grande", scientificName: "Megaceryle torquata", group: "Aves", environments: ["Rios e corixos", "Áreas alagadas"],
      description: "Martim-pescador robusto que usa poleiros próximos à água para localizar e capturar presas por mergulho.", physicalCharacteristics: "Cabeça grande, bico longo, dorso azul-acinzentado e peito ferrugíneo, com diferenças de plumagem entre os sexos.", habitat: "Rios, corixos, lagoas e represas com água aberta e galhos ou estruturas para observação.", behavior: "Permanece imóvel em um poleiro e mergulha rapidamente quando identifica um peixe ou outra presa aquática.", diet: "Principalmente peixes, além de crustáceos, insetos e pequenos vertebrados aquáticos.", curiosities: ["Pode escavar o ninho em barrancos próximos à água.", "O mergulho é precedido por observação cuidadosa a partir de um poleiro elevado."], distribution: "Américas, do sul dos Estados Unidos à Argentina, com ocorrência ampla no Brasil.", ecologicalImportance: "É predador de ambientes aquáticos e transporta energia entre a comunidade de peixes e a cadeia alimentar terrestre.",
      images: [image("https://commons.wikimedia.org/wiki/Special:FilePath/003%20Ringed%20kingfisher%20flying%20with%20a%20fish%20in%20Encontro%20das%20%C3%81guas%20State%20Park%20Photo%20by%20Giles%20Laurent.jpg", "Giles Laurent", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:003_Ringed_kingfisher_flying_with_a_fish_in_Encontro_das_Águas_State_Park_Photo_by_Giles_Laurent.jpg", "Giles Laurent / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Ringed%20Kingfisher,%20Rio%20Sarar%C3%A9,%20Mato%20Grosso,%20Brazil.jpg", "Andreas Trepte", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Ringed_Kingfisher,_Rio_Sararé,_Mato_Grosso,_Brazil.jpg", "Andreas Trepte / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Ringed%20kingfisher%20(Megaceryle%20torquata)%20male%20in%20flight%20Rio%20Napo.jpg", "Charles J. Sharp", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Ringed_kingfisher_(Megaceryle_torquata)_male_in_flight_Rio_Napo.jpg", "Charles J. Sharp / Wikimedia Commons")], sources: [gbif("Megaceryle torquata")],
    },
    {
      id: "ardea-alba", commonName: "Garça-branca-grande", scientificName: "Ardea alba", group: "Aves", environments: ["Áreas alagadas", "Rios e corixos"],
      description: "Garça de grande porte que percorre águas rasas e margens em busca de peixes e outros animais pequenos.", physicalCharacteristics: "Plumagem branca, pescoço e pernas longos e bico comprido, geralmente amarelado fora do período reprodutivo.", habitat: "Lagoas, rios, corixos, banhados, estuários e outras áreas com água rasa e margem aberta.", behavior: "Caminha lentamente ou permanece imóvel antes de desferir um golpe rápido com o pescoço para capturar a presa.", diet: "Peixes, anfíbios, crustáceos, insetos, répteis pequenos e outros animais aquáticos ou terrestres.", curiosities: ["A postura imóvel reduz o movimento percebido pelas presas.", "Colônias reprodutivas podem reunir várias espécies de aves aquáticas quando há árvores adequadas."], distribution: "Distribuição ampla em áreas temperadas e tropicais das Américas, África, Europa, Ásia e Oceania.", ecologicalImportance: "Integra as teias alimentares de áreas úmidas e responde à disponibilidade de peixes e invertebrados em águas rasas.",
      images: [image("https://commons.wikimedia.org/wiki/Special:FilePath/012%20Great%20egret%20fishing%20during%20a%20foggy%20day%20at%20Champ-Pittet%20Photo%20by%20Giles%20Laurent.jpg", "Giles Laurent", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:012_Great_egret_fishing_during_a_foggy_day_at_Champ-Pittet_Photo_by_Giles_Laurent.jpg", "Giles Laurent / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Ardea%20alba4.jpg", "Calibas", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Ardea_alba4.jpg", "Calibas / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Ardea%20alba;%203%20chicks,%20Morro%20Bay%20Heron%20Rookery%202%20-%20by%20Mike%20Baird.jpg", "Mike Baird", "CC BY 2.0", "https://commons.wikimedia.org/wiki/File:Ardea_alba;_3_chicks,_Morro_Bay_Heron_Rookery_2_-_by_Mike_Baird.jpg", "Mike Baird / Wikimedia Commons")], sources: [gbif("Ardea alba")],
    },
  ],
};
