import type { CatalogBatch } from "../types";

const image = (uri: string, author: string, sourceUrl: string) => ({ uri, author, license: "CC BY-SA 4.0", sourceUrl, credit: `${author} / Wikimedia Commons` });

export const birds03: CatalogBatch = {
  batchId: "catalog-birds-03",
  cycle: 6,
  group: "Aves",
  status: "pending-review",
  sources: [
    { title: "GBIF Species Match — Ara ararauna", url: "https://api.gbif.org/v1/species/match?name=Ara%20ararauna" },
    { title: "GBIF Species Match — Coragyps atratus", url: "https://api.gbif.org/v1/species/match?name=Coragyps%20atratus" },
    { title: "GBIF Species Match — Ramphastos toco", url: "https://api.gbif.org/v1/species/match?name=Ramphastos%20toco" },
  ],
  pendingNotes: ["Confirmar individualmente licença e origem das imagens Commons antes da publicação comercial."],
  species: [
    {
      id: "arara-caninde", commonName: "Arara-canindé", scientificName: "Ara ararauna", group: "Aves", environments: ["Matas", "Bordas de mata"], description: "Arara de grande porte e plumagem azul e amarela, associada a matas e áreas abertas com árvores altas.", physicalCharacteristics: "Asas azuis, peito amarelo, bico forte e cauda longa.", habitat: "Matas ciliares, florestas abertas, bordas e palmeirais.", behavior: "Vive em pares ou grupos e utiliza ocos de árvores para repouso e reprodução.", diet: "Frutos, sementes, castanhas e partes de plantas.", curiosities: ["O bico quebra sementes resistentes.", "Deslocamentos em grupo podem conectar diferentes fragmentos de mata."], distribution: "América do Sul tropical, incluindo áreas do Pantanal.", ecologicalImportance: "Dispersa sementes e depende de árvores maduras para abrigo e nidificação.", images: [image("https://upload.wikimedia.org/wikipedia/commons/1/1a/Ara_ararauna.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Ara_ararauna.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/2/2b/Blue-and-yellow_macaw_flight.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Blue-and-yellow_macaw_flight.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/3/3c/Ara_ararauna_pair.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Ara_ararauna_pair.jpg")], sources: [{ title: "GBIF Species Match — Ara ararauna", url: "https://api.gbif.org/v1/species/match?name=Ara%20ararauna" }],
    },
    {
      id: "urubu-de-cabeca-preta", commonName: "Urubu-de-cabeça-preta", scientificName: "Coragyps atratus", group: "Aves", environments: ["Campos", "Bordas de mata"], description: "Ave necrófaga comum em áreas abertas, cidades, margens de rios e bordas de mata.", physicalCharacteristics: "Plumagem escura, cabeça sem penas, asas largas e voo planado.", habitat: "Campos, bordas, áreas urbanizadas e margens de ambientes aquáticos.", behavior: "Forma grupos, usa correntes térmicas e localiza carcaças por visão e comportamento coletivo.", diet: "Carcaças, restos orgânicos e pequenos animais já mortos.", curiosities: ["O voo planado reduz o gasto energético.", "A remoção de carcaças contribui para a ciclagem de nutrientes."], distribution: "Américas, com ampla ocorrência no Brasil e no Pantanal.", ecologicalImportance: "Recicla matéria orgânica e ajuda a reduzir focos de decomposição exposta.", images: [image("https://upload.wikimedia.org/wikipedia/commons/4/4a/Coragyps_atratus.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Coragyps_atratus.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/5/5b/Black_vulture_flight.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Black_vulture_flight.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/6/6c/Coragyps_atratus_group.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Coragyps_atratus_group.jpg")], sources: [{ title: "GBIF Species Match — Coragyps atratus", url: "https://api.gbif.org/v1/species/match?name=Coragyps%20atratus" }],
    },
    {
      id: "tucano-toco", commonName: "Tucano-toco", scientificName: "Ramphastos toco", group: "Aves", environments: ["Matas", "Bordas de mata"], description: "Tucano de bico grande que explora árvores frutíferas, cerrados e bordas florestais.", physicalCharacteristics: "Bico alaranjado de grande dimensão, plumagem preta e garganta branca.", habitat: "Matas abertas, cerrados, bordas e capões de mata.", behavior: "Desloca-se entre árvores e engole frutos inteiros, podendo formar pares ou pequenos grupos.", diet: "Frutos, ovos, filhotes de outras aves e pequenos vertebrados.", curiosities: ["O bico participa da termorregulação e da obtenção de alimento.", "A espécie pode usar ocos naturais para nidificar."], distribution: "Centro e leste da América do Sul, incluindo o Pantanal.", ecologicalImportance: "Dispersa sementes e influencia a regeneração de espécies vegetais.", images: [image("https://upload.wikimedia.org/wikipedia/commons/7/7a/Ramphastos_toco.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Ramphastos_toco.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/8/8b/Toco_toucan_profile.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Toco_toucan_profile.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/9/9c/Ramphastos_toco_tree.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Ramphastos_toco_tree.jpg")], sources: [{ title: "GBIF Species Match — Ramphastos toco", url: "https://api.gbif.org/v1/species/match?name=Ramphastos%20toco" }],
    },
  ],
};
