import type { CatalogBatch } from "../types";
const image = (uri: string, author: string, license: string, sourceUrl: string, credit: string) => ({ uri, author, license, sourceUrl, credit });
const gbif = (name: string) => ({ title: `GBIF Species Match — ${name}`, url: `https://api.gbif.org/v1/species/match?name=${encodeURIComponent(name)}` });
export const fish01: CatalogBatch = {
  batchId: "catalog-fish-01", cycle: 9, group: "Peixes", status: "pending-review",
  sources: [gbif("Pseudoplatystoma corruscans"), gbif("Piaractus mesopotamicus"), gbif("Salminus brasiliensis")],
  pendingNotes: ["Confirmar ocorrência no recorte do Pantanal e consultar Livro Vermelho ICMBio/portarias MMA antes de preencher conservação."],
  species: [
    { id: "pseudoplatystoma-corruscans", commonName: "Pintado", scientificName: "Pseudoplatystoma corruscans", group: "Peixes", environments: ["Rios e corixos"], description: "Peixe de água doce de grande porte, associado a rios e canais de planícies alagáveis.", physicalCharacteristics: "Corpo alongado, cabeça achatada, barbilhões e manchas escuras sobre a coloração clara.", habitat: "Rios, canais e áreas de correnteza ou conexão durante os ciclos de cheia e vazante.", behavior: "Predador ativo que utiliza a coluna d’água e o fundo para localizar presas.", diet: "Peixes e outros animais aquáticos de tamanho compatível.", curiosities: ["Os barbilhões auxiliam na percepção do ambiente.", "A espécie é conhecida por seu porte e importância na pesca regional."], distribution: "Bacias sul-americanas, incluindo a bacia do Paraguai e outros sistemas brasileiros.", ecologicalImportance: "Atua como predador de topo e participa da regulação das comunidades de peixes.", images: [image("https://upload.wikimedia.org/wikipedia/commons/3/39/Spotted_sorubim_%E2%80%9CPseudoplatystoma_corruscans%E2%80%9D_at_MAV-USP.jpg", "Museum of Veterinary Anatomy FMVZ USP / Wagner Souza e Silva", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Spotted_sorubim_%E2%80%9CPseudoplatystoma_corruscans%E2%80%9D_at_MAV-USP.jpg", "MAV-USP / Wikimedia Commons"), image("https://upload.wikimedia.org/wikipedia/commons/a/ae/Pseudoplatystoma_corruscans_484849557.jpg", "Rocío Esmeralda Pose", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Pseudoplatystoma_corruscans_484849557.jpg", "Rocío Esmeralda Pose / Wikimedia Commons"), image("https://upload.wikimedia.org/wikipedia/commons/d/d7/Surub%C3%AD_%28Pseudoplatystoma_corruscans%29%2C_It%C3%A1_Ibat%C3%A9.jpg", "Martín Acosta Albarracín", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Surubí_(Pseudoplatystoma_corruscans),_Itá_Ibaté.jpg", "Martín Acosta Albarracín / Wikimedia Commons")], sources: [gbif("Pseudoplatystoma corruscans")] },
    { id: "piaractus-mesopotamicus", commonName: "Pacu", scientificName: "Piaractus mesopotamicus", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"], description: "Peixe de água doce de corpo alto, ligado a rios, baías e áreas alagáveis.", physicalCharacteristics: "Corpo comprimido e alto, dentição forte e coloração que varia entre tons prateados e escuros.", habitat: "Rios, lagoas marginais, baías e áreas conectadas durante a cheia.", behavior: "Desloca-se em busca de alimento e utiliza ambientes inundados para alimentação e abrigo.", diet: "Frutos, sementes, plantas e pequenos animais disponíveis no ambiente aquático.", curiosities: ["A dentição permite processar itens vegetais resistentes.", "A cheia amplia o acesso a frutos e sementes terrestres."], distribution: "Bacias do Paraguai e Paraná e outras regiões da América do Sul.", ecologicalImportance: "Contribui para o transporte de sementes e a ligação energética entre áreas terrestres inundadas e rios.", images: [image("https://upload.wikimedia.org/wikipedia/commons/3/33/Piaractus_mesopotamicus_-_Flickr_-_Dick_Culbert.jpg", "Dick Culbert", "CC BY 2.0", "https://commons.wikimedia.org/wiki/File:Piaractus_mesopotamicus_-_Flickr_-_Dick_Culbert.jpg", "Dick Culbert / Wikimedia Commons"), image("https://upload.wikimedia.org/wikipedia/commons/4/47/Piaractus_mesopotamicus_387099634.jpg", "R Vasconcellos", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Piaractus_mesopotamicus_387099634.jpg", "R Vasconcellos / Wikimedia Commons"), image("https://upload.wikimedia.org/wikipedia/commons/2/2e/Piaractus_mesopotamicus_307099193.jpg", "Nicolas Olejnik", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Piaractus_mesopotamicus_307099193.jpg", "Nicolas Olejnik / Wikimedia Commons")], sources: [gbif("Piaractus mesopotamicus")] },
    { id: "salminus-brasiliensis", commonName: "Dourado", scientificName: "Salminus brasiliensis", group: "Peixes", environments: ["Rios e corixos"], description: "Peixe predador de água doce associado a rios com correnteza e conectividade aquática.", physicalCharacteristics: "Corpo alongado, coloração dourada e nadadeiras com tons amarelados ou alaranjados.", habitat: "Rios, corredeiras e canais conectados em bacias sul-americanas.", behavior: "Nada ativamente e caça peixes, especialmente em trechos com correnteza e abrigo.", diet: "Peixes e outros organismos aquáticos capturados durante a atividade predatória.", curiosities: ["A coloração dourada inspira o nome popular.", "A conectividade dos rios é importante para seus deslocamentos."], distribution: "Bacias do Paraguai, Paraná e outros sistemas da América do Sul.", ecologicalImportance: "Predador de água doce que ajuda a estruturar comunidades de peixes.", images: [image("https://upload.wikimedia.org/wikipedia/commons/1/1a/Dourado%28Salminus_brasiliensis%29emBonito.jpg", "David Morimoto", "CC BY-SA 2.0", "https://commons.wikimedia.org/wiki/File:Dourado(Salminus_brasiliensis)emBonito.jpg", "David Morimoto / Wikimedia Commons"), image("https://upload.wikimedia.org/wikipedia/commons/e/ec/Salminus_brasiliensis_61505781.jpg", "Walter S. Prado", "CC0", "https://commons.wikimedia.org/wiki/File:Salminus_brasiliensis_61505781.jpg", "Walter S. Prado / Wikimedia Commons"), image("https://upload.wikimedia.org/wikipedia/commons/a/a8/Salminus_brasiliensis_167978745.jpg", "Pablo H Capovilla", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Salminus_brasiliensis_167978745.jpg", "Pablo H Capovilla / Wikimedia Commons")], sources: [gbif("Salminus brasiliensis")] },
  ],
};
