import type { CatalogBatch } from "../types";

const image = (uri: string, author: string, license: string, sourceUrl: string, credit: string) => ({ uri, author, license, sourceUrl, credit });
const gbif = (name: string) => ({ title: `GBIF Species Match — ${name}`, url: `https://api.gbif.org/v1/species/match?name=${encodeURIComponent(name)}` });

export const fish05: CatalogBatch = {
  batchId: "catalog-fish-05", cycle: 11, group: "Peixes", status: "pending-review",
  sources: [gbif("Pseudoplatystoma reticulatum"), gbif("Cichla piquiti"), gbif("Piaractus brachypomus")],
  pendingNotes: ["Confirmar ocorrência no recorte do Pantanal e eventual conservação em fonte ICMBio/MMA; imagens não substituem ocorrência regional."],
  species: [
    {
      id: "pseudoplatystoma-reticulatum", commonName: "Cachara", scientificName: "Pseudoplatystoma reticulatum", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
      description: "Bagre de grande porte com padrão reticulado, associado a rios e ambientes de planície de inundação.", physicalCharacteristics: "Corpo alongado, cabeça achatada, barbilhões sensoriais e faixas ou manchas escuras formando desenho reticulado.", habitat: "Rios, canais, lagoas marginais e áreas alagadas conectadas durante o pulso de inundação.", behavior: "Explora a coluna d’água e o fundo, usando áreas de abrigo e maior disponibilidade de presas ao longo do ciclo hidrológico.", diet: "Peixes e outros animais aquáticos capturados por emboscada.", curiosities: ["Os barbilhões ajudam a localizar presas em águas turvas.", "O desenho do corpo auxilia a reconhecer o grupo de grandes bagres sul-americanos."], distribution: "Bacias sul-americanas, incluindo a bacia do Paraguai e outros sistemas brasileiros.", ecologicalImportance: "É predador de topo relativo em rios e transfere energia entre peixes de menor porte e consumidores maiores.",
      images: [image("https://commons.wikimedia.org/wiki/Special:FilePath/Fish%20fauna%20from%20R%C3%ADo%20Pilcomayo%20National%20Park%20(4%20of%207).png", "Florencia Brancolini, Priscilla Minotti, Lucila Protogino, Hugo López e Claudio Baigún", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Fish_fauna_from_Río_Pilcomayo_National_Park_(4_of_7).png", "Brancolini et al. / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Pescadorpintado.jpg", "Tomcather e Klaus", "Public domain", "https://commons.wikimedia.org/wiki/File:Pescadorpintado.jpg", "Tomcather e Klaus / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Pseudoplatystoma%20reticulatum.JPG", "CHUCAO", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Pseudoplatystoma_reticulatum.JPG", "CHUCAO / Wikimedia Commons")], sources: [gbif("Pseudoplatystoma reticulatum")],
    },
    {
      id: "cichla-piquiti", commonName: "Tucunaré-azul", scientificName: "Cichla piquiti", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
      description: "Ciclídeo predador de água doce que ocupa áreas com estrutura submersa e água relativamente calma.", physicalCharacteristics: "Corpo alto, boca ampla e coloração variável com barras ou manchas escuras sobre fundo azulado ou esverdeado.", habitat: "Rios, reservatórios, lagoas e margens com galhos, pedras ou vegetação submersa.", behavior: "Defende áreas de reprodução e caça peixes e outros animais em ataques rápidos próximos a estruturas.", diet: "Principalmente peixes, além de crustáceos e outros organismos aquáticos.", curiosities: ["A coloração pode mudar conforme idade, ambiente e estado comportamental.", "O cuidado parental pode incluir defesa de ovos e juvenis em algumas espécies do gênero."], distribution: "Bacias brasileiras, especialmente sistemas associados às regiões central e sudeste; ocorrência pantaneira requer confirmação regional.", ecologicalImportance: "Regula populações de pequenos peixes e altera o fluxo de energia em comunidades aquáticas.",
      images: [image("https://commons.wikimedia.org/wiki/Special:FilePath/Cichla%20piquiti%2029769333.jpg", "Douglas", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Cichla_piquiti_29769333.jpg", "Douglas / iNaturalist / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Cichla%20piquiti%2029769333%20(cropped).jpg", "Douglas", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Cichla_piquiti_29769333_(cropped).jpg", "Douglas / iNaturalist / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Cichla%20piquiti%20from%20the%20Lajeado%20reservoir%20(2%20of%202)%20(cropped).png", "Renata Bartolette, Carolina Santos Vieira e colaboradores", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Cichla_piquiti_from_the_Lajeado_reservoir_(2_of_2)_(cropped).png", "Bartolette et al. / Wikimedia Commons")], sources: [gbif("Cichla piquiti")],
    },
    {
      id: "piaractus-brachypomus", commonName: "Pirapitinga", scientificName: "Piaractus brachypomus", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
      description: "Peixe de corpo alto que utiliza rios e áreas inundáveis e combina recursos vegetais e animais na alimentação.", physicalCharacteristics: "Corpo comprimido e alto, mandíbula robusta e coloração que pode apresentar tons prateados, avermelhados ou escuros.", habitat: "Rios, lagoas marginais e florestas alagáveis com frutos, sementes e abrigo disponíveis.", behavior: "Desloca-se em busca de alimento e pode aproveitar recursos que caem da vegetação sobre a água.", diet: "Frutos, sementes, material vegetal e invertebrados aquáticos, com variação conforme a disponibilidade.", curiosities: ["A dentição robusta auxilia no processamento de frutos e sementes.", "A conexão entre floresta alagável e rio amplia a oferta alimentar durante a cheia."], distribution: "Bacias da América do Sul, especialmente ao norte e oeste do continente; ocorrência pantaneira permanece pendente.", ecologicalImportance: "Participa da dispersão e do processamento de sementes e conecta a produção da vegetação ripária às teias aquáticas.",
      images: [image("https://commons.wikimedia.org/wiki/Special:FilePath/Piaractus%20brachypomus%20-%20squelette%20mnhn%20Paris.JPG", "Cedricguppy - Loury Cédric", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Piaractus_brachypomus_-_squelette_mnhn_Paris.JPG", "Cedricguppy / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Piaractus%20brachypomus%20in%20Minsk%20Zoo.JPG", "Хомелка", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Piaractus_brachypomus_in_Minsk_Zoo.JPG", "Хомелка / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Piaractus%20brachypomus%20in%20Minsk%20Zoo%2001.JPG", "Mahufi", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Piaractus_brachypomus_in_Minsk_Zoo_01.JPG", "Mahufi / Wikimedia Commons")], sources: [gbif("Piaractus brachypomus")],
    },
  ],
};
