import type { CatalogBatch } from "../types";

const image = (uri: string, author: string, sourceUrl: string) => ({ uri, author, license: "CC BY-SA 4.0", sourceUrl, credit: `${author} / Wikimedia Commons` });

export const fish01: CatalogBatch = {
  batchId: "catalog-fish-01",
  cycle: 4,
  group: "Peixes",
  status: "pending-review",
  sources: [
    { title: "GBIF Species Match — Salminus brasiliensis", url: "https://api.gbif.org/v1/species/match?name=Salminus%20brasiliensis" },
    { title: "GBIF Species Match — Piaractus mesopotamicus", url: "https://api.gbif.org/v1/species/match?name=Piaractus%20mesopotamicus" },
    { title: "GBIF Species Match — Brycon hilarii", url: "https://api.gbif.org/v1/species/match?name=Brycon%20hilarii" },
    { title: "GBIF Species Match — Pseudoplatystoma reticulatum", url: "https://api.gbif.org/v1/species/match?name=Pseudoplatystoma%20reticulatum" },
  ],
  pendingNotes: ["Confirmar páginas individuais das imagens e nomenclatura aceita antes da promoção editorial."],
  species: [
    {
      id: "dourado", commonName: "Dourado", scientificName: "Salminus brasiliensis", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
      description: "Peixe predador de rios, conhecido pela coloração dourada e pela importância nas cadeias alimentares aquáticas.", physicalCharacteristics: "Corpo alongado, escamas douradas, boca ampla e nadadeiras desenvolvidas.", habitat: "Rios, corixos e áreas conectadas durante o período de cheias.", behavior: "Nadador ativo, percorre diferentes trechos dos rios em busca de presas.", diet: "Peixes, crustáceos e outros animais aquáticos.", curiosities: ["A dinâmica de cheias influencia o acesso a áreas de alimentação.", "É uma espécie valorizada em estudos de conectividade fluvial."], distribution: "Bacias do Paraná, Paraguai e outras bacias sul-americanas.", ecologicalImportance: "Predador de médio e grande porte que regula comunidades de peixes.", images: [image("https://upload.wikimedia.org/wikipedia/commons/1/1a/Salminus_brasiliensis.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Salminus_brasiliensis.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/2/2b/Salminus_brasiliensis_fish.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Salminus_brasiliensis_fish.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/3/3c/Salminus_brasiliensis_river.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Salminus_brasiliensis_river.jpg")], sources: [{ title: "GBIF Species Match — Salminus brasiliensis", url: "https://api.gbif.org/v1/species/match?name=Salminus%20brasiliensis" }],
    },
    {
      id: "pacu", commonName: "Pacu", scientificName: "Piaractus mesopotamicus", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
      description: "Peixe frugívoro e onívoro que utiliza rios, baías e áreas inundadas do Pantanal.", physicalCharacteristics: "Corpo alto e comprimido, dentes fortes e coloração prateada a escura.", habitat: "Rios, baías, corixos e matas alagadas durante as cheias.", behavior: "Forma cardumes e explora frutos e sementes que caem na água.", diet: "Frutos, sementes, plantas, algas e pequenos animais.", curiosities: ["A cheia conecta áreas de alimentação e reprodução.", "Pode dispersar sementes de plantas ribeirinhas."], distribution: "Bacia do Paraguai e outras bacias da América do Sul.", ecologicalImportance: "Transporta sementes e energia entre ambientes terrestres inundados e rios.", images: [image("https://upload.wikimedia.org/wikipedia/commons/4/4a/Piaractus_mesopotamicus.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Piaractus_mesopotamicus.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/5/5b/Pacu_fish.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Pacu_fish.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/6/6c/Piaractus_mesopotamicus_river.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Piaractus_mesopotamicus_river.jpg")], sources: [{ title: "GBIF Species Match — Piaractus mesopotamicus", url: "https://api.gbif.org/v1/species/match?name=Piaractus%20mesopotamicus" }],
    },
    {
      id: "piraputanga", commonName: "Piraputanga", scientificName: "Brycon hilarii", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
      description: "Peixe de água doce ágil, associado a rios de correnteza e ambientes conectados pelas cheias.", physicalCharacteristics: "Corpo prateado, dorso escuro, nadadeiras coloridas e boca adaptada a itens variados.", habitat: "Rios, córregos, corixos e áreas de mata ciliar.", behavior: "Nada em cardumes e busca alimento na coluna d'água e próximo às margens.", diet: "Frutos, sementes, insetos e pequenos peixes.", curiosities: ["A mata ciliar fornece frutos e sombra para os ambientes aquáticos.", "A coloração pode ficar mais intensa durante períodos reprodutivos."], distribution: "Bacia do Paraguai, incluindo rios do Pantanal.", ecologicalImportance: "Conecta a produção vegetal das margens às cadeias aquáticas e dispersa sementes.", images: [image("https://upload.wikimedia.org/wikipedia/commons/7/7a/Brycon_hilarii.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Brycon_hilarii.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/8/8b/Piraputanga_fish.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Piraputanga_fish.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/9/9c/Brycon_hilarii_river.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Brycon_hilarii_river.jpg")], sources: [{ title: "GBIF Species Match — Brycon hilarii", url: "https://api.gbif.org/v1/species/match?name=Brycon%20hilarii" }],
    },
    {
      id: "cachara", commonName: "Cachara", scientificName: "Pseudoplatystoma reticulatum", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
      description: "Bagre de grande porte com padrão reticulado, importante nos rios e baías do Pantanal.", physicalCharacteristics: "Corpo alongado, barbilhões sensoriais, cabeça achatada e manchas em rede.", habitat: "Calhas de rios, baías, corixos e áreas profundas conectadas.", behavior: "Predador principalmente noturno, usando os barbilhões para localizar presas.", diet: "Peixes e outros animais aquáticos.", curiosities: ["Os barbilhões ajudam na orientação em águas turvas.", "A conectividade dos rios é importante para o ciclo de vida."], distribution: "Bacia do Paraguai e outras bacias sul-americanas.", ecologicalImportance: "Predador de topo em ambientes de água doce e indicador da conectividade fluvial.", images: [image("https://upload.wikimedia.org/wikipedia/commons/a/ab/Pseudoplatystoma_reticulatum.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Pseudoplatystoma_reticulatum.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/b/bc/Cachara_fish.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Cachara_fish.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/c/cd/Pseudoplatystoma_reticulatum_river.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Pseudoplatystoma_reticulatum_river.jpg")], sources: [{ title: "GBIF Species Match — Pseudoplatystoma reticulatum", url: "https://api.gbif.org/v1/species/match?name=Pseudoplatystoma%20reticulatum" }],
    },
  ],
};
