import type { CatalogBatch } from "../types";

const image = (uri: string, author: string, license: string, sourceUrl: string, credit: string) => ({ uri, author, license, sourceUrl, credit });
const gbif = (name: string) => ({ title: `GBIF Species Match — ${name}`, url: `https://api.gbif.org/v1/species/match?name=${encodeURIComponent(name)}` });

export const fish04: CatalogBatch = {
  batchId: "catalog-fish-04",
  cycle: 11,
  group: "Peixes",
  status: "pending-review",
  sources: [gbif("Pimelodus maculatus"), gbif("Loricariichthys anus"), gbif("Corydoras paleatus")],
  pendingNotes: ["Confirmar ocorrência no recorte do Pantanal e eventual conservação em fonte ICMBio/MMA; imagens e match GBIF não substituem ocorrência regional."],
  species: [
    {
      id: "pimelodus-maculatus", commonName: "Mandi", scientificName: "Pimelodus maculatus", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
      description: "Peixe de água doce associado ao fundo de rios e lagoas, com barbilhões que auxiliam a exploração do ambiente.", physicalCharacteristics: "Corpo alongado, coloração amarelada ou prateada com manchas escuras e barbilhões ao redor da boca.", habitat: "Rios, remansos, lagoas marginais e trechos com substrato e abrigo disponíveis.", behavior: "Explora o fundo e as margens, usando os barbilhões para localizar alimento em águas turvas.", diet: "Invertebrados aquáticos, pequenos peixes, detritos e matéria orgânica do substrato.", curiosities: ["Os barbilhões funcionam como estruturas sensoriais.", "A atividade pode aumentar em períodos de menor luminosidade."], distribution: "Bacias de água doce da América do Sul, com ampla ocorrência em rios brasileiros.", ecologicalImportance: "Participa da reciclagem de matéria orgânica e integra a dieta de predadores aquáticos e ribeirinhos.",
      images: [image("https://upload.wikimedia.org/wikipedia/commons/c/ca/Pimelodus_maculatus.jpg", "Paul Louis Oudart", "Public domain", "https://commons.wikimedia.org/wiki/File:Pimelodus_maculatus.jpg", "Paul Louis Oudart / Wikimedia Commons"), image("https://upload.wikimedia.org/wikipedia/commons/0/0a/Mandi_%E2%80%93_Pimelodus_maculatus_%285257144069%29.jpg", "Secretaria de Agricultura e Abastecimento", "CC BY 2.0", "https://commons.wikimedia.org/wiki/File:Mandi_–_Pimelodus_maculatus_(5257144069).jpg", "Secretaria de Agricultura e Abastecimento / Wikimedia Commons"), image("https://upload.wikimedia.org/wikipedia/commons/7/7e/Pimelodus_maculatus_469641789.jpg", "Rocío Esmeralda Pose", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Pimelodus_maculatus_469641789.jpg", "Rocío Esmeralda Pose / iNaturalist / Wikimedia Commons")], sources: [gbif("Pimelodus maculatus")],
    },
    {
      id: "loricariichthys-anus", commonName: "Cascudo-chinelo", scientificName: "Loricariichthys anus", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
      description: "Peixe de fundo com corpo protegido por placas, encontrado em ambientes de água doce com vegetação e substrato variados.", physicalCharacteristics: "Corpo alongado revestido por placas ósseas, boca inferior e nadadeiras adaptadas ao deslocamento junto ao fundo.", habitat: "Rios, lagoas, remansos e margens com areia, lodo ou vegetação submersa.", behavior: "Permanece próximo ao substrato e procura alimento em períodos de atividade crepuscular ou noturna.", diet: "Algas, detritos, matéria vegetal e pequenos organismos associados ao fundo.", curiosities: ["As placas reduzem a vulnerabilidade a predadores.", "A boca voltada para baixo favorece a alimentação junto ao substrato."], distribution: "Bacias de água doce do sul e centro da América do Sul, incluindo sistemas brasileiros.", ecologicalImportance: "Recicla matéria orgânica do fundo e serve de alimento para predadores de ambientes aquáticos.",
      images: [image("https://upload.wikimedia.org/wikipedia/commons/9/9b/Loricariichthys_anus.jpg", "Cláudio Dias Timm", "CC BY-SA 2.0", "https://commons.wikimedia.org/wiki/File:Loricariichthys_anus.jpg", "Cláudio Dias Timm / Wikimedia Commons"), image("https://upload.wikimedia.org/wikipedia/commons/2/2d/Loricariichthys_anus_Orbigny.jpg", "Paul Louis Oudart", "Public domain", "https://commons.wikimedia.org/wiki/File:Loricariichthys_anus_Orbigny.jpg", "Paul Louis Oudart / Wikimedia Commons"), image("https://upload.wikimedia.org/wikipedia/commons/e/ed/Species_of_fishes_from_the_Chasqueiro_Stream_%28Mirim_Lagoon_system%29.jpg", "Fabiano Corrêa et al.", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Species_of_fishes_from_the_Chasqueiro_Stream_(Mirim_Lagoon_system).jpg", "Fabiano Corrêa et al. / Wikimedia Commons")], sources: [gbif("Loricariichthys anus")],
    },
    {
      id: "corydoras-paleatus", commonName: "Coridora-pintada", scientificName: "Corydoras paleatus", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
      description: "Pequeno peixe de fundo que vive em grupos e revolve o substrato em busca de partículas alimentares.", physicalCharacteristics: "Corpo curto com placas ósseas, barbilhões na boca e padrão de manchas ou faixas sobre fundo claro.", habitat: "Riachos, margens rasas, lagoas e trechos de baixa correnteza com substrato fino.", behavior: "Forrageia junto ao fundo, frequentemente em grupo, e sobe à superfície para engolir ar em algumas condições.", diet: "Pequenos invertebrados, larvas, detritos e partículas orgânicas do substrato.", curiosities: ["Os barbilhões ajudam a localizar alimento no fundo.", "A respiração aérea complementar pode auxiliar em águas pobres em oxigênio."], distribution: "Bacias do sul da América do Sul, com registros no Brasil, Uruguai e Argentina.", ecologicalImportance: "Contribui para a movimentação de sedimentos e integra as teias alimentares de pequenos cursos d’água.",
      images: [image("https://upload.wikimedia.org/wikipedia/commons/6/69/Corydoras_paleatus_by_NiKo.jpg", "NiKo", "Public domain", "https://commons.wikimedia.org/wiki/File:Corydoras_paleatus_by_NiKo.jpg", "NiKo / Wikimedia Commons"), image("https://upload.wikimedia.org/wikipedia/commons/d/db/Corydoras_paleatus_84869641.jpg", "Guillermo Debandi", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Corydoras_paleatus_84869641.jpg", "Guillermo Debandi / iNaturalist / Wikimedia Commons"), image("https://upload.wikimedia.org/wikipedia/commons/c/c5/Corydoras_paleatus_1.jpg", "Juan Carlos Palau Díaz", "CC BY 3.0", "https://commons.wikimedia.org/wiki/File:Corydoras_paleatus_1.jpg", "Juan Carlos Palau Díaz / Wikimedia Commons")], sources: [gbif("Corydoras paleatus")],
    },
  ],
};
