import type { CatalogBatch } from "../types";

const image = (uri: string, author: string, license: string, sourceUrl: string, credit: string) => ({ uri, author, license, sourceUrl, credit });
const gbif = (name: string) => ({ title: `GBIF Species Match — ${name}`, url: `https://api.gbif.org/v1/species/match?name=${encodeURIComponent(name)}` });

export const invertebrates06: CatalogBatch = {
  batchId: "catalog-invertebrates-06", cycle: 14, group: "Invertebrados", status: "pending-review",
  sources: [gbif("Heliconius erato"), gbif("Papilio thoas"), gbif("Bombus pauloensis")],
  pendingNotes: ["Confirmar ocorrência no recorte do Pantanal e eventual conservação em fonte ICMBio/MMA; imagens não substituem ocorrência regional."],
  species: [
    {
      id: "heliconius-erato", commonName: "Dançarina", scientificName: "Heliconius erato", group: "Invertebrados", environments: ["Matas", "Bordas de mata"], description: "Borboleta neotropical de voo diurno, associada a áreas florestais e plantas hospedeiras usadas pelas lagartas.", physicalCharacteristics: "Asas alongadas com faixas vermelhas, amarelas e escuras, em padrões que variam entre formas geográficas.", habitat: "Matas, clareiras, bordas e corredores com flores e maracujás silvestres.", behavior: "Voa durante o dia, visita flores e pode formar agrupamentos de repouso ao anoitecer.", diet: "Adultos visitam flores e frutos; lagartas usam espécies de Passiflora como plantas hospedeiras.", curiosities: ["A espécie participa de complexos de mimetismo entre borboletas de coloração semelhante.", "Adultos podem viver por mais tempo que muitas outras borboletas, favorecendo deslocamentos e reprodução."], distribution: "Américas Central e do Sul, incluindo diferentes regiões do Brasil.", ecologicalImportance: "Participa da polinização e integra cadeias alimentares florestais em fases larval e adulta.", images: [image("https://commons.wikimedia.org/wiki/Special:FilePath/Common%20longwing%20(Heliconius%20erato%20amazona).JPG", "Charles J. Sharp", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Common_longwing_(Heliconius_erato_amazona).JPG", "Charles J. Sharp / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Heliconius%20erato%20Richard%20Bartz.jpg", "Richard Bartz", "CC BY-SA 2.5", "https://commons.wikimedia.org/wiki/File:Heliconius_erato_Richard_Bartz.jpg", "Richard Bartz / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Heliconius%20erato%20petiveranus%20MHNT.jpg", "Didier Descouens", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Heliconius_erato_petiveranus_MHNT.jpg", "Didier Descouens / Wikimedia Commons")], sources: [gbif("Heliconius erato")],
    },
    {
      id: "papilio-thoas", commonName: "Borboleta-caixão-de-defunto", scientificName: "Papilio thoas", group: "Invertebrados", environments: ["Campos", "Bordas de mata"], description: "Borboleta de grande porte que usa ambientes abertos e bordas com plantas cítricas e outras hospedeiras.", physicalCharacteristics: "Asas escuras com manchas amarelas e caudas posteriores, com variação regional no desenho.", habitat: "Clareiras, campos, jardins e bordas florestais com néctar e plantas hospedeiras.", behavior: "Voa rapidamente durante o dia e visita flores, alternando patrulhamento de áreas com pousos breves.", diet: "Adultos alimentam-se de néctar; lagartas utilizam plantas da família Rutaceae.", curiosities: ["As caudas das asas posteriores podem desviar ataques para longe do corpo.", "O padrão amarelo e preto é conspícuo durante o voo e contrastante quando pousada."], distribution: "Américas, com ampla distribuição tropical e subtropical, inclusive no Brasil.", ecologicalImportance: "É polinizadora visitante e recurso alimentar para predadores de campos e bordas.", images: [image("https://commons.wikimedia.org/wiki/Special:FilePath/DSC%204112%20-%20Papilio%20thoas.JPG", "Tubifex", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:DSC_4112_-_Papilio_thoas.JPG", "Tubifex / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Papilio%20thoas%20thoas%20MHNT.jpg", "Didier Descouens", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Papilio_thoas_thoas_MHNT.jpg", "Didier Descouens / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Papilionidae%20Papilio%20thoas%201.jpg", "NasserHalaweh", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Papilionidae_Papilio_thoas_1.jpg", "NasserHalaweh / Wikimedia Commons")], sources: [gbif("Papilio thoas")],
    },
    {
      id: "bombus-pauloensis", commonName: "Mamangava-de-chão", scientificName: "Bombus pauloensis", group: "Invertebrados", environments: ["Campos", "Bordas de mata"], description: "Abelha social de grande porte que visita flores em áreas abertas e pode nidificar em cavidades protegidas.", physicalCharacteristics: "Corpo robusto e piloso, com faixas de coloração variável e estruturas adaptadas à coleta de pólen.", habitat: "Campos, bordas, áreas agrícolas e clareiras com flores e locais protegidos para o ninho.", behavior: "Visita muitas flores, transporta pólen nas corbículas e vive em colônias sazonais.", diet: "Adultos consomem néctar e coletam pólen para alimentar larvas e a colônia.", curiosities: ["A vibração dos músculos de voo ajuda algumas mamangavas a liberar pólen de anteras específicas.", "A colônia depende de recursos florais distribuídos na paisagem ao longo da estação."], distribution: "América do Sul, com registros no Brasil e países vizinhos.", ecologicalImportance: "É polinizadora importante de plantas nativas e cultivadas, contribuindo para a reprodução vegetal.", images: [image("https://commons.wikimedia.org/wiki/Special:FilePath/Bombus%20Atratus%20Map.jpg", "WikiMedia Commons", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Bombus_Atratus_Map.jpg", "WikiMedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Bombus%20atratus%20BYN.jpg", "Megustanlasframbuesas", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Bombus_atratus_BYN.jpg", "Megustanlasframbuesas / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Bombus%20pauloensis%20-%20Nayara%20-%20396750748.jpeg", "Nayara", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Bombus_pauloensis_-_Nayara_-_396750748.jpeg", "Nayara / iNaturalist / Wikimedia Commons")], sources: [gbif("Bombus pauloensis")],
    },
  ],
};
