import type { CatalogBatch } from "../types";

const image = (uri: string, author: string, license: string, sourceUrl: string, credit: string) => ({ uri, author, license, sourceUrl, credit });
const gbif = (name: string) => ({ title: `GBIF Species Match — ${name}`, url: `https://api.gbif.org/v1/species/match?name=${encodeURIComponent(name)}` });

export const invertebrates05: CatalogBatch = {
  batchId: "catalog-invertebrates-05",
  cycle: 14,
  group: "Invertebrados",
  status: "pending-review",
  sources: [gbif("Morpho menelaus"), gbif("Ascalapha odorata"), gbif("Dynastes hercules")],
  pendingNotes: ["Confirmar ocorrência no recorte do Pantanal e eventual conservação em fonte ICMBio/MMA; imagens licenciadas não provam ocorrência regional."],
  species: [
    {
      id: "morpho-menelaus", commonName: "Borboleta-azul-menelaus", scientificName: "Morpho menelaus", group: "Invertebrados", environments: ["Matas", "Bordas de mata"],
      description: "Borboleta neotropical de asas amplas, associada a ambientes florestais e clareiras onde adultos e larvas encontram recursos distintos.", physicalCharacteristics: "Asas grandes com brilho azul na face superior em muitos indivíduos e face inferior parda com desenhos ocelares.", habitat: "Matas úmidas, bordas, clareiras e corredores florestais com plantas hospedeiras.", behavior: "Realiza voos planados e alterna deslocamentos rápidos com pousos em folhas e ramos sombreados.", diet: "Adultos visitam frutos em fermentação e outras fontes líquidas; lagartas consomem folhas de plantas hospedeiras.", curiosities: ["O brilho azul resulta da estrutura microscópica das escamas, não de um pigmento azul simples.", "A face inferior contrastante ajuda a reduzir a detecção quando a borboleta permanece pousada."], distribution: "Regiões tropicais da América Central e da América do Sul, incluindo o Brasil.", ecologicalImportance: "Integra as cadeias alimentares florestais e participa do fluxo de matéria e energia entre plantas, herbívoros e predadores.",
      images: [image("https://commons.wikimedia.org/wiki/Special:FilePath/Morpho%20didius%20Male%20MHNT.jpg", "Didier Descouens", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Morpho_didius_Male_MHNT.jpg", "Didier Descouens / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Morpho%20didius%20Male%20Ventre%20MHNT.jpg", "Didier Descouens", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Morpho_didius_Male_Ventre_MHNT.jpg", "Didier Descouens / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Morpho%20menelaus%20huebneri%20MHNT%20Male.jpg", "Didier Descouens", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Morpho_menelaus_huebneri_MHNT_Male.jpg", "Didier Descouens / Wikimedia Commons")], sources: [gbif("Morpho menelaus")],
    },
    {
      id: "ascalapha-odorata", commonName: "Mariposa-bruxa", scientificName: "Ascalapha odorata", group: "Invertebrados", environments: ["Matas", "Bordas de mata"],
      description: "Mariposa noturna de grande porte que utiliza áreas arborizadas e pode visitar estruturas iluminadas durante a noite.", physicalCharacteristics: "Asas largas de coloração marrom-escura, frequentemente com padrões ondulados e manchas que variam entre indivíduos.", habitat: "Matas, bordas, quintais arborizados e outros locais com abrigo diurno e plantas hospedeiras.", behavior: "É predominantemente noturna, repousa em superfícies protegidas durante o dia e pode ser atraída por luzes artificiais.", diet: "Adultos consomem líquidos de frutos ou seiva; lagartas alimentam-se de folhas de plantas hospedeiras.", curiosities: ["O padrão das asas pode fornecer camuflagem em troncos e folhas secas.", "A atividade noturna reduz a exposição a parte dos predadores diurnos, embora aumente o contato com fontes artificiais de luz."], distribution: "Américas tropicais e subtropicais, com ampla distribuição no Brasil.", ecologicalImportance: "Serve de presa para morcegos, aves e outros predadores e participa da decomposição e transferência de nutrientes ao visitar frutos e seiva.",
      images: [image("https://commons.wikimedia.org/wiki/Special:FilePath/Ascalapha%20odorata%20(Mariposa-bruxa).jpg", "André Ribeiro Cardoso", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Ascalapha_odorata_(Mariposa-bruxa).jpg", "André Ribeiro Cardoso / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Black%20witch%20moth%20(Ascalapha%20odorata).JPG", "Charles J. Sharp", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Black_witch_moth_(Ascalapha_odorata).JPG", "Charles J. Sharp / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Starr%20001215%200060%20ascalapha%20odorata.jpg", "Forest & Kim Starr", "CC BY 3.0", "https://commons.wikimedia.org/wiki/File:Starr_001215_0060_ascalapha_odorata.jpg", "Forest & Kim Starr / Wikimedia Commons")], sources: [gbif("Ascalapha odorata")],
    },
    {
      id: "dynastes-hercules", commonName: "Besouro-hércules", scientificName: "Dynastes hercules", group: "Invertebrados", environments: ["Matas"],
      description: "Besouro-rinoceronte de grande porte associado a florestas tropicais, onde larvas e adultos ocupam nichos alimentares diferentes.", physicalCharacteristics: "Machos apresentam cornos torácico e cefálico; o corpo possui élitros e coloração que pode variar conforme umidade e iluminação.", habitat: "Florestas tropicais e áreas arborizadas com madeira em decomposição e matéria vegetal disponível.", behavior: "Adultos deslocam-se principalmente à noite e podem usar o corno em disputas; larvas permanecem no material orgânico do solo ou de troncos.", diet: "Larvas consomem madeira e matéria vegetal em decomposição; adultos utilizam frutos, seiva e outros recursos vegetais.", curiosities: ["A mudança aparente de cor dos élitros está relacionada à umidade das estruturas superficiais.", "O dimorfismo entre machos e fêmeas é acentuado pela presença de cornos nos machos."], distribution: "América Central e norte da América do Sul, em regiões tropicais; a confirmação local no Pantanal permanece pendente.", ecologicalImportance: "A fase larval contribui para a fragmentação de madeira e reciclagem de nutrientes, enquanto adultos integram redes alimentares florestais.",
      images: [image("https://commons.wikimedia.org/wiki/Special:FilePath/Dynastes%20hercules%20(female).jpg", "Hans Hillewaert", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Dynastes_hercules_(female).jpg", "Hans Hillewaert / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Dynastes%20hercules%20ecuatorianus%20MHNT.jpg", "Didier Descouens", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Dynastes_hercules_ecuatorianus_MHNT.jpg", "Didier Descouens / Wikimedia Commons"), image("https://commons.wikimedia.org/wiki/Special:FilePath/Hercules%20beetle%20(Dynastes%20hercules),%20Entomica.jpg", "Fungus Guy", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Hercules_beetle_(Dynastes_hercules),_Entomica.jpg", "Fungus Guy / Wikimedia Commons")], sources: [gbif("Dynastes hercules")],
    },
  ],
};
