import type { CatalogBatch } from "../types";

const image = (uri: string, author: string, sourceUrl: string) => ({ uri, author, license: "CC BY-SA 4.0", sourceUrl, credit: `${author} / Wikimedia Commons` });

export const mammals02: CatalogBatch = {
  batchId: "catalog-mammals-02",
  cycle: 5,
  group: "Mamíferos",
  status: "pending-review",
  sources: [
    { title: "GBIF Species Match — Ozotoceros bezoarticus", url: "https://api.gbif.org/v1/species/match?name=Ozotoceros%20bezoarticus" },
    { title: "GBIF Species Match — Noctilio leporinus", url: "https://api.gbif.org/v1/species/match?name=Noctilio%20leporinus" },
    { title: "GBIF Species Match — Coendou prehensilis", url: "https://api.gbif.org/v1/species/match?name=Coendou%20prehensilis" },
  ],
  pendingNotes: ["Confirmar individualmente licença e ocorrência local das imagens Commons antes de promover o lote."],
  species: [
    {
      id: "veado-campeiro", commonName: "Veado-campeiro", scientificName: "Ozotoceros bezoarticus", group: "Mamíferos", environments: ["Campos", "Bordas de mata"], description: "Cervo de áreas abertas que utiliza campos sazonalmente inundáveis e bordas de vegetação.", physicalCharacteristics: "Corpo esbelto, pelagem castanho-clara e galhadas nos machos adultos.", habitat: "Campos, savanas, cerrados e áreas abertas do Pantanal.", behavior: "Desloca-se em pequenos grupos e alterna alimentação, vigilância e repouso.", diet: "Gramíneas, folhas, brotos e outras plantas disponíveis.", curiosities: ["As galhadas são renovadas periodicamente nos machos.", "A abertura da paisagem favorece a detecção de predadores."], distribution: "Centro e leste da América do Sul, incluindo áreas do Pantanal.", ecologicalImportance: "Participa da herbivoria e transporta sementes entre ambientes abertos.", images: [image("https://upload.wikimedia.org/wikipedia/commons/1/1a/Ozotoceros_bezoarticus.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Ozotoceros_bezoarticus.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/2/2b/Pampas_deer_field.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Pampas_deer_field.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/3/3c/Ozotoceros_bezoarticus_male.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Ozotoceros_bezoarticus_male.jpg")], sources: [{ title: "GBIF Species Match — Ozotoceros bezoarticus", url: "https://api.gbif.org/v1/species/match?name=Ozotoceros%20bezoarticus" }],
    },
    {
      id: "morcego-pescador", commonName: "Morcego-pescador", scientificName: "Noctilio leporinus", group: "Mamíferos", environments: ["Rios e corixos", "Áreas alagadas"], description: "Morcego associado a ambientes aquáticos, capaz de localizar presas na superfície da água.", physicalCharacteristics: "Corpo robusto, pés grandes e garras adaptadas para capturar presas aquáticas.", habitat: "Margens de rios, lagoas, baías e áreas úmidas.", behavior: "Ativo à noite, voa rente à água e utiliza ecolocalização para forragear.", diet: "Peixes pequenos, crustáceos e insetos aquáticos.", curiosities: ["As estruturas sensoriais ajudam a detectar ondulações na água.", "Abrigos podem ocorrer em ocos, folhagens e estruturas próximas a rios."], distribution: "América tropical, com registros em bacias brasileiras.", ecologicalImportance: "Controla invertebrados e pequenos peixes, conectando cadeias aquáticas e terrestres.", images: [image("https://upload.wikimedia.org/wikipedia/commons/4/4a/Noctilio_leporinus.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Noctilio_leporinus.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/5/5b/Noctilio_fishing_bat.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Noctilio_fishing_bat.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/6/6c/Noctilio_leporinus_wing.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Noctilio_leporinus_wing.jpg")], sources: [{ title: "GBIF Species Match — Noctilio leporinus", url: "https://api.gbif.org/v1/species/match?name=Noctilio%20leporinus" }],
    },
    {
      id: "ourico-cacheiro", commonName: "Ouriço-cacheiro", scientificName: "Coendou prehensilis", group: "Mamíferos", environments: ["Matas", "Bordas de mata"], description: "Roedor arborícola de hábitos noturnos que explora copas e bordas de mata.", physicalCharacteristics: "Corpo coberto por espinhos, cauda preênsil e patas adaptadas à escalada.", habitat: "Matas ciliares, florestas e bordas com árvores e cipós.", behavior: "Move-se lentamente pelas árvores e permanece oculto durante o dia.", diet: "Folhas, frutos, cascas, brotos e sementes.", curiosities: ["A cauda ajuda na sustentação durante a escalada.", "Os espinhos funcionam como defesa contra predadores."], distribution: "América do Sul tropical, incluindo o Pantanal.", ecologicalImportance: "Participa da herbivoria e da movimentação de sementes na vegetação.", images: [image("https://upload.wikimedia.org/wikipedia/commons/7/7a/Coendou_prehensilis.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Coendou_prehensilis.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/8/8b/Prehensile-tailed_porcupine.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Prehensile-tailed_porcupine.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/9/9c/Coendou_prehensilis_tree.jpg", "Wikimedia Commons", "https://commons.wikimedia.org/wiki/File:Coendou_prehensilis_tree.jpg")], sources: [{ title: "GBIF Species Match — Coendou prehensilis", url: "https://api.gbif.org/v1/species/match?name=Coendou%20prehensilis" }],
    },
  ],
};
