import type { CatalogBatch } from "../types";

const image = (uri: string, author: string, license: string, sourceUrl: string) => ({ uri, author, license, sourceUrl, credit: `${author} / Wikimedia Commons` });

export const reptiles02: CatalogBatch = {
  batchId: "catalog-reptiles-02",
  cycle: 9,
  group: "Répteis",
  status: "pending-review",
  sources: [
    { title: "GBIF Species Match — Acanthochelys macrocephala", url: "https://api.gbif.org/v1/species/match?name=Acanthochelys%20macrocephala" },
    { title: "GBIF Species Match — Helicops infrataeniatus", url: "https://api.gbif.org/v1/species/match?name=Helicops%20infrataeniatus" },
    { title: "GBIF Species Match — Caiman yacare", url: "https://api.gbif.org/v1/species/match?name=Caiman%20yacare" },
    { title: "GBIF Species Match — Salvator rufescens", url: "https://api.gbif.org/v1/species/match?name=Salvator%20rufescens" },
  ],
  pendingNotes: ["Confirmar individualmente as páginas Commons e a ocorrência no recorte pantaneiro antes da promoção editorial."],
  species: [
    {
      id: "cangapara", commonName: "Cágado-cabeçudo", scientificName: "Acanthochelys macrocephala", group: "Répteis", environments: ["Rios e corixos", "Áreas alagadas"], description: "Quelônio de água doce associado a áreas alagadas, margens vegetadas e ambientes lentos.", physicalCharacteristics: "Carapaça escura e robusta, cabeça larga e membros adaptados à água doce.", habitat: "Baías, corixos, lagoas e margens com vegetação aquática.", behavior: "Alterna períodos na água e em locais de descanso nas margens.", diet: "Invertebrados, pequenos animais, plantas e matéria orgânica.", curiosities: ["A carapaça oferece proteção contra predadores.", "A qualidade das margens influencia abrigo e alimentação."], distribution: "Bacia do Paraguai e áreas úmidas do centro da América do Sul.", ecologicalImportance: "Participa do fluxo de matéria entre fundos, margens e águas rasas.", images: [image("https://upload.wikimedia.org/wikipedia/commons/1/1a/Acanthochelys_macrocephala.jpg", "Goodshort", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Acanthochelys_macrocephala.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/e/eb/Big-headed_Pantanal_Swamp_Turtle_%28Acanthochelys_macrocephala%29.jpg", "Bernard DUPONT", "CC BY-SA 2.0", "https://commons.wikimedia.org/wiki/File:Big-headed_Pantanal_Swamp_Turtle_(Acanthochelys_macrocephala).jpg"), image("https://upload.wikimedia.org/wikipedia/commons/1/10/Big-headed_Pantanal_Swamp_Turtle_%28Acanthochelys_macrocephala%29_%2831831317365%29.jpg", "Bernard DUPONT", "CC BY-SA 2.0", "https://commons.wikimedia.org/wiki/File:Big-headed_Pantanal_Swamp_Turtle_(Acanthochelys_macrocephala)_(31831317365).jpg")], sources: [{ title: "GBIF Species Match — Acanthochelys macrocephala", url: "https://api.gbif.org/v1/species/match?name=Acanthochelys%20macrocephala" }],
    },
    {
      id: "cobra-dagua", commonName: "Cobra-d'água", scientificName: "Helicops infrataeniatus", group: "Répteis", environments: ["Rios e corixos", "Áreas alagadas"], description: "Serpente aquática que utiliza corpos d'água e margens vegetadas para caçar e se abrigar.", physicalCharacteristics: "Corpo alongado, escamas lisas e padrão que ajuda na camuflagem entre a vegetação.", habitat: "Lagoas, corixos, banhados e margens de rios.", behavior: "Nada com facilidade e procura presas em águas rasas e entre plantas.", diet: "Peixes, girinos e pequenos animais aquáticos.", curiosities: ["O corpo hidrodinâmico facilita a natação.", "A coloração pode quebrar o contorno entre sombras e vegetação."], distribution: "Regiões úmidas do sul e centro da América do Sul.", ecologicalImportance: "Controla pequenos vertebrados aquáticos e integra a cadeia alimentar de áreas úmidas.", images: [image("https://upload.wikimedia.org/wikipedia/commons/3/35/Helicops_infrataeniatus01.jpg", "Diogo B. Provete", "CC BY-SA 2.5", "https://commons.wikimedia.org/wiki/File:Helicops_infrataeniatus01.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/b/b5/Helicops_infrataeniatus_cabeca_Catanduva_SP_OAVM.jpg", "Otavio A Marques", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Helicops_infrataeniatus_cabeca_Catanduva_SP_OAVM.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/b/b1/Helicops_infrataeniatus_Catanduva_SP_OAVM2.jpg", "Otavio A Marques", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Helicops_infrataeniatus_Catanduva_SP_OAVM2.jpg")], sources: [{ title: "GBIF Species Match — Helicops infrataeniatus", url: "https://api.gbif.org/v1/species/match?name=Helicops%20infrataeniatus" }],
    },
    {
      id: "jacare-pagua", commonName: "Jacaré-do-Pantanal", scientificName: "Caiman yacare", group: "Répteis", environments: ["Rios e corixos", "Áreas alagadas"], description: "Jacaré abundante em rios, baías e corixos, adaptado ao ciclo anual de cheias e secas.", physicalCharacteristics: "Corpo alongado, focinho largo, placas dérmicas e cauda musculosa.", habitat: "Rios, lagoas, baías, corixos e campos inundáveis.", behavior: "Aquece-se nas margens, caça na água e pode formar concentrações em períodos sazonais.", diet: "Peixes, crustáceos, insetos e pequenos vertebrados.", curiosities: ["A temperatura influencia atividade e reprodução.", "As áreas de vazante concentram alimento durante a seca."], distribution: "Bacia do Paraguai e outras áreas úmidas do centro da América do Sul.", ecologicalImportance: "Predador aquático e indicador da integridade de ambientes úmidos.", images: [image("https://upload.wikimedia.org/wikipedia/commons/4/4c/Brillenkaiman_Caiman_yacare.jpg", "Andreas Trepte", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Brillenkaiman_Caiman_yacare.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/6/66/Yacare_caiman_%28Caiman_yacare%29_2.jpg", "Charles J. Sharp", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Yacare_caiman_(Caiman_yacare)_2.jpg"), image("https://upload.wikimedia.org/wikipedia/commons/7/7e/023_Yacare_caiman_sunbathing_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg", "Giles Laurent", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:023_Yacare_caiman_sunbathing_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg")], sources: [{ title: "GBIF Species Match — Caiman yacare", url: "https://api.gbif.org/v1/species/match?name=Caiman%20yacare" }],
    },
    {
      id: "tei-de-cauda-vermelha", commonName: "Teiú-vermelho", scientificName: "Salvator rufescens", group: "Répteis", environments: ["Campos", "Bordas de mata"], description: "Lagarto terrestre de grande porte que explora áreas abertas, bordas e abrigos no solo.", physicalCharacteristics: "Corpo robusto, cauda longa, garras fortes e coloração avermelhada.", habitat: "Campos, cerrados, bordas de mata e áreas com solo para escavação.", behavior: "Diurno, oportunista e capaz de utilizar tocas para abrigo e termorregulação.", diet: "Frutos, ovos, insetos, pequenos vertebrados e carniça.", curiosities: ["A dieta ampla permite explorar ambientes sazonais.", "A escavação cria refúgios usados em períodos de calor ou ameaça."], distribution: "Centro-sul da América do Sul, com ocorrência em formações abertas.", ecologicalImportance: "Preda, remove matéria orgânica e pode dispersar sementes.", images: [image("https://upload.wikimedia.org/wikipedia/commons/2/2d/Argentine_Red_Tegu_8_weeks.jpeg", "Scott Hogge", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Argentine_Red_Tegu_8_weeks.jpeg"), image("https://upload.wikimedia.org/wikipedia/commons/3/35/Red_Tegu_%28Salvator_rufescens%29.jpg", "Holger Braun", "CC BY 4.0", "https://commons.wikimedia.org/wiki/File:Red_Tegu_(Salvator_rufescens).jpg"), image("https://upload.wikimedia.org/wikipedia/commons/2/2d/Salvator_rufescens_32477548.jpg", "Hugo Hulsberg", "CC0", "https://commons.wikimedia.org/wiki/File:Salvator_rufescens_32477548.jpg")], sources: [{ title: "GBIF Species Match — Salvator rufescens", url: "https://api.gbif.org/v1/species/match?name=Salvator%20rufescens" }],
    },
  ],
};
