import { Linking, Pressable, ScrollView, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { species } from "@/shared/pantanal";
import { useColors } from "@/hooks/use-colors";
import { SpeciesImage } from "@/components/species-image";

export default function SpeciesDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const colors = useColors(); const animal = species.find((item) => item.id === id) ?? species[0];
  const block = (title: string, content: string) => <View style={{ marginTop: 20 }}><Text style={{ color: colors.primary, fontWeight: "800", fontSize: 15, textTransform: "uppercase", letterSpacing: .7 }}>{title}</Text><Text style={{ color: colors.foreground, fontSize: 15, lineHeight: 23, marginTop: 6 }}>{content}</Text></View>;
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="px-5"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 40 }}><Pressable onPress={() => router.back()}><Text style={{ color: colors.primary, fontSize: 16, fontWeight: "700", paddingVertical: 14 }}>‹ Voltar</Text></Pressable><ScrollView horizontal pagingEnabled showsHorizontalScrollIndicator={false} style={{ marginHorizontal: -20 }} contentContainerStyle={{ gap: 8 }}>{animal.images.map((image) => <SpeciesImage key={image.uri} image={image} style={{ width: 340, height: 230, backgroundColor: colors.border }} label={`${animal.commonName} sem fotografia disponível`} />)}</ScrollView><Text style={{ color: colors.muted, fontSize: 12, marginTop: 8 }}>Deslize para consultar as {animal.images.length} imagens. Os créditos e as licenças estão ao final da ficha.</Text><Text style={{ color: colors.foreground, fontSize: 30, fontWeight: "800", marginTop: 18 }}>{animal.commonName}</Text><Text style={{ color: colors.muted, fontStyle: "italic", fontSize: 16, marginTop: 3 }}>{animal.scientificName}</Text><View style={{ flexDirection: "row", gap: 8, marginTop: 12 }}><Text style={{ backgroundColor: colors.primary, color: "#fff", borderRadius: 14, paddingHorizontal: 10, paddingVertical: 6, fontWeight: "700", fontSize: 12 }}>{animal.group}</Text><Text style={{ backgroundColor: colors.surface, color: colors.foreground, borderRadius: 14, paddingHorizontal: 10, paddingVertical: 6, fontSize: 12 }}>{animal.environments[0]}</Text></View>{block("Sobre", animal.description)}{block("Características", animal.physicalCharacteristics)}{block("Habitat", animal.habitat)}{block("Comportamento", animal.behavior)}{block("Alimentação", animal.diet)}{block("Importância ecológica", animal.ecologicalImportance)}{block("Distribuição", animal.distribution)}{block("Conservação", animal.conservationStatus ?? "Informação não disponível")}{block("Curiosidades", animal.curiosities.join("\n\n"))}<Pressable onPress={() => router.push({ pathname: "/sightings/new", params: { speciesId: animal.id } } as any)} style={{ backgroundColor: colors.primary, borderRadius: 16, padding: 16, marginTop: 24 }}><Text style={{ color: "#fff", textAlign: "center", fontWeight: "800", fontSize: 16 }}>Registrar avistamento</Text></Pressable><Text style={{ color: colors.muted, fontWeight: "700", marginTop: 24 }}>Imagens e fontes</Text>{animal.images.map((image) => <Pressable key={`${image.uri}-credit`} onPress={() => Linking.openURL(image.sourceUrl)}><Text style={{ color: colors.muted, fontSize: 12, marginTop: 6 }}>{image.credit} · {image.license}</Text></Pressable>)}{animal.sources.map((source) => <Pressable key={source.url} onPress={() => Linking.openURL(source.url)}><Text style={{ color: colors.primary, marginTop: 8 }}>{source.title}</Text></Pressable>)}</ScrollView></ScreenContainer>;
}
