export type SpeciesGroup = "Mamíferos" | "Aves" | "Répteis" | "Anfíbios" | "Peixes" | "Invertebrados";
export type Environment = "Rios e corixos" | "Áreas alagadas" | "Campos" | "Matas" | "Bordas de mata";
export type LocationPrecision = "exact" | "approximate" | "municipality" | "none";
export type Visibility = "private" | "shareable";

export type Species = {
  id: string;
  commonName: string;
  scientificName: string;
  group: SpeciesGroup;
  environments: Environment[];
  description: string;
  physicalCharacteristics: string;
  habitat: string;
  behavior: string;
  diet: string;
  curiosities: string[];
  distribution: string;
  ecologicalImportance: string;
  conservationStatus?: string;
  images: { uri: string; author: string; license: string; sourceUrl: string; credit: string }[];
  sources: { title: string; url: string }[];
};

export type Sighting = {
  id: string;
  speciesId: string;
  photoUri?: string;
  date: string;
  time?: string;
  locationLabel?: string;
  latitude?: number;
  longitude?: number;
  locationPrecision: LocationPrecision;
  quantity?: number;
  notes?: string;
  visibility: Visibility;
  createdAt: string;
  updatedAt: string;
};

export const groups: SpeciesGroup[] = ["Mamíferos", "Aves", "Répteis", "Anfíbios", "Peixes", "Invertebrados"];
export const environments: Environment[] = ["Rios e corixos", "Áreas alagadas", "Campos", "Matas", "Bordas de mata"];
export const languages = ["Português", "English", "Español"];

const commons = (file: string, author: string) => ({
  uri: `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=900`,
  author,
  license: "CC BY-SA 4.0",
  sourceUrl: "https://commons.wikimedia.org/",
  credit: `${author} / Wikimedia Commons`,
});

export const species: Species[] = [
  {
    id: "tuiuiu", commonName: "Tuiuiú", scientificName: "Jabiru mycteria", group: "Aves", environments: ["Áreas alagadas", "Rios e corixos"],
    description: "Grande ave pernalta símbolo do Pantanal, frequentemente observada em áreas abertas e alagadas.", physicalCharacteristics: "Plumagem branca, cabeça preta e papo vermelho, com pernas longas e bico robusto.", habitat: "Campos inundáveis, baías, vazantes e margens de rios.", behavior: "Constrói ninhos altos e pode ser visto forrageando em águas rasas.", diet: "Peixes, anfíbios, répteis, insetos e pequenos vertebrados.", curiosities: ["É uma das maiores aves voadoras da América do Sul.", "Seu ninho pode ser reutilizado por vários anos."], distribution: "América Central e América do Sul, incluindo todo o Pantanal.", ecologicalImportance: "Ajuda a indicar a disponibilidade de alimento e a saúde das áreas úmidas.", conservationStatus: "Pouco preocupante", images: [commons("Jabiru mycteria - Brazil.jpg", "Wikimedia Commons"), commons("Jabiru mycteria flying.jpg", "Wikimedia Commons"), commons("Jabiru mycteria nest.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Jabiru mycteria", url: "https://www.iucnredlist.org/species/22697710/93625378" }]
  },
  {
    id: "arara-azul", commonName: "Arara-azul", scientificName: "Anodorhynchus hyacinthinus", group: "Aves", environments: ["Matas", "Bordas de mata"],
    description: "Arara de grande porte, reconhecida pela plumagem azul-cobalto e pelo bico poderoso.", physicalCharacteristics: "Azul intenso, anel amarelo ao redor dos olhos e da base do bico.", habitat: "Matas ciliares, áreas de carandazais e bordas de mata.", behavior: "Vive em pares ou grupos familiares e usa ocos de árvores para nidificar.", diet: "Principalmente frutos de palmeiras, como acuri e bocaiúva.", curiosities: ["O bico quebra frutos muito resistentes.", "A conservação depende da oferta de palmeiras e árvores com ocos."], distribution: "Brasil central, Bolívia e Paraguai, com população importante no Pantanal.", ecologicalImportance: "Dispersa sementes e participa da regeneração das palmeiras pantaneiras.", conservationStatus: "Vulnerável", images: [commons("Anodorhynchus hyacinthinus -Brazil-8.jpg", "Wikimedia Commons"), commons("Hyacinth Macaw.jpg", "Wikimedia Commons"), commons("Anodorhynchus hyacinthinus in flight.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Anodorhynchus hyacinthinus", url: "https://www.iucnredlist.org/species/22685516/132559780" }]
  },
  {
    id: "onca-pintada", commonName: "Onça-pintada", scientificName: "Panthera onca", group: "Mamíferos", environments: ["Matas", "Bordas de mata", "Rios e corixos"],
    description: "Maior felino das Américas e predador de topo dos ambientes pantaneiros.", physicalCharacteristics: "Pelagem dourada com rosetas, corpo musculoso e mordida muito potente.", habitat: "Matas próximas a rios, corixos e áreas com boa oferta de presas.", behavior: "Solitária, territorial e excelente nadadora.", diet: "Capivaras, jacarés, queixadas, cervos e outros vertebrados.", curiosities: ["As rosetas podem apresentar pequenos pontos centrais.", "Rios e baías são importantes corredores para a espécie."], distribution: "Do México ao norte da Argentina, com população relevante no Pantanal.", ecologicalImportance: "Regula populações de presas e ajuda a manter o equilíbrio das cadeias alimentares.", conservationStatus: "Quase ameaçada", images: [commons("Jaguar (Panthera onca) female.jpg", "Wikimedia Commons"), commons("Panthera onca at the river.jpg", "Wikimedia Commons"), commons("Jaguar portrait.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Panthera onca", url: "https://www.iucnredlist.org/species/15953/123791436" }]
  },
  {
    id: "capivara", commonName: "Capivara", scientificName: "Hydrochoerus hydrochaeris", group: "Mamíferos", environments: ["Rios e corixos", "Áreas alagadas", "Campos"],
    description: "Maior roedor vivo do mundo, muito associado às margens de corpos d’água.", physicalCharacteristics: "Corpo robusto, patas parcialmente palmadas e pelagem castanho-avermelhada.", habitat: "Margens de rios, lagoas, baías e campos úmidos.", behavior: "Social, vive em grupos e busca refúgio na água quando ameaçada.", diet: "Gramíneas e plantas aquáticas.", curiosities: ["Pode permanecer submersa por vários minutos.", "Grupos costumam apresentar forte organização social."], distribution: "Grande parte da América do Sul, incluindo o Pantanal.", ecologicalImportance: "É presa importante para grandes predadores e influencia a vegetação das margens.", conservationStatus: "Pouco preocupante", images: [commons("Hydrochoerus hydrochaeris.jpg", "Wikimedia Commons"), commons("Capybara swimming.jpg", "Wikimedia Commons"), commons("Capybara group.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Hydrochoerus hydrochaeris", url: "https://www.iucnredlist.org/species/10300/22190115" }]
  },
  {
    id: "jacare-do-pantanal", commonName: "Jacaré-do-pantanal", scientificName: "Caiman yacare", group: "Répteis", environments: ["Rios e corixos", "Áreas alagadas"], description: "Jacaré abundante nas águas pantaneiras, adaptado à dinâmica sazonal das cheias.", physicalCharacteristics: "Corpo alongado, focinho estreito e faixas claras na mandíbula.", habitat: "Baías, corixos, lagoas e rios de águas lentas.", behavior: "Toma sol nas margens e caça principalmente durante o período de atividade noturna.", diet: "Peixes, crustáceos, anfíbios e pequenos vertebrados.", curiosities: ["As áreas alagadas oferecem abrigo e alimento durante a seca.", "Filhotes usam vegetação marginal como proteção."], distribution: "Centro da América do Sul, especialmente Brasil, Bolívia e Paraguai.", ecologicalImportance: "Participa do controle de populações aquáticas e transporta nutrientes entre água e margens.", conservationStatus: "Pouco preocupante", images: [commons("Caiman yacare.jpg", "Wikimedia Commons"), commons("Yacare caiman river.jpg", "Wikimedia Commons"), commons("Caiman yacare closeup.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Caiman yacare", url: "https://www.iucnredlist.org/species/46584/3009948" }]
  },
  {
    id: "anta", commonName: "Anta", scientificName: "Tapirus terrestris", group: "Mamíferos", environments: ["Matas", "Rios e corixos"],
    description: "Grande mamífero herbívoro que percorre matas, veredas e margens de rios no Pantanal.", physicalCharacteristics: "Corpo volumoso, focinho alongado e pelagem castanha curta.", habitat: "Matas ciliares, capões e áreas próximas à água.", behavior: "Solitária, geralmente mais ativa no crepúsculo e à noite.", diet: "Folhas, frutos, brotos e outras partes de plantas.", curiosities: ["É uma importante dispersora de sementes.", "Nada bem e usa a água para fugir de ameaças."], distribution: "América do Sul a leste dos Andes, incluindo o Pantanal.", ecologicalImportance: "Transporta sementes entre diferentes ambientes e contribui para a regeneração florestal.", conservationStatus: "Vulnerável", images: [commons("Lowland tapir (Tapirus terrestris).jpg", "Wikimedia Commons"), commons("Tapirus terrestris 01.jpg", "Wikimedia Commons"), commons("Tapirus terrestris swimming.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Tapirus terrestris", url: "https://www.iucnredlist.org/search?query=Tapirus%20terrestris&searchType=species" }]
  },
  {
    id: "tamandua-bandeira", commonName: "Tamanduá-bandeira", scientificName: "Myrmecophaga tridactyla", group: "Mamíferos", environments: ["Campos", "Bordas de mata"],
    description: "Mamífero especializado em capturar formigas e cupins com a língua longa e pegajosa.", physicalCharacteristics: "Focinho tubular, cauda muito volumosa e faixa diagonal escura no corpo.", habitat: "Campos, savanas e bordas de matas com solo adequado para escavação.", behavior: "Caminha longas distâncias e pode ser ativo de dia ou à noite.", diet: "Formigas e cupins.", curiosities: ["Não possui dentes funcionais.", "A língua pode ser projetada repetidamente para retirar insetos dos ninhos."], distribution: "América Central e América do Sul, incluindo áreas abertas do Pantanal.", ecologicalImportance: "Controla populações de insetos sociais e revolve o solo ao abrir formigueiros e cupinzeiros.", conservationStatus: "Vulnerável", images: [commons("Myrmecophaga tridactyla.jpg", "Wikimedia Commons"), commons("Giant anteater walking.jpg", "Wikimedia Commons"), commons("Myrmecophaga tridactyla Pantanal.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Myrmecophaga tridactyla", url: "https://www.iucnredlist.org/search?query=Myrmecophaga%20tridactyla&searchType=species" }]
  },
  {
    id: "cervo-do-pantanal", commonName: "Cervo-do-pantanal", scientificName: "Blastocerus dichotomus", group: "Mamíferos", environments: ["Áreas alagadas", "Campos"],
    description: "Maior cervídeo da América do Sul, associado a várzeas, brejos e campos inundáveis.", physicalCharacteristics: "Pernas longas, pelagem castanho-avermelhada e galhadas ramificadas nos machos.", habitat: "Brejos, baías, campos inundáveis e margens de rios.", behavior: "Usa áreas alagadas como abrigo e desloca-se em busca de vegetação aquática.", diet: "Gramíneas, plantas aquáticas, folhas e brotos.", curiosities: ["As adaptações das pernas favorecem o deslocamento em terrenos úmidos.", "A espécie depende da manutenção de áreas úmidas conectadas."], distribution: "Centro e sul da América do Sul, com ocorrência no Pantanal.", ecologicalImportance: "Participa da dinâmica da vegetação de áreas úmidas e dispersa sementes.", conservationStatus: "Vulnerável", images: [commons("Blastocerus dichotomus.jpg", "Wikimedia Commons"), commons("Marsh deer Pantanal.jpg", "Wikimedia Commons"), commons("Blastocerus dichotomus male.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Blastocerus dichotomus", url: "https://www.iucnredlist.org/search?query=Blastocerus%20dichotomus&searchType=species" }]
  },
  {
    id: "ema", commonName: "Ema", scientificName: "Rhea americana", group: "Aves", environments: ["Campos", "Bordas de mata"],
    description: "Ave corredora de grande porte que ocupa campos e áreas abertas do Pantanal.", physicalCharacteristics: "Pescoço longo, asas reduzidas, pernas fortes e plumagem parda.", habitat: "Campos, cerrados e áreas abertas com vegetação baixa.", behavior: "Vive em grupos e corre rapidamente quando perturbada.", diet: "Frutos, sementes, folhas e pequenos animais.", curiosities: ["O macho participa da incubação e do cuidado dos filhotes.", "As asas ajudam no equilíbrio durante a corrida."], distribution: "América do Sul, com ocorrência em áreas abertas do Pantanal.", ecologicalImportance: "Dispersa sementes e integra as cadeias alimentares dos campos.", conservationStatus: "Pouco preocupante", images: [commons("Rhea americana.jpg", "Wikimedia Commons"), commons("Greater rhea running.jpg", "Wikimedia Commons"), commons("Rhea americana Pantanal.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Rhea americana", url: "https://www.iucnredlist.org/search?query=Rhea%20americana&searchType=species" }]
  },
  {
    id: "colhereiro", commonName: "Colhereiro", scientificName: "Platalea ajaja", group: "Aves", environments: ["Áreas alagadas", "Rios e corixos"],
    description: "Ave aquática de bico espatulado, observada em águas rasas e margens lamacentas.", physicalCharacteristics: "Plumagem rosada, pescoço claro e bico longo com ponta em forma de colher.", habitat: "Lagoas, baías, brejos e margens de rios.", behavior: "Move o bico de um lado para o outro na água para localizar alimento.", diet: "Peixes pequenos, crustáceos, insetos e outros invertebrados aquáticos.", curiosities: ["A coloração rosada está relacionada à alimentação.", "Costuma forragear em grupos em áreas rasas."], distribution: "Américas, principalmente zonas úmidas costeiras e continentais.", ecologicalImportance: "Conecta as cadeias alimentares de invertebrados e pequenos peixes em áreas úmidas.", conservationStatus: "Pouco preocupante", images: [commons("Platalea ajaja -Brazil-8.jpg", "Wikimedia Commons"), commons("Roseate spoonbill feeding.jpg", "Wikimedia Commons"), commons("Platalea ajaja flight.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Platalea ajaja", url: "https://www.iucnredlist.org/search?query=Platalea%20ajaja&searchType=species" }]
  },
  {
    id: "garca-branca", commonName: "Garça-branca", scientificName: "Ardea alba", group: "Aves", environments: ["Áreas alagadas", "Rios e corixos"],
    description: "Garça grande e clara, comum em margens, campos inundáveis e corpos d’água do Pantanal.", physicalCharacteristics: "Plumagem branca, pescoço comprido, bico amarelo e pernas escuras.", habitat: "Rios, baías, corixos, brejos e campos alagados.", behavior: "Caminha lentamente em águas rasas e captura presas com um golpe rápido do bico.", diet: "Peixes, anfíbios, répteis pequenos, crustáceos e insetos.", curiosities: ["Pode permanecer imóvel por longos períodos durante a caça.", "Reúne-se em colônias para reprodução."], distribution: "Ampla distribuição mundial, com presença em todo o Brasil.", ecologicalImportance: "Preda diversos organismos aquáticos e indica a disponibilidade de alimento nas margens.", conservationStatus: "Pouco preocupante", images: [commons("Ardea alba -Brazil-8.jpg", "Wikimedia Commons"), commons("Great egret fishing.jpg", "Wikimedia Commons"), commons("Ardea alba in flight.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Ardea alba", url: "https://www.iucnredlist.org/search?query=Ardea%20alba&searchType=species" }]
  },
  {
    id: "sucuri-verde", commonName: "Sucuri-verde", scientificName: "Eunectes murinus", group: "Répteis", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Grande serpente semiaquática que utiliza rios, baías e áreas alagadas para caçar.", physicalCharacteristics: "Corpo robusto, coloração verde-oliva com manchas escuras e olhos posicionados no alto da cabeça.", habitat: "Brejos, lagoas, baías, corixos e margens de rios.", behavior: "Permanece parcialmente submersa e captura presas por constrição.", diet: "Peixes, aves, mamíferos e outros vertebrados de tamanho compatível.", curiosities: ["As narinas e os olhos ajudam a observar o entorno com o corpo submerso.", "É uma das maiores serpentes do mundo em massa corporal."], distribution: "Regiões tropicais da América do Sul, incluindo o Pantanal.", ecologicalImportance: "Atua como predadora de topo em ambientes aquáticos e ribeirinhos.", conservationStatus: "Pouco preocupante", images: [commons("Eunectes murinus.jpg", "Wikimedia Commons"), commons("Green anaconda swimming.jpg", "Wikimedia Commons"), commons("Eunectes murinus closeup.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Eunectes murinus", url: "https://www.iucnredlist.org/search?query=Eunectes%20murinus&searchType=species" }]
  },
  {
    id: "jabuti-piranga", commonName: "Jabuti-piranga", scientificName: "Chelonoidis carbonaria", group: "Répteis", environments: ["Matas", "Bordas de mata"],
    description: "Jabuti terrestre de hábitos predominantemente diurnos, encontrado em áreas florestadas e seus arredores.", physicalCharacteristics: "Carapaça escura com manchas amarelas ou alaranjadas e escamas coloridas nas patas.", habitat: "Matas, capões, bordas de mata e áreas com serapilheira.", behavior: "Desloca-se pelo chão e procura alimento entre folhas e frutos caídos.", diet: "Frutos, folhas, flores, fungos e pequenos invertebrados.", curiosities: ["Pode contribuir para a dispersão de sementes de frutos que consome.", "A carapaça oferece proteção, mas não torna a espécie imune a queimadas e perda de habitat."], distribution: "Norte e centro da América do Sul, incluindo áreas do Brasil central.", ecologicalImportance: "Dispersa sementes e participa da ciclagem de matéria orgânica no solo.", conservationStatus: "Vulnerável", images: [commons("Chelonoidis carbonaria.jpg", "Wikimedia Commons"), commons("Red-footed tortoise walking.jpg", "Wikimedia Commons"), commons("Chelonoidis carbonaria head.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Chelonoidis carbonaria", url: "https://www.iucnredlist.org/search?query=Chelonoidis%20carbonaria&searchType=species" }]
  },
  {
    id: "sapo-cururu", commonName: "Sapo-cururu", scientificName: "Rhinella diptycha", group: "Anfíbios", environments: ["Campos", "Bordas de mata"],
    description: "Sapo de grande porte, adaptável a áreas abertas e frequentemente observado após chuvas.", physicalCharacteristics: "Pele rugosa, glândulas parotoides evidentes e coloração variável em tons terrosos.", habitat: "Campos, bordas de mata, áreas úmidas temporárias e ambientes modificados.", behavior: "É mais ativo à noite e reproduz-se em corpos d’água temporários ou permanentes.", diet: "Insetos e outros pequenos invertebrados.", curiosities: ["As glândulas cutâneas produzem substâncias defensivas.", "Girinos dependem de água para completar o desenvolvimento."], distribution: "Brasil central e outras áreas da América do Sul, incluindo o Pantanal.", ecologicalImportance: "Controla invertebrados e serve de alimento para predadores.", conservationStatus: "Pouco preocupante", images: [commons("Rhinella diptycha.jpg", "Wikimedia Commons"), commons("Rhinella toad closeup.jpg", "Wikimedia Commons"), commons("Rhinella diptycha in water.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Rhinella diptycha", url: "https://www.iucnredlist.org/search?query=Rhinella%20diptycha&searchType=species" }]
  },
  {
    id: "ra-pimenta", commonName: "Rã-pimenta", scientificName: "Leptodactylus labyrinthicus", group: "Anfíbios", environments: ["Áreas alagadas", "Campos"],
    description: "Rã de grande porte associada a áreas úmidas, poças e margens com vegetação.", physicalCharacteristics: "Corpo robusto, dorso castanho com desenhos contrastantes e membros posteriores fortes.", habitat: "Brejos, lagoas temporárias, campos úmidos e margens de córregos.", behavior: "Pode construir ninhos de espuma e vocaliza principalmente no período reprodutivo.", diet: "Insetos, aranhas e outros pequenos animais.", curiosities: ["A espuma ajuda a proteger ovos em ambientes sujeitos à variação do nível da água.", "A espécie é conhecida por vocalizações fortes durante as chuvas."], distribution: "Brasil e países vizinhos, com ocorrência em áreas abertas e úmidas do centro-sul.", ecologicalImportance: "Participa do controle de invertebrados e é sensível à alteração de áreas reprodutivas.", conservationStatus: "Pouco preocupante", images: [commons("Leptodactylus labyrinthicus.jpg", "Wikimedia Commons"), commons("Leptodactylus labyrinthicus frog.jpg", "Wikimedia Commons"), commons("Leptodactylus labyrinthicus profile.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Leptodactylus labyrinthicus", url: "https://www.iucnredlist.org/search?query=Leptodactylus%20labyrinthicus&searchType=species" }]
  },
  {
    id: "pintado", commonName: "Pintado", scientificName: "Pseudoplatystoma corruscans", group: "Peixes", environments: ["Rios e corixos"],
    description: "Peixe de couro de grande porte, importante nos rios e na pesca tradicional do Pantanal.", physicalCharacteristics: "Corpo alongado, cabeça achatada, barbilhões e manchas escuras em faixas.", habitat: "Canais de rios, poços e trechos com correnteza.", behavior: "Predador ativo, especialmente ao localizar peixes em movimento.", diet: "Peixes e outros organismos aquáticos.", curiosities: ["Os barbilhões auxiliam na percepção do ambiente.", "A reprodução acompanha o pulso de cheias e a migração pelos rios."], distribution: "Bacias do Paraná-Paraguai e do São Francisco, incluindo o Pantanal.", ecologicalImportance: "É predador relevante e indicador da conectividade dos ambientes fluviais.", conservationStatus: "Dados insuficientes", images: [commons("Pseudoplatystoma corruscans.jpg", "Wikimedia Commons"), commons("Pintado fish Pantanal.jpg", "Wikimedia Commons"), commons("Pseudoplatystoma corruscans head.jpg", "Wikimedia Commons")], sources: [{ title: "FishBase — Pseudoplatystoma corruscans", url: "https://www.fishbase.se/summary/Pseudoplatystoma-corruscans.html" }]
  },
  {
    id: "pacu", commonName: "Pacu", scientificName: "Piaractus mesopotamicus", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Peixe onívoro de água doce que se desloca entre rios, baías e áreas alagadas durante o ciclo de cheias.", physicalCharacteristics: "Corpo alto e comprimido, dentes fortes e coloração prateada com tons avermelhados.", habitat: "Rios, baías, corixos e lagoas conectadas durante as cheias.", behavior: "Forma cardumes e aproveita frutos e sementes que caem na água.", diet: "Frutos, sementes, plantas aquáticas e pequenos animais.", curiosities: ["Pode transportar sementes ao longo da rede de drenagem.", "A sazonalidade das cheias influencia alimentação e migração."], distribution: "Bacia do Paraguai e outras bacias do centro-sul da América do Sul.", ecologicalImportance: "Conecta a vegetação terrestre às cadeias alimentares aquáticas e dispersa sementes.", conservationStatus: "Pouco preocupante", images: [commons("Piaractus mesopotamicus.jpg", "Wikimedia Commons"), commons("Pacu fish underwater.jpg", "Wikimedia Commons"), commons("Piaractus mesopotamicus side.jpg", "Wikimedia Commons")], sources: [{ title: "FishBase — Piaractus mesopotamicus", url: "https://www.fishbase.se/summary/Piaractus-mesopotamicus.html" }]
  },
  {
    id: "piraputanga", commonName: "Piraputanga", scientificName: "Brycon hilarii", group: "Peixes", environments: ["Rios e corixos", "Matas"],
    description: "Peixe de água doce veloz, comum em rios de águas claras e associado a matas ciliares.", physicalCharacteristics: "Corpo prateado, dorso escuro, nadadeira caudal avermelhada e escamas bem marcadas.", habitat: "Rios, córregos e trechos com correnteza e vegetação nas margens.", behavior: "Nada em cardumes e explora frutos, sementes e pequenos organismos.", diet: "Frutos, sementes, insetos e pequenos invertebrados aquáticos.", curiosities: ["A mata ciliar fornece alimento que cai sobre a água.", "É uma espécie apreciada na pesca esportiva e na culinária regional."], distribution: "Bacias do Paraguai e do Paraná, incluindo rios do Pantanal.", ecologicalImportance: "Ajuda a transportar matéria orgânica entre a mata ciliar e o rio.", conservationStatus: "Pouco preocupante", images: [commons("Brycon hilarii.jpg", "Wikimedia Commons"), commons("Piraputanga fish.jpg", "Wikimedia Commons"), commons("Brycon hilarii river.jpg", "Wikimedia Commons")], sources: [{ title: "FishBase — Brycon hilarii", url: "https://www.fishbase.se/summary/Brycon-hilarii.html" }]
  },
  {
    id: "caranguejo-agua-doce", commonName: "Caranguejo-de-água-doce", scientificName: "Dilocarcinus pagei", group: "Invertebrados", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Caranguejo de água doce encontrado em ambientes lênticos e margens de rios da bacia do Paraguai.", physicalCharacteristics: "Carapaça achatada, pinças desenvolvidas e coloração castanha a avermelhada.", habitat: "Lagoas, baías, corixos, margens e vegetação aquática.", behavior: "Utiliza o fundo e a vegetação para buscar alimento e abrigo.", diet: "Detritos, algas, matéria vegetal e pequenos organismos.", curiosities: ["A espécie participa da decomposição de matéria orgânica aquática.", "A disponibilidade de abrigo varia com a cheia e a seca."], distribution: "Bacias interiores da América do Sul, incluindo a bacia do Paraguai.", ecologicalImportance: "Recicla matéria orgânica e serve de alimento para peixes e aves aquáticas.", conservationStatus: "Dados insuficientes", images: [commons("Dilocarcinus pagei.jpg", "Wikimedia Commons"), commons("Freshwater crab Pantanal.jpg", "Wikimedia Commons"), commons("Dilocarcinus pagei carapace.jpg", "Wikimedia Commons")], sources: [{ title: "WoRMS — Dilocarcinus pagei", url: "https://www.marinespecies.org/aphia.php?p=taxdetails&id=439231" }]
  },
  {
    id: "camarao-agua-doce", commonName: "Camarão-da-amazônia", scientificName: "Macrobrachium amazonicum", group: "Invertebrados", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Camarão de água doce associado a rios, lagoas e áreas alagáveis de diversas bacias brasileiras.", physicalCharacteristics: "Corpo segmentado, rostro alongado e primeiro par de quelas desenvolvido.", habitat: "Rios, lagoas, baías e áreas de vegetação aquática.", behavior: "Busca alimento no fundo e entre plantas, com atividade variável ao longo do dia.", diet: "Detritos, algas, pequenos invertebrados e matéria orgânica.", curiosities: ["O ciclo de vida pode usar águas doces e ambientes com maior salinidade em diferentes populações.", "É uma espécie relevante para cadeias alimentares e para comunidades ribeirinhas."], distribution: "Ampla distribuição na América do Sul, com registros em bacias brasileiras.", ecologicalImportance: "Transfere energia do detrito e da vegetação para peixes e aves aquáticas.", conservationStatus: "Pouco preocupante", images: [commons("Macrobrachium amazonicum.jpg", "Wikimedia Commons"), commons("Amazon river prawn.jpg", "Wikimedia Commons"), commons("Macrobrachium amazonicum closeup.jpg", "Wikimedia Commons")], sources: [{ title: "FishBase — Macrobrachium amazonicum", url: "https://www.fishbase.se/summary/Macrobrachium-amazonicum.html" }]
  },
  {
    id: "bugio-preto", commonName: "Bugio-preto", scientificName: "Alouatta caraya", group: "Mamíferos", environments: ["Matas", "Bordas de mata"],
    description: "Primata de vocalização potente, associado a matas ciliares e capões do Pantanal.", physicalCharacteristics: "Pelagem escura nos machos, rosto marcado e cauda preênsil.", habitat: "Matas ciliares, capões e bordas de floresta.", behavior: "Vive em grupos e emite vocalizações territoriais ao amanhecer.", diet: "Folhas, frutos, flores e brotos.", curiosities: ["As vocalizações podem ser ouvidas a grandes distâncias.", "A cauda auxilia na locomoção entre galhos."], distribution: "Centro e leste da América do Sul, incluindo o Pantanal.", ecologicalImportance: "Dispersa sementes e influencia a regeneração das matas.", conservationStatus: "Pouco preocupante", images: [commons("Alouatta caraya.jpg", "Wikimedia Commons"), commons("Alouatta caraya male.jpg", "Wikimedia Commons"), commons("Black howler monkey.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Alouatta caraya", url: "https://www.iucnredlist.org/search?query=Alouatta%20caraya&searchType=species" }]
  },
  {
    id: "ariranha", commonName: "Ariranha", scientificName: "Pteronura brasiliensis", group: "Mamíferos", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Mamífero social e semiaquático que caça em rios, baías e corixos do Pantanal.", physicalCharacteristics: "Corpo alongado, patas palmadas, cauda forte e manchas claras no pescoço.", habitat: "Rios, lagoas, baías e margens com abrigo vegetal.", behavior: "Vive em grupos familiares, vocaliza e caça principalmente peixes.", diet: "Peixes, crustáceos e pequenos vertebrados aquáticos.", curiosities: ["Cada indivíduo pode apresentar marcas claras distintas no pescoço.", "A espécie depende de águas relativamente preservadas e conectadas."], distribution: "Bacias hidrográficas da América do Sul, com população importante no Pantanal.", ecologicalImportance: "É predadora de topo dos ambientes aquáticos e indica a qualidade dos rios.", conservationStatus: "Em perigo", images: [commons("Pteronura brasiliensis.jpg", "Wikimedia Commons"), commons("Giant otter Pantanal.jpg", "Wikimedia Commons"), commons("Giant otter swimming.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Pteronura brasiliensis", url: "https://www.iucnredlist.org/search?query=Pteronura%20brasiliensis&searchType=species" }]
  },
  {
    id: "lontra-neotropical", commonName: "Lontra-neotropical", scientificName: "Lontra longicaudis", group: "Mamíferos", environments: ["Rios e corixos", "Matas"],
    description: "Lontra de hábitos discretos que utiliza rios, córregos e lagoas com margens vegetadas.", physicalCharacteristics: "Corpo fusiforme, patas parcialmente palmadas e pelagem marrom densa.", habitat: "Cursos d’água, lagoas e matas ciliares.", behavior: "Solta ou em pequenos grupos, nada com agilidade e repousa em tocas e barrancos.", diet: "Peixes, crustáceos, anfíbios e pequenos vertebrados.", curiosities: ["Pode deixar marcas e fezes em pontos de passagem nas margens.", "A vegetação ciliar oferece abrigo e locais de descanso."], distribution: "América Central e América do Sul, incluindo o Pantanal.", ecologicalImportance: "Participa do controle de organismos aquáticos e conecta ambientes terrestres e aquáticos.", conservationStatus: "Quase ameaçada", images: [commons("Lontra longicaudis.jpg", "Wikimedia Commons"), commons("Neotropical otter river.jpg", "Wikimedia Commons"), commons("Lontra longicaudis swimming.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Lontra longicaudis", url: "https://www.iucnredlist.org/search?query=Lontra%20longicaudis&searchType=species" }]
  },
  {
    id: "queixada", commonName: "Queixada", scientificName: "Tayassu pecari", group: "Mamíferos", environments: ["Matas", "Campos"],
    description: "Porco-do-mato social que percorre grandes áreas em busca de frutos, raízes e invertebrados.", physicalCharacteristics: "Pelagem escura, faixa clara no queixo e corpo compacto.", habitat: "Matas, cerrados, capões e bordas de mata.", behavior: "Forma bandos numerosos, desloca-se por longas distâncias e usa vocalizações de contato.", diet: "Frutos, sementes, raízes, folhas e pequenos animais.", curiosities: ["Bandos grandes podem modificar o solo ao forragear.", "A espécie é sensível à fragmentação e à caça."], distribution: "América Central e América do Sul, com ocorrência no Pantanal.", ecologicalImportance: "Dispersa sementes e movimenta a camada superficial do solo.", conservationStatus: "Vulnerável", images: [commons("Tayassu pecari.jpg", "Wikimedia Commons"), commons("White-lipped peccary group.jpg", "Wikimedia Commons"), commons("Tayassu pecari Pantanal.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Tayassu pecari", url: "https://www.iucnredlist.org/search?query=Tayassu%20pecari&searchType=species" }]
  },
  {
    id: "mutum-de-penacho", commonName: "Mutum-de-penacho", scientificName: "Crax fasciolata", group: "Aves", environments: ["Matas", "Bordas de mata"],
    description: "Ave terrestre de grande porte encontrada em matas e bordas com oferta de frutos.", physicalCharacteristics: "Crista encaracolada, corpo robusto e dimorfismo entre machos e fêmeas.", habitat: "Matas ciliares, capões e bordas de floresta.", behavior: "Forrageia no chão e pode empoleirar-se em árvores ao anoitecer.", diet: "Frutos, sementes, folhas e pequenos invertebrados.", curiosities: ["Machos e fêmeas possuem padrões de plumagem diferentes.", "A espécie pode ser ouvida antes de ser avistada."], distribution: "Brasil central e meridional, Bolívia e Paraguai.", ecologicalImportance: "Dispersa sementes de plantas das matas pantaneiras.", conservationStatus: "Vulnerável", images: [commons("Crax fasciolata.jpg", "Wikimedia Commons"), commons("Bare-faced curassow.jpg", "Wikimedia Commons"), commons("Crax fasciolata male.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Crax fasciolata", url: "https://www.iucnredlist.org/search?query=Crax%20fasciolata&searchType=species" }]
  },
  {
    id: "carau", commonName: "Carão", scientificName: "Aramus guarauna", group: "Aves", environments: ["Áreas alagadas", "Rios e corixos"],
    description: "Ave de áreas úmidas, conhecida pelo chamado forte e pela busca de caramujos entre a vegetação.", physicalCharacteristics: "Plumagem parda estriada, pernas longas e bico curvo.", habitat: "Brejos, campos alagados, baías e margens com macrófitas.", behavior: "Caminha lentamente em águas rasas e vocaliza ao amanhecer e ao entardecer.", diet: "Principalmente caramujos e outros invertebrados aquáticos.", curiosities: ["O bico curvo ajuda a retirar moluscos das conchas.", "É frequentemente detectado pelo canto antes do avistamento."], distribution: "América Central e América do Sul, incluindo todo o Pantanal.", ecologicalImportance: "Regula populações de moluscos em áreas alagadas.", conservationStatus: "Pouco preocupante", images: [commons("Aramus guarauna.jpg", "Wikimedia Commons"), commons("Limpkin wetland.jpg", "Wikimedia Commons"), commons("Aramus guarauna Pantanal.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Aramus guarauna", url: "https://www.iucnredlist.org/search?query=Aramus%20guarauna&searchType=species" }]
  },
  {
    id: "seriema", commonName: "Seriema", scientificName: "Cariama cristata", group: "Aves", environments: ["Campos", "Bordas de mata"],
    description: "Ave corredora de campos e cerrados, reconhecida pela crista e pelo canto distante.", physicalCharacteristics: "Pernas longas, bico forte, crista frontal e plumagem acinzentada.", habitat: "Campos secos, cerrados e bordas de mata.", behavior: "Caminha pelo solo, corre diante de ameaças e caça presas pequenas.", diet: "Insetos, pequenos vertebrados, frutos e sementes.", curiosities: ["Seu chamado pode atravessar grandes áreas abertas.", "Pode usar o bico e as pernas para dominar pequenas presas."], distribution: "Centro e leste da América do Sul, incluindo o Pantanal.", ecologicalImportance: "Controla invertebrados e pequenos vertebrados dos campos.", conservationStatus: "Pouco preocupante", images: [commons("Cariama cristata.jpg", "Wikimedia Commons"), commons("Red-legged seriema.jpg", "Wikimedia Commons"), commons("Cariama cristata grassland.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Cariama cristata", url: "https://www.iucnredlist.org/search?query=Cariama%20cristata&searchType=species" }]
  },
  {
    id: "teiú", commonName: "Teiú", scientificName: "Salvator merianae", group: "Répteis", environments: ["Campos", "Bordas de mata"],
    description: "Lagarto de grande porte que ocupa campos, bordas e áreas próximas a habitações rurais.", physicalCharacteristics: "Corpo robusto, cauda longa, coloração escura com manchas claras e língua bifurcada.", habitat: "Campos, bordas de mata, solos arenosos e áreas antropizadas.", behavior: "Ativo durante o dia, explora o solo e abriga-se em tocas.", diet: "Frutos, ovos, insetos, pequenos vertebrados e carniça.", curiosities: ["É um onívoro oportunista.", "A língua auxilia na coleta de informações químicas do ambiente."], distribution: "Leste e centro da América do Sul, incluindo o Pantanal.", ecologicalImportance: "Contribui para a dispersão de sementes e o controle de pequenos animais.", conservationStatus: "Pouco preocupante", images: [commons("Salvator merianae.jpg", "Wikimedia Commons"), commons("Argentine black and white tegu.jpg", "Wikimedia Commons"), commons("Tegu lizard Pantanal.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Salvator merianae", url: "https://www.iucnredlist.org/search?query=Salvator%20merianae&searchType=species" }]
  },
  {
    id: "dourado", commonName: "Dourado", scientificName: "Salminus brasiliensis", group: "Peixes", environments: ["Rios e corixos"],
    description: "Peixe predador de rios, valorizado como indicador da conectividade e da qualidade dos ambientes aquáticos.", physicalCharacteristics: "Corpo alongado, coloração dourada e cabeça robusta.", habitat: "Rios com correnteza, corredeiras e trechos conectados às planícies de inundação.", behavior: "Predador ativo, desloca-se em busca de peixes e responde à dinâmica sazonal dos rios.", diet: "Peixes e outros organismos aquáticos.", curiosities: ["A migração depende da conectividade dos rios.", "É uma espécie importante para cadeias alimentares e pesca sustentável."], distribution: "Bacias do Paraná, Paraguai e Uruguai.", ecologicalImportance: "Regula populações de peixes e sinaliza a integridade dos corredores aquáticos.", conservationStatus: "Dados insuficientes", images: [commons("Salminus brasiliensis.jpg", "Wikimedia Commons"), commons("Dourado fish river.jpg", "Wikimedia Commons"), commons("Salminus brasiliensis closeup.jpg", "Wikimedia Commons")], sources: [{ title: "FishBase — Salminus brasiliensis", url: "https://www.fishbase.se/summary/Salminus-brasiliensis.html" }]
  },
  {
    id: "jaguatirica", commonName: "Jaguatirica", scientificName: "Leopardus pardalis", group: "Mamíferos", environments: ["Matas", "Bordas de mata"],
    description: "Felino de médio porte, noturno e discreto, associado a matas e corredores de vegetação.", physicalCharacteristics: "Pelagem amarelada com manchas e rosetas, cauda curta e olhos adaptados à baixa luz.", habitat: "Matas ciliares, capões, cerrados e bordas de mata.", behavior: "Solitária, territorial e principalmente noturna.", diet: "Pequenos mamíferos, aves, répteis e anfíbios.", curiosities: ["As manchas ajudam na camuflagem entre sombras e folhagem.", "Pode utilizar corredores de mata para se deslocar entre áreas."], distribution: "Ampla distribuição nas Américas, incluindo o Pantanal.", ecologicalImportance: "Controla populações de pequenos vertebrados.", conservationStatus: "Pouco preocupante", images: [commons("Leopardus pardalis.jpg", "Wikimedia Commons"), commons("Ocelot Pantanal.jpg", "Wikimedia Commons"), commons("Ocelot resting.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Leopardus pardalis", url: "https://www.iucnredlist.org/search?query=Leopardus%20pardalis&searchType=species" }]
  },
  {
    id: "mao-pelada", commonName: "Mão-pelada", scientificName: "Procyon cancrivorus", group: "Mamíferos", environments: ["Rios e corixos", "Matas"],
    description: "Mamífero noturno que explora margens de rios, áreas úmidas e matas em busca de alimento.", physicalCharacteristics: "Máscara facial escura, cauda anelada e dedos longos.", habitat: "Matas ciliares, banhados, rios e áreas alagadas.", behavior: "Noturno, solitário e habilidoso ao manipular alimentos com as patas.", diet: "Crustáceos, frutos, insetos, anfíbios e pequenos vertebrados.", curiosities: ["As patas sensíveis auxiliam na procura de alimento em água rasa.", "A cauda anelada é uma marca visual característica."], distribution: "América Central e América do Sul, incluindo o Pantanal.", ecologicalImportance: "Participa do controle de invertebrados e da dispersão de sementes.", conservationStatus: "Pouco preocupante", images: [commons("Procyon cancrivorus.jpg", "Wikimedia Commons"), commons("Crab-eating raccoon.jpg", "Wikimedia Commons"), commons("Procyon cancrivorus wetland.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Procyon cancrivorus", url: "https://www.iucnredlist.org/search?query=Procyon%20cancrivorus&searchType=species" }]
  },
  {
    id: "cachorro-do-mato", commonName: "Cachorro-do-mato", scientificName: "Cerdocyon thous", group: "Mamíferos", environments: ["Campos", "Bordas de mata"],
    description: "Canídeo generalista que ocupa campos, cerrados e bordas de mata no Pantanal.", physicalCharacteristics: "Pelagem cinza-amarronzada, pernas curtas e focinho estreito.", habitat: "Campos, cerrados, matas abertas e áreas alteradas.", behavior: "Atividade crepuscular e noturna, geralmente solitário ou em casal.", diet: "Frutos, insetos, pequenos vertebrados e carniça.", curiosities: ["Adapta-se a diferentes ambientes e recursos alimentares.", "Pode atuar como dispersor de sementes de frutos nativos."], distribution: "Grande parte da América do Sul, incluindo o Pantanal.", ecologicalImportance: "Conecta cadeias alimentares e dispersa sementes.", conservationStatus: "Pouco preocupante", images: [commons("Cerdocyon thous.jpg", "Wikimedia Commons"), commons("Crab-eating fox.jpg", "Wikimedia Commons"), commons("Cerdocyon thous cerrado.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Cerdocyon thous", url: "https://www.iucnredlist.org/search?query=Cerdocyon%20thous&searchType=species" }]
  },
  {
    id: "macaco-prego", commonName: "Macaco-prego", scientificName: "Sapajus cay", group: "Mamíferos", environments: ["Matas", "Bordas de mata"],
    description: "Primata arborícola inteligente, comum em fragmentos e corredores florestais do Pantanal.", physicalCharacteristics: "Corpo robusto, mãos hábeis, cauda semipreênsil e face expressiva.", habitat: "Matas ciliares, capões e bordas florestais.", behavior: "Diurno, social e ativo na copa e no sub-bosque.", diet: "Frutos, sementes, folhas, insetos e pequenos animais.", curiosities: ["Usa as mãos para explorar alimentos e objetos.", "Vive em grupos com relações sociais complexas."], distribution: "Centro-sul da América do Sul, com ocorrência no Pantanal.", ecologicalImportance: "Dispersa sementes e controla invertebrados.", conservationStatus: "Pouco preocupante", images: [commons("Sapajus cay.jpg", "Wikimedia Commons"), commons("Black-striped capuchin.jpg", "Wikimedia Commons"), commons("Sapajus cay tree.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Sapajus cay", url: "https://www.iucnredlist.org/search?query=Sapajus%20cay&searchType=species" }]
  },
  {
    id: "anhuma", commonName: "Anhuma", scientificName: "Anhima cornuta", group: "Aves", environments: ["Áreas alagadas", "Rios e corixos"],
    description: "Ave de áreas úmidas reconhecida pelo espinho córneo na cabeça e pelo chamado forte.", physicalCharacteristics: "Grande porte, corpo escuro, asas com esporões e projeção córnea na testa.", habitat: "Brejos, baías, campos alagados e margens com vegetação aquática.", behavior: "Alimenta-se em áreas úmidas e costuma permanecer em casais ou pequenos grupos.", diet: "Folhas, brotos, sementes e plantas aquáticas.", curiosities: ["O espinho frontal é uma estrutura queratinizada característica.", "Pode ser avistada em margens abertas de baías pantaneiras."], distribution: "Norte e centro da América do Sul, incluindo o Pantanal.", ecologicalImportance: "Participa do fluxo de energia entre vegetação aquática e consumidores.", conservationStatus: "Pouco preocupante", images: [commons("Anhima cornuta.jpg", "Wikimedia Commons"), commons("Horned screamer wetland.jpg", "Wikimedia Commons"), commons("Anhima cornuta Pantanal.jpg", "Wikimedia Commons")], sources: [{ title: "BirdLife Data Zone — Anhima cornuta", url: "https://datazone.birdlife.org/species/factsheet/horned-screamer-anhima-cornuta" }]
  },
  {
    id: "urubu-rei", commonName: "Urubu-rei", scientificName: "Sarcoramphus papa", group: "Aves", environments: ["Matas", "Bordas de mata"],
    description: "Abutre de grande porte que utiliza áreas abertas para planar e matas para abrigo.", physicalCharacteristics: "Plumagem branca e preta, cabeça colorida e bico forte.", habitat: "Matas, cerrados, bordas e grandes áreas abertas.", behavior: "Plana por longos períodos e localiza carcaças com auxílio de outras espécies.", diet: "Carcaças de animais.", curiosities: ["A cabeça sem penas facilita a higiene durante a alimentação.", "Pode aproveitar correntes térmicas para economizar energia."], distribution: "América Central e América do Sul, incluindo o Pantanal.", ecologicalImportance: "Remove carcaças e reduz riscos sanitários no ambiente.", conservationStatus: "Pouco preocupante", images: [commons("Sarcoramphus papa.jpg", "Wikimedia Commons"), commons("King vulture flight.jpg", "Wikimedia Commons"), commons("Sarcoramphus papa head.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Sarcoramphus papa", url: "https://www.iucnredlist.org/search?query=Sarcoramphus%20papa&searchType=species" }]
  },
  {
    id: "jacare-coroa", commonName: "Jacaré-coroa", scientificName: "Paleosuchus palpebrosus", group: "Répteis", environments: ["Rios e corixos", "Matas"],
    description: "Pequeno jacaré de água doce associado a córregos, rios e áreas de mata.", physicalCharacteristics: "Focinho curto, osteodermos marcados e corpo compacto.", habitat: "Córregos, riachos, rios de menor porte e margens sombreadas.", behavior: "Discreto, principalmente noturno e dependente de abrigos próximos à água.", diet: "Peixes, crustáceos, insetos e pequenos vertebrados.", curiosities: ["É uma das menores espécies de jacaré.", "A cobertura óssea protege o dorso contra impactos e predadores."], distribution: "Bacias da América do Sul, incluindo áreas do Pantanal.", ecologicalImportance: "Preda organismos aquáticos e ajuda a equilibrar cadeias de riachos.", conservationStatus: "Pouco preocupante", images: [commons("Paleosuchus palpebrosus.jpg", "Wikimedia Commons"), commons("Cuvier's dwarf caiman.jpg", "Wikimedia Commons"), commons("Paleosuchus palpebrosus river.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Paleosuchus palpebrosus", url: "https://www.iucnredlist.org/search?query=Paleosuchus%20palpebrosus&searchType=species" }]
  },
  {
    id: "traira", commonName: "Traíra", scientificName: "Hoplias malabaricus", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Peixe predador de águas calmas, comum em lagoas, corixos e áreas de vegetação aquática.", physicalCharacteristics: "Corpo alongado, boca ampla e coloração parda camuflada.", habitat: "Lagoas, baías, corixos, rios lentos e áreas alagadas.", behavior: "Predador de emboscada, permanece entre estruturas submersas.", diet: "Peixes, crustáceos, insetos e pequenos vertebrados aquáticos.", curiosities: ["A camuflagem favorece ataques rápidos a partir de abrigos.", "Tolera variações sazonais de oxigênio em águas rasas."], distribution: "Ampla distribuição em bacias sul-americanas, incluindo o Pantanal.", ecologicalImportance: "Regula populações de pequenos peixes e invertebrados aquáticos.", conservationStatus: "Pouco preocupante", images: [commons("Hoplias malabaricus.jpg", "Wikimedia Commons"), commons("Traira fish.jpg", "Wikimedia Commons"), commons("Hoplias malabaricus river.jpg", "Wikimedia Commons")], sources: [{ title: "FishBase — Hoplias malabaricus", url: "https://www.fishbase.se/summary/Hoplias-malabaricus.html" }]
  },
  {
    id: "cutia", commonName: "Cutia", scientificName: "Dasyprocta azarae", group: "Mamíferos", environments: ["Matas", "Bordas de mata"],
    description: "Roedor diurno que percorre o sub-bosque e enterra sementes em áreas de mata.", physicalCharacteristics: "Corpo compacto, pernas longas e pelagem castanha.", habitat: "Matas ciliares, capões e bordas florestais.", behavior: "Diurna, alerta e geralmente solitária ou em pares.", diet: "Frutos, sementes, brotos e raízes.", curiosities: ["Pode esconder sementes para consumo posterior.", "Seu comportamento ajuda a transportar sementes para longe da planta-mãe."], distribution: "Centro-sul da América do Sul, incluindo o Pantanal.", ecologicalImportance: "Dispersa e enterra sementes, contribuindo para a regeneração das matas.", conservationStatus: "Pouco preocupante", images: [commons("Dasyprocta azarae.jpg", "Wikimedia Commons"), commons("Azara's agouti.jpg", "Wikimedia Commons"), commons("Dasyprocta forest.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Dasyprocta azarae", url: "https://www.iucnredlist.org/search?query=Dasyprocta%20azarae&searchType=species" }]
  },
  {
    id: "paca", commonName: "Paca", scientificName: "Cuniculus paca", group: "Mamíferos", environments: ["Matas", "Rios e corixos"],
    description: "Roedor de hábitos crepusculares e noturnos, associado a matas próximas de água.", physicalCharacteristics: "Corpo robusto, manchas laterais claras e cabeça larga.", habitat: "Matas ciliares, capões e margens de rios.", behavior: "Discreta, escava tocas e busca frutos no solo.", diet: "Frutos, sementes e partes tenras de plantas.", curiosities: ["A proximidade da água oferece rotas de fuga e abrigo.", "É uma importante presa para grandes felinos e jacarés."], distribution: "América Central e América do Sul, incluindo o Pantanal.", ecologicalImportance: "Dispersa sementes e participa da cadeia alimentar terrestre.", conservationStatus: "Pouco preocupante", images: [commons("Cuniculus paca.jpg", "Wikimedia Commons"), commons("Lowland paca.jpg", "Wikimedia Commons"), commons("Cuniculus paca forest.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Cuniculus paca", url: "https://www.iucnredlist.org/search?query=Cuniculus%20paca&searchType=species" }]
  },
  {
    id: "gato-mourisco", commonName: "Gato-mourisco", scientificName: "Herpailurus yagouaroundi", group: "Mamíferos", environments: ["Campos", "Bordas de mata"],
    description: "Felino de corpo alongado que utiliza campos, cerrados e bordas de mata.", physicalCharacteristics: "Corpo esguio, pernas curtas, cabeça pequena e pelagem uniforme variável.", habitat: "Campos, cerrados, matas abertas e bordas.", behavior: "Solitário, ativo em diferentes horários e capaz de ocupar áreas alteradas.", diet: "Pequenos mamíferos, aves, répteis e invertebrados.", curiosities: ["A pelagem pode variar entre tons avermelhados, cinzentos ou escuros.", "Seu corpo alongado facilita a movimentação em vegetação densa."], distribution: "América Central e América do Sul, incluindo o Pantanal.", ecologicalImportance: "Controla pequenos vertebrados e invertebrados.", conservationStatus: "Pouco preocupante", images: [commons("Herpailurus yagouaroundi.jpg", "Wikimedia Commons"), commons("Jaguarundi grassland.jpg", "Wikimedia Commons"), commons("Herpailurus yagouaroundi profile.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Herpailurus yagouaroundi", url: "https://www.iucnredlist.org/search?query=Herpailurus%20yagouaroundi&searchType=species" }]
  },
  {
    id: "aracua", commonName: "Aracuã", scientificName: "Ortalis canicollis", group: "Aves", environments: ["Matas", "Bordas de mata"],
    description: "Ave social de bordas e matas abertas, reconhecida pelo chamado coletivo ruidoso.", physicalCharacteristics: "Corpo esguio, cauda longa e plumagem parda com garganta clara.", habitat: "Matas ciliares, capões e bordas de mata.", behavior: "Vive em grupos e desloca-se entre árvores e arbustos em busca de alimento.", diet: "Frutos, sementes, folhas e flores.", curiosities: ["Grupos podem vocalizar em coro ao amanhecer.", "É frequentemente avistada em árvores frutíferas."], distribution: "Centro da América do Sul, incluindo o Pantanal.", ecologicalImportance: "Dispersa sementes de espécies arbóreas e arbustivas.", conservationStatus: "Pouco preocupante", images: [commons("Ortalis canicollis.jpg", "Wikimedia Commons"), commons("Chaco chachalaca.jpg", "Wikimedia Commons"), commons("Ortalis canicollis group.jpg", "Wikimedia Commons")], sources: [{ title: "BirdLife Data Zone — Ortalis canicollis", url: "https://datazone.birdlife.org/species/factsheet/chaco-chachalaca-ortalis-canicollis" }]
  },
  {
    id: "soco-boi", commonName: "Socó-boi", scientificName: "Tigrisoma lineatum", group: "Aves", environments: ["Áreas alagadas", "Rios e corixos"],
    description: "Garça de hábitos discretos que caça em águas rasas e margens com vegetação.", physicalCharacteristics: "Pescoço longo, plumagem estriada e bico pontudo.", habitat: "Brejos, baías, corixos e margens de rios.", behavior: "Permanece imóvel à espera de presas e é mais ativo no crepúsculo.", diet: "Peixes, anfíbios, crustáceos e insetos aquáticos.", curiosities: ["A imobilidade ajuda a aproximar-se de presas aquáticas.", "A plumagem juvenil é bastante diferente da adulta."], distribution: "América Central e América do Sul, incluindo o Pantanal.", ecologicalImportance: "Controla organismos de áreas alagadas e integra cadeias aquáticas.", conservationStatus: "Pouco preocupante", images: [commons("Tigrisoma lineatum.jpg", "Wikimedia Commons"), commons("Rufescent tiger heron wetland.jpg", "Wikimedia Commons"), commons("Tigrisoma lineatum Pantanal.jpg", "Wikimedia Commons")], sources: [{ title: "BirdLife Data Zone — Tigrisoma lineatum", url: "https://datazone.birdlife.org/species/factsheet/rufescent-tiger-heron-tigrisoma-lineatum" }]
  },
  {
    id: "jacana", commonName: "Jaçanã", scientificName: "Jacana jacana", group: "Aves", environments: ["Áreas alagadas", "Rios e corixos"],
    description: "Ave de áreas alagadas que caminha sobre folhas flutuantes com dedos muito longos.", physicalCharacteristics: "Dedos e unhas alongados, corpo escuro e detalhes amarelos e vermelhos.", habitat: "Lagoas rasas, brejos e campos com plantas aquáticas flutuantes.", behavior: "Caminha sobre a vegetação e busca invertebrados entre folhas e água.", diet: "Insetos, pequenos invertebrados, sementes e matéria vegetal.", curiosities: ["Os dedos distribuem o peso sobre folhas flutuantes.", "Pode emitir chamados curtos quando alarmada."], distribution: "América Central e América do Sul, incluindo o Pantanal.", ecologicalImportance: "Controla invertebrados e movimenta nutrientes em áreas rasas.", conservationStatus: "Pouco preocupante", images: [commons("Jacana jacana.jpg", "Wikimedia Commons"), commons("Wattled jacana wetland.jpg", "Wikimedia Commons"), commons("Jacana jacana Pantanal.jpg", "Wikimedia Commons")], sources: [{ title: "BirdLife Data Zone — Jacana jacana", url: "https://datazone.birdlife.org/species/factsheet/wattled-jacana-jacana-jacana" }]
  },
  {
    id: "martim-pescador-grande", commonName: "Martim-pescador-grande", scientificName: "Megaceryle torquata", group: "Aves", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Ave ribeirinha que observa a água de poleiros e mergulha para capturar peixes.", physicalCharacteristics: "Bico grande, corpo robusto e crista evidente.", habitat: "Rios, lagoas, baías e margens abertas.", behavior: "Vigia a partir de galhos e realiza mergulhos rápidos.", diet: "Peixes, crustáceos e pequenos animais aquáticos.", curiosities: ["A posição do poleiro ajuda a calcular o mergulho.", "Pode ser observada em águas abertas e com boa visibilidade."], distribution: "Américas, incluindo todo o Pantanal.", ecologicalImportance: "Integra cadeias alimentares aquáticas e terrestres.", conservationStatus: "Pouco preocupante", images: [commons("Megaceryle torquata.jpg", "Wikimedia Commons"), commons("Ringed kingfisher river.jpg", "Wikimedia Commons"), commons("Megaceryle torquata Pantanal.jpg", "Wikimedia Commons")], sources: [{ title: "BirdLife Data Zone — Megaceryle torquata", url: "https://datazone.birdlife.org/species/factsheet/ringed-kingfisher-megaceryle-torquata" }]
  },
  {
    id: "curimbata", commonName: "Curimbatá", scientificName: "Prochilodus lineatus", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Peixe migrador de rios sul-americanos, importante para a dinâmica das cheias e cadeias aquáticas.", physicalCharacteristics: "Corpo fusiforme, boca adaptada à raspagem e escamas prateadas.", habitat: "Rios, canais, corixos e áreas inundadas durante a cheia.", behavior: "Forma cardumes e realiza deslocamentos sazonais para reprodução e alimentação.", diet: "Detritos, algas e matéria orgânica do fundo.", curiosities: ["A migração depende da conectividade dos rios.", "A alimentação no fundo movimenta sedimentos e nutrientes."], distribution: "Bacias do Paraná, Paraguai e Uruguai.", ecologicalImportance: "Transporta energia e nutrientes entre rios e planícies de inundação.", conservationStatus: "Pouco preocupante", images: [commons("Prochilodus lineatus.jpg", "Wikimedia Commons"), commons("Prochilodus fish.jpg", "Wikimedia Commons"), commons("Prochilodus lineatus river.jpg", "Wikimedia Commons")], sources: [{ title: "FishBase — Prochilodus lineatus", url: "https://www.fishbase.se/summary/Prochilodus-lineatus.html" }]
  },
  {
    id: "cagado-de-barbicha", commonName: "Cágado-de-barbicha", scientificName: "Phrynops geoffroanus", group: "Répteis", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Cágado de água doce que ocupa rios, lagoas e margens com abrigos disponíveis.", physicalCharacteristics: "Carapaça oval, cabeça larga e barbilhões sob o queixo.", habitat: "Rios, corixos, lagoas e margens de águas lentas.", behavior: "Aquático, oportunista e frequentemente observado tomando sol em troncos.", diet: "Peixes pequenos, invertebrados, carcaças e matéria vegetal.", curiosities: ["Os barbilhões ajudam na percepção do ambiente aquático.", "A qualidade das margens influencia seus locais de abrigo."], distribution: "Bacias do centro e leste da América do Sul, incluindo o Pantanal.", ecologicalImportance: "Participa do controle de organismos aquáticos e reciclagem de matéria.", conservationStatus: "Pouco preocupante", images: [commons("Phrynops geoffroanus.jpg", "Wikimedia Commons"), commons("Geoffroy's side-necked turtle.jpg", "Wikimedia Commons"), commons("Phrynops river turtle.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Phrynops geoffroanus", url: "https://www.iucnredlist.org/search?query=Phrynops%20geoffroanus&searchType=species" }]
  },
  {
    id: "cobra-verde", commonName: "Cobra-verde", scientificName: "Philodryas olfersii", group: "Répteis", environments: ["Matas", "Bordas de mata"],
    description: "Serpente arborícola de coloração verde, encontrada em matas, arbustos e bordas vegetadas.", physicalCharacteristics: "Corpo delgado, escamas verdes e cauda longa.", habitat: "Matas, capões, arbustos e bordas com vegetação densa.", behavior: "Diurna, ágil e predominantemente arborícola.", diet: "Pequenos vertebrados, anfíbios, lagartos e aves.", curiosities: ["A coloração oferece camuflagem entre folhas.", "Como toda serpente, deve ser observada sem tentativa de captura."], distribution: "América do Sul, incluindo o Pantanal.", ecologicalImportance: "Controla pequenos vertebrados e integra a cadeia alimentar das matas.", conservationStatus: "Pouco preocupante", images: [commons("Philodryas olfersii.jpg", "Wikimedia Commons"), commons("Philodryas green snake.jpg", "Wikimedia Commons"), commons("Philodryas olfersii vegetation.jpg", "Wikimedia Commons")], sources: [{ title: "IUCN Red List — Philodryas olfersii", url: "https://www.iucnredlist.org/search?query=Philodryas%20olfersii&searchType=species" }]
  },
  {
    id: "perereca-cabecuda", commonName: "Perereca-cabeçuda", scientificName: "Boana raniceps", group: "Anfíbios", environments: ["Áreas alagadas", "Bordas de mata"],
    description: "Anfíbio de áreas úmidas e bordas vegetadas, ativo principalmente à noite.", physicalCharacteristics: "Corpo esguio, olhos grandes, discos adesivos nos dedos e coloração variável.", habitat: "Brejos, lagoas temporárias, áreas alagadas e vegetação próxima à água.", behavior: "Noturna, vocaliza durante o período chuvoso e repousa na vegetação.", diet: "Insetos e outros pequenos invertebrados.", curiosities: ["O canto ajuda a localizar indivíduos durante a estação chuvosa.", "A pele sensível torna a espécie vulnerável à poluição da água."], distribution: "Centro e leste da América do Sul, incluindo o Pantanal.", ecologicalImportance: "Controla insetos e funciona como indicador de qualidade ambiental.", conservationStatus: "Pouco preocupante", images: [commons("Boana raniceps.jpg", "Wikimedia Commons"), commons("Boana frog wetland.jpg", "Wikimedia Commons"), commons("Boana raniceps vegetation.jpg", "Wikimedia Commons")], sources: [{ title: "Amphibian Species of the World — Boana raniceps", url: "https://amphibiansoftheworld.amnh.org/Amphibia/Anura/Hylidae/Hylinae/Boana/Boana-raniceps" }]
  },
  {
    id: "ra-quatro-olhos", commonName: "Rã-de-quatro-olhos", scientificName: "Pleurodema diplolister", group: "Anfíbios", environments: ["Campos", "Áreas alagadas"],
    description: "Pequena rã terrestre que aproveita poças temporárias formadas pelas chuvas.", physicalCharacteristics: "Corpo compacto, manchas dorsais e glândulas que lembram olhos na região posterior.", habitat: "Campos, solos arenosos e poças temporárias.", behavior: "Noturna e explosiva após chuvas intensas, quando se reproduz rapidamente.", diet: "Insetos e pequenos invertebrados.", curiosities: ["As poças temporárias são essenciais para seu ciclo reprodutivo.", "As marcas posteriores podem confundir predadores."], distribution: "Regiões abertas da América do Sul, com registros no centro do Brasil.", ecologicalImportance: "Controla invertebrados e serve de alimento para aves, répteis e mamíferos.", conservationStatus: "Pouco preocupante", images: [commons("Pleurodema diplolister.jpg", "Wikimedia Commons"), commons("Pleurodema frog sand.jpg", "Wikimedia Commons"), commons("Pleurodema diplolister wetland.jpg", "Wikimedia Commons")], sources: [{ title: "Amphibian Species of the World — Pleurodema diplolister", url: "https://amphibiansoftheworld.amnh.org/Amphibia/Anura/Leptodactylidae/Leiuperinae/Pleurodema/Pleurodema-diplolister" }]
  },
  {
    id: "piranha-vermelha", commonName: "Piranha-vermelha", scientificName: "Pygocentrus nattereri", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Peixe de dentes cortantes que ocupa águas lentas, baías, corixos e lagoas do Pantanal.", physicalCharacteristics: "Corpo alto, coloração prateada com ventre avermelhado e dentição forte.", habitat: "Rios lentos, baías, corixos e lagoas de planície de inundação.", behavior: "Forma cardumes e responde a oportunidades de alimentação e abrigo.", diet: "Peixes, invertebrados, frutos e matéria animal.", curiosities: ["A espécie participa de redes alimentares complexas, não sendo definida apenas por comportamento agressivo.", "A dinâmica de cheia influencia sua distribuição local."], distribution: "Bacias do norte e centro da América do Sul, incluindo o Pantanal.", ecologicalImportance: "Regula populações de peixes e recicla matéria orgânica.", conservationStatus: "Pouco preocupante", images: [commons("Pygocentrus nattereri.jpg", "Wikimedia Commons"), commons("Red-bellied piranha fish.jpg", "Wikimedia Commons"), commons("Pygocentrus nattereri river.jpg", "Wikimedia Commons")], sources: [{ title: "FishBase — Pygocentrus nattereri", url: "https://www.fishbase.se/summary/Pygocentrus-nattereri.html" }]
  },
  {
    id: "tuvira", commonName: "Tuvira", scientificName: "Gymnotus inaequilabiatus", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Peixe elétrico de águas calmas, ativo entre raízes, plantas e estruturas submersas.", physicalCharacteristics: "Corpo alongado, ausência de nadadeira dorsal e região anal ondulante.", habitat: "Corixos, lagoas, baías e margens com vegetação aquática.", behavior: "Noturna, usa sinais elétricos fracos para orientação e comunicação.", diet: "Invertebrados aquáticos e pequenos peixes.", curiosities: ["Os sinais elétricos auxiliam a navegação em água turva.", "A dinâmica das cheias amplia seu habitat disponível."], distribution: "Bacia do Paraguai e regiões associadas do centro da América do Sul.", ecologicalImportance: "Integra cadeias alimentares e controla pequenos organismos aquáticos.", conservationStatus: "Dados insuficientes", images: [commons("Gymnotus inaequilabiatus.jpg", "Wikimedia Commons"), commons("Gymnotus electric fish.jpg", "Wikimedia Commons"), commons("Gymnotus river fish.jpg", "Wikimedia Commons")], sources: [{ title: "FishBase — Gymnotus inaequilabiatus", url: "https://www.fishbase.se/summary/Gymnotus-inaequilabiatus.html" }]
  },
  {
    id: "morfoborboleta", commonName: "Borboleta-morfo", scientificName: "Morpho helenor", group: "Invertebrados", environments: ["Matas", "Bordas de mata"],
    description: "Borboleta de asas azuladas que frequenta clareiras, bordas e trilhas de mata.", physicalCharacteristics: "Asas amplas com brilho azul metálico nos machos e padrões de ocelos no verso.", habitat: "Matas ciliares, capões, clareiras e bordas florestais.", behavior: "Voa em trajetórias amplas e visita áreas ensolaradas para termorregulação.", diet: "Adultos consomem líquidos de frutos e matéria orgânica; lagartas usam plantas hospedeiras.", curiosities: ["O brilho azul resulta da estrutura das escamas, não de pigmento simples.", "O verso das asas é mais discreto e favorece a camuflagem."], distribution: "América Central e América do Sul, incluindo o Pantanal.", ecologicalImportance: "Participa da polinização e das cadeias alimentares de matas.", conservationStatus: "Dados insuficientes", images: [commons("Morpho helenor.jpg", "Wikimedia Commons"), commons("Morpho butterfly blue.jpg", "Wikimedia Commons"), commons("Morpho helenor forest.jpg", "Wikimedia Commons")], sources: [{ title: "GBIF — Morpho helenor", url: "https://www.gbif.org/species/search?q=Morpho%20helenor" }]
  },
  {
    id: "besouro-rola-bosta", commonName: "Besouro-rola-bosta", scientificName: "Deltochilum verruciferum", group: "Invertebrados", environments: ["Campos", "Matas"],
    description: "Besouro escarabeíneo que utiliza matéria orgânica e contribui para a ciclagem de nutrientes.", physicalCharacteristics: "Corpo compacto, pernas adaptadas à escavação e mandíbulas fortes.", habitat: "Campos, matas abertas e solos com disponibilidade de matéria orgânica.", behavior: "Localiza recursos pelo odor, forma e transporta pequenas bolas de material.", diet: "Material orgânico e fezes de vertebrados.", curiosities: ["O enterramento do recurso melhora a incorporação de nutrientes ao solo.", "A atividade varia com umidade e temperatura."], distribution: "América do Sul, com registros em ambientes brasileiros.", ecologicalImportance: "Recicla nutrientes, aerando o solo e dispersando sementes presentes no material orgânico.", conservationStatus: "Dados insuficientes", images: [commons("Deltochilum beetle.jpg", "Wikimedia Commons"), commons("Dung beetle rolling.jpg", "Wikimedia Commons"), commons("Scarabaeinae beetle.jpg", "Wikimedia Commons")], sources: [{ title: "GBIF — Deltochilum verruciferum", url: "https://www.gbif.org/species/search?q=Deltochilum%20verruciferum" }]
  },
  {
    id: "biguá", commonName: "Biguá", scientificName: "Nannopterum brasilianum", group: "Aves", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Ave aquática que mergulha para capturar peixes em rios, baías e corixos.", physicalCharacteristics: "Plumagem escura, pescoço longo e bico com ponta recurvada.", habitat: "Rios, lagoas, baías, corixos e margens abertas.", behavior: "Mergulha e nada com eficiência, secando as asas após a pesca.", diet: "Peixes, crustáceos e pequenos animais aquáticos.", curiosities: ["A plumagem pode ser aberta ao sol após mergulhos.", "É um indicador visual da presença de peixes em águas abertas."], distribution: "América Central e América do Sul, incluindo o Pantanal.", ecologicalImportance: "Participa do controle de peixes e da transferência de nutrientes entre água e terra.", conservationStatus: "Pouco preocupante", images: [commons("Nannopterum brasilianum.jpg", "Wikimedia Commons"), commons("Neotropic cormorant wetland.jpg", "Wikimedia Commons"), commons("Nannopterum brasilianum river.jpg", "Wikimedia Commons")], sources: [{ title: "BirdLife Data Zone — Nannopterum brasilianum", url: "https://datazone.birdlife.org/species/factsheet/neotropic-cormorant-nannopterum-brasilianum" }]
  },
  {
    id: "garca-moura", commonName: "Garça-moura", scientificName: "Ardea cocoi", group: "Aves", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Grande garça que caça imóvel em margens, campos inundados e águas rasas.", physicalCharacteristics: "Pescoço longo, pernas compridas, dorso cinza e peito claro.", habitat: "Rios, baías, brejos, corixos e campos alagados.", behavior: "Caminha lentamente ou permanece imóvel à espera de presas.", diet: "Peixes, anfíbios, répteis, crustáceos e pequenos mamíferos.", curiosities: ["A postura imóvel reduz o alerta das presas.", "Pode utilizar árvores altas para descanso e nidificação."], distribution: "América do Sul, incluindo todo o Pantanal.", ecologicalImportance: "Integra cadeias alimentares aquáticas e terrestres.", conservationStatus: "Pouco preocupante", images: [commons("Ardea cocoi.jpg", "Wikimedia Commons"), commons("Cocoi heron wetland.jpg", "Wikimedia Commons"), commons("Ardea cocoi Pantanal.jpg", "Wikimedia Commons")], sources: [{ title: "BirdLife Data Zone — Ardea cocoi", url: "https://datazone.birdlife.org/species/factsheet/cocoi-heron-ardea-cocoi" }]
  },
  {
    id: "soco-dorminhoco", commonName: "Socó-dorminhoco", scientificName: "Nycticorax nycticorax", group: "Aves", environments: ["Áreas alagadas", "Rios e corixos"],
    description: "Garça de hábitos crepusculares e noturnos que usa margens e vegetação aquática.", physicalCharacteristics: "Corpo compacto, olhos vermelhos no adulto e bico robusto.", habitat: "Brejos, lagoas, rios, canais e áreas alagadas com abrigo.", behavior: "Descansa durante o dia e sai para caçar no crepúsculo e à noite.", diet: "Peixes, anfíbios, insetos, crustáceos e pequenos vertebrados.", curiosities: ["Jovens possuem plumagem marrom estriada bem diferente da adulta.", "Pode formar colônias de reprodução em árvores próximas à água."], distribution: "Américas e outras regiões, com ocorrência ampla no Pantanal.", ecologicalImportance: "Controla organismos aquáticos e terrestres em áreas úmidas.", conservationStatus: "Pouco preocupante", images: [commons("Nycticorax nycticorax.jpg", "Wikimedia Commons"), commons("Black-crowned night heron wetland.jpg", "Wikimedia Commons"), commons("Nycticorax nycticorax Pantanal.jpg", "Wikimedia Commons")], sources: [{ title: "BirdLife Data Zone — Nycticorax nycticorax", url: "https://datazone.birdlife.org/species/factsheet/black-crowned-night-heron-nycticorax-nycticorax" }]
  },
  {
    id: "coruja-buraqueira", commonName: "Coruja-buraqueira", scientificName: "Athene cunicularia", group: "Aves", environments: ["Campos", "Bordas de mata"],
    description: "Coruja terrestre que ocupa campos abertos e utiliza tocas para abrigo e reprodução.", physicalCharacteristics: "Corpo pequeno, olhos amarelos, pernas longas e postura ereta.", habitat: "Campos, pastagens, áreas abertas e margens de estradas rurais.", behavior: "Ativa de dia e à noite, observando o entorno a partir do solo ou de poleiros baixos.", diet: "Insetos, pequenos roedores, lagartos e anfíbios.", curiosities: ["Pode ocupar tocas abandonadas por mamíferos.", "Movimenta a cabeça e o corpo com rapidez ao investigar ameaças."], distribution: "Américas, incluindo o Pantanal.", ecologicalImportance: "Controla insetos e pequenos vertebrados em áreas abertas.", conservationStatus: "Pouco preocupante", images: [commons("Athene cunicularia.jpg", "Wikimedia Commons"), commons("Burrowing owl grassland.jpg", "Wikimedia Commons"), commons("Athene cunicularia Pantanal.jpg", "Wikimedia Commons")], sources: [{ title: "BirdLife Data Zone — Athene cunicularia", url: "https://datazone.birdlife.org/species/factsheet/burrowing-owl-athene-cunicularia" }]
  },
  {
    id: "lambari-do-pantanal", commonName: "Lambari", scientificName: "Astyanax lacustris", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Pequeno peixe de cardume presente em águas calmas e correntes da planície de inundação.", physicalCharacteristics: "Corpo prateado, escamas pequenas e nadadeiras delicadas.", habitat: "Rios, corixos, lagoas e campos inundados.", behavior: "Forma cardumes e procura alimento entre plantas e margens.", diet: "Insetos, algas, frutos e pequenos invertebrados.", curiosities: ["Cardumes respondem rapidamente a sombras e movimentos na margem.", "Pequenos peixes são importantes para predadores maiores."], distribution: "Bacias do centro e sul do Brasil, incluindo o sistema do Paraguai.", ecologicalImportance: "Transfere energia de pequenos recursos para peixes, aves e répteis predadores.", conservationStatus: "Pouco preocupante", images: [commons("Astyanax lacustris.jpg", "Wikimedia Commons"), commons("Lambari fish school.jpg", "Wikimedia Commons"), commons("Astyanax river fish.jpg", "Wikimedia Commons")], sources: [{ title: "FishBase — Astyanax lacustris", url: "https://www.fishbase.se/summary/Astyanax-lacustris.html" }]
  },
  {
    id: "mandi", commonName: "Mandi", scientificName: "Pimelodus maculatus", group: "Peixes", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Bagre de fundo que procura alimento entre pedras, troncos e sedimentos dos rios.", physicalCharacteristics: "Barbilhões longos, manchas no corpo e nadadeiras com espinhos.", habitat: "Rios, canais, corixos e trechos com fundo variado.", behavior: "Mais ativo ao entardecer e durante a noite, explorando o fundo.", diet: "Invertebrados, pequenos peixes e matéria orgânica.", curiosities: ["Os barbilhões ajudam a encontrar alimento em água turva.", "A conectividade dos rios favorece seus deslocamentos."], distribution: "Bacias do Paraná, Paraguai e outras bacias sul-americanas.", ecologicalImportance: "Recicla matéria orgânica e participa da cadeia alimentar aquática.", conservationStatus: "Pouco preocupante", images: [commons("Pimelodus maculatus.jpg", "Wikimedia Commons"), commons("Mandi catfish river.jpg", "Wikimedia Commons"), commons("Pimelodus maculatus fish.jpg", "Wikimedia Commons")], sources: [{ title: "FishBase — Pimelodus maculatus", url: "https://www.fishbase.se/summary/Pimelodus-maculatus.html" }]
  },
  {
    id: "pitu", commonName: "Pitu", scientificName: "Macrobrachium amazonicum", group: "Invertebrados", environments: ["Rios e corixos", "Áreas alagadas"],
    description: "Camarão de água doce que ocupa rios, lagoas e áreas inundadas com abrigo vegetal.", physicalCharacteristics: "Corpo segmentado, antenas longas e quelas desenvolvidas.", habitat: "Rios, corixos, lagoas, raízes submersas e margens vegetadas.", behavior: "Explora o fundo e a vegetação, especialmente no período noturno.", diet: "Detritos, algas, pequenos animais e matéria orgânica.", curiosities: ["A forma do corpo permite esconder-se em raízes e folhas submersas.", "As cheias ampliam os locais disponíveis para alimentação e dispersão."], distribution: "Bacias sul-americanas, com registros em ambientes de água doce brasileiros.", ecologicalImportance: "Recicla matéria orgânica e serve de alimento para peixes e aves.", conservationStatus: "Dados insuficientes", images: [commons("Macrobrachium amazonicum.jpg", "Wikimedia Commons"), commons("Amazon river prawn.jpg", "Wikimedia Commons"), commons("Macrobrachium freshwater.jpg", "Wikimedia Commons")], sources: [{ title: "GBIF — Macrobrachium amazonicum", url: "https://www.gbif.org/species/search?q=Macrobrachium%20amazonicum" }]
  },
  {
    id: "libelula-pantaneira", commonName: "Libélula pantaneira", scientificName: "Pantala flavescens", group: "Invertebrados", environments: ["Áreas alagadas", "Campos"],
    description: "Libélula migratória observada sobre áreas abertas e corpos d'água temporários.", physicalCharacteristics: "Asas longas, abdômen estreito e coloração amarelada a castanha.", habitat: "Lagoas temporárias, brejos, campos e áreas abertas próximas à água.", behavior: "Voa longas distâncias e caça insetos durante o dia.", diet: "Mosquitos, moscas e outros insetos voadores.", curiosities: ["A espécie é conhecida por deslocamentos de longa distância.", "As ninfas vivem na água antes da metamorfose."], distribution: "Amplamente distribuída em regiões tropicais e subtropicais, incluindo o Pantanal.", ecologicalImportance: "Controla insetos voadores e conecta ambientes aquáticos e terrestres.", conservationStatus: "Pouco preocupante", images: [commons("Pantala flavescens.jpg", "Wikimedia Commons"), commons("Wandering glider dragonfly.jpg", "Wikimedia Commons"), commons("Pantala dragonfly wetland.jpg", "Wikimedia Commons")], sources: [{ title: "GBIF — Pantala flavescens", url: "https://www.gbif.org/species/search?q=Pantala%20flavescens" }]
  },
];

const isHttpUrl = (value: string) => /^https?:\/\/\S+$/i.test(value);

export function validateSpeciesCatalog(items: Species[] = species): string[] {
  const errors: string[] = [];
  const ids = new Set<string>();
  items.forEach((item, index) => {
    const prefix = `species[${index}](${item.id || "sem-id"})`;
    if (!item.id || ids.has(item.id)) errors.push(`${prefix}.id deve ser único e não vazio`);
    ids.add(item.id);
    if (!item.commonName.trim()) errors.push(`${prefix}.commonName ausente`);
    if (!item.scientificName.trim()) errors.push(`${prefix}.scientificName ausente`);
    if (!groups.includes(item.group)) errors.push(`${prefix}.group inválido`);
    if (item.environments.length === 0 || item.environments.some((environment) => !environments.includes(environment))) errors.push(`${prefix}.environments inválido`);
    for (const field of ["description", "physicalCharacteristics", "habitat", "behavior", "diet", "distribution", "ecologicalImportance"] as const) {
      if (!item[field]?.trim()) errors.push(`${prefix}.${field} ausente`);
    }
    if (item.curiosities.length === 0 || item.curiosities.some((curiosity) => !curiosity.trim())) errors.push(`${prefix}.curiosities inválido`);
    if (item.images.length < 3) errors.push(`${prefix}.images deve ter pelo menos 3 imagens`);
    item.images.forEach((image, imageIndex) => {
      if (!image.uri || !isHttpUrl(image.uri) || !image.author || !image.license || !isHttpUrl(image.sourceUrl) || !image.credit) errors.push(`${prefix}.images[${imageIndex}] sem crédito/licença/fonte completos`);
    });
    if (item.sources.length === 0 || item.sources.some((source) => !source.title.trim() || !isHttpUrl(source.url))) errors.push(`${prefix}.sources inválido`);
  });
  return errors;
}


const ISO_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
const TIME_PATTERN = /^(?:[01]\d|2[0-3]):[0-5]\d$/;

export function isValidSightingDate(value: string): boolean {
  if (!ISO_DATE_PATTERN.test(value)) return false;
  const parsed = new Date(`${value}T00:00:00Z`);
  return !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value;
}

export function isValidSightingTime(value: string): boolean {
  return value === "" || TIME_PATTERN.test(value);
}

export function isValidCoordinatePair(latitude: unknown, longitude: unknown): boolean {
  if (latitude === undefined && longitude === undefined) return true;
  return typeof latitude === "number" && Number.isFinite(latitude) && latitude >= -90 && latitude <= 90 &&
    typeof longitude === "number" && Number.isFinite(longitude) && longitude >= -180 && longitude <= 180;
}

export function sanitizeStoredSightings(value: unknown): Sighting[] {
  if (!Array.isArray(value)) return [];
  return value.filter((item): item is Sighting => {
    if (!item || typeof item !== "object") return false;
    const sighting = item as Partial<Sighting>;
    const quantityIsValid = sighting.quantity === undefined ||
      (typeof sighting.quantity === "number" && Number.isInteger(sighting.quantity) && sighting.quantity > 0);
    const timeIsValid = sighting.time === undefined || (typeof sighting.time === "string" && isValidSightingTime(sighting.time));
    return typeof sighting.id === "string" && sighting.id.length > 0 &&
      typeof sighting.speciesId === "string" && species.some((entry) => entry.id === sighting.speciesId) &&
      typeof sighting.date === "string" && isValidSightingDate(sighting.date) &&
      typeof sighting.createdAt === "string" && typeof sighting.updatedAt === "string" &&
      ["exact", "approximate", "municipality", "none"].includes(sighting.locationPrecision ?? "") &&
      ["private", "shareable"].includes(sighting.visibility ?? "") &&
      timeIsValid && isValidCoordinatePair(sighting.latitude, sighting.longitude) && quantityIsValid;
  });
}

export function sanitizeSettings(value: unknown): { defaultLanguage: string; quickLanguages: string[] } {
  const fallback = { defaultLanguage: "Português", quickLanguages: ["Português", "English"] };
  if (!value || typeof value !== "object") return fallback;
  const candidate = value as { defaultLanguage?: unknown; quickLanguages?: unknown };
  const quickLanguages = Array.isArray(candidate.quickLanguages) ? candidate.quickLanguages.filter((item): item is string => typeof item === "string" && languages.includes(item)) : fallback.quickLanguages;
  const safeQuickLanguages = quickLanguages.length ? Array.from(new Set(quickLanguages)) : fallback.quickLanguages;
  const defaultLanguage = typeof candidate.defaultLanguage === "string" && languages.includes(candidate.defaultLanguage) ? candidate.defaultLanguage : safeQuickLanguages[0];
  return { defaultLanguage, quickLanguages: safeQuickLanguages };
}
